
---Build Orphan record Deletion 

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.CONTACT_PERSON where CONTACT_PERSON_ID not in
(SELECT CONTACT_PERSON_ID from  ODS_GRS_NO.DBO.CONTACT_OBJECT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='CONTACT_PERSON' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.CONT_PERS_COM where CONTACT_PERSON_ID not in
(SELECT CONTACT_PERSON_ID from  ODS_GRS_NO.DBO.CONTACT_OBJECT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='CONT_PERS_COM' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.CONT_PERS_FUNC where CONTACT_PERSON_ID not in
(SELECT CONTACT_PERSON_ID from  ODS_GRS_NO.DBO.CONTACT_OBJECT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='CONT_PERS_FUNC' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;


Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.REPORT_CONTACT_OBJECT where CONTACT_PERSON_ID not in
(SELECT CONTACT_PERSON_ID from  ODS_GRS_NO.DBO.CONTACT_OBJECT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='REPORT_CONTACT_OBJECT' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;




Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.REPORT_MARK_FOLDER where REPORT_MARK_FOLDER_ID not in
(SELECT REPORT_MARK_FOLDER_ID from  ODS_GRS_NO.DBO.GRSR_CUSTOMER_REPORT_MARK_FOLDER)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='REPORT_MARK_FOLDER' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.GD where REPORT_MARK_FOLDER_ID not in
(SELECT REPORT_MARK_FOLDER_ID from  ODS_GRS_NO.DBO.GRSR_CUSTOMER_REPORT_MARK_FOLDER)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='GD' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.REPORT_MARK_FOLDER_ITEM where REPORT_MARK_FOLDER_ID not in
(SELECT REPORT_MARK_FOLDER_ID from  ODS_GRS_NO.DBO.GRSR_CUSTOMER_REPORT_MARK_FOLDER)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='REPORT_MARK_FOLDER_ITEM' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.REPORT_MARK_FOLDER_ITEM_COMBI where REPORT_MARK_FOLDER_ID not in
(SELECT REPORT_MARK_FOLDER_ID from  ODS_GRS_NO.DBO.GRSR_CUSTOMER_REPORT_MARK_FOLDER)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='REPORT_MARK_FOLDER_ITEM_COMBI' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.REPORT_MARK_FOLDER_ITEM_EMP where REPORT_MARK_FOLDER_ID not in
(SELECT REPORT_MARK_FOLDER_ID from  ODS_GRS_NO.DBO.GRSR_CUSTOMER_REPORT_MARK_FOLDER)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='REPORT_MARK_FOLDER_ITEM_EMP' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.REPORT_MARK_FOLDER_ITEM_GD where REPORT_MARK_FOLDER_ID not in
(SELECT REPORT_MARK_FOLDER_ID from  ODS_GRS_NO.DBO.GRSR_CUSTOMER_REPORT_MARK_FOLDER)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='REPORT_MARK_FOLDER_ITEM_GD' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;






Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.GUARD_ORDER where GUARD_ORDER_ID not in
(SELECT GUARD_ORDER_ID from  ODS_GRS_NO.DBO.GUARD_OBJECT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='GUARD_ORDER' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO..GUARD_ORDER_CULTURE  where GUARD_ORDER_ID not in
(SELECT GUARD_ORDER_ID from  ODS_GRS_NO.DBO.GUARD_OBJECT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='.GUARD_ORDER_CULTURE ' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.GUARD_ORDER_ENDTEXT_CULTURE where GUARD_ORDER_ID not in
(SELECT GUARD_ORDER_ID from  ODS_GRS_NO.DBO.GUARD_OBJECT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='GUARD_ORDER_ENDTEXT_CULTURE' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;



/* 
--GUARD_ORDER_RECEIPT table is not in scope 
Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.GUARD_ORDER_RECEIPT where GUARD_ORDER_ID not in
(SELECT GUARD_ORDER_ID from  ODS_GRS_NO.DBO.GUARD_OBJECT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='GUARD_ORDER_RECEIPT' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;
*/
