
---Build Orphan record Deletion 


Alter table DW.CONTROL.LOADPROCESS Add (ORPHANDELETE_EXPRESSIONS VARCHAR); 
Alter table DW.CONTROL.LOADPROCESS Add (ISORPHANDELETE BOOLEAN);


Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.CONTR_PART_VER where CONTRACT_ID not in
(SELECT CONTRACT_ID from  ODS_GRS_NO.DBO.CONTRACT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='CONTR_PART_VER' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.CONTRACT_PART where CONTRACT_ID not in
(SELECT CONTRACT_ID from  ODS_GRS_NO.DBO.CONTRACT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='CONTRACT_PART' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;

Update DW.CONTROL.LOADPROCESS set
ORPHANDELETE_EXPRESSIONS = 'Delete from ODS_GRS_NO.DBO.CUSTOMER_OBJECT where CUST_OBJ_ID not in
(SELECT CUST_OBJ_ID from  ODS_GRS_NO.DBO.CUST_CUST_OBJECT)',
ISORPHANDELETE=TRUE
where ODSTABLENAME ='CUSTOMER_OBJECT' and SOURCESYSTEMID = 1  and RESTRICTEDTABLE_RANK=3;



CREATE OR REPLACE secure VIEW DW.CONTROL.SOURCESYSTEM_LOADPROCESS3 AS 
With PSEUDONYMISEDCOLUMNLISTEXP AS 
  (
	SELECT a.SOURCESYSTEMID,a.SOURCESYSTEMNAME,NVL(a.Column_List||','||b.Column_List_exp,a.Column_List) ColumnListExp,a.STAGEDATABASENAME,a.STAGETABLENAME from   
     (
     SELECT c.SOURCESYSTEMID,s.SOURCESYSTEMNAME,c.STAGEDATABASENAME,c.STAGETABLENAME,
    listagg( NVL(EXPRESSIONS,'') || '  "' ||(STAGETABLECOLUMN) ||'" as ' ||UPPER(STAGETABLECOLUMN), ',') 
        within GROUP (ORDER BY (c.STAGETABLENAME)) AS Column_List
    FROM "DW"."CONTROL"."COLUMNDETAILS" c, "DW"."CONTROL"."SOURCESYSTEM" s WHERE 
    c.ACTIVEFLAG = 'TRUE' 
    AND NVL(ISPSEUDONYMISED,'FALSE')  = 'FALSE'
    AND c.SOURCESYSTEMID=s.SOURCESYSTEMID
   -- AND SOURCESYSTEMID=3 
    GROUP BY c.SOURCESYSTEMID,s.SOURCESYSTEMNAME,c.STAGEDATABASENAME,c.STAGETABLENAME) a 
    LEFT OUTER JOIN 
     (SELECT c.SOURCESYSTEMID,s.SOURCESYSTEMNAME,c.STAGEDATABASENAME,c.STAGETABLENAME,
    listagg( NVL('encrypt("'||c.STAGETABLECOLUMN||'",'||ks.PASSPHRASE||','''||ks.KEY_VALUE||''','''||ks.ADVANCED_ENCRYPTION_STD||''')','') || ' ' ||UPPER(c.STAGETABLECOLUMN), '  ,') 
        within GROUP (ORDER BY (c.STAGETABLENAME)) AS Column_List_exp
    FROM "DW"."CONTROL"."COLUMNDETAILS" c, "DW"."CONTROL"."KEYSTORE" ks, "DW"."CONTROL"."SOURCESYSTEM" s WHERE 
    c.ACTIVEFLAG = 'TRUE'
    AND c.ISPSEUDONYMISED  = 'TRUE' AND c.SOURCESYSTEMID=s.SOURCESYSTEMID AND s.SOURCESYSTEMNAME=ks.SOURCESYSTEM
    --AND c.SOURCESYSTEMID=3
    AND ARRAYS_OVERLAP(ARRAY_CONSTRUCT(c.SOURCESYSTEMID),ks.SOURCESYSTEMID) =TRUE
    AND TABLE_CATALOG=s.ODSDATABASENAME
    GROUP BY c.SOURCESYSTEMID,s.SOURCESYSTEMNAME,c.STAGEDATABASENAME,c.STAGETABLENAME) b
    on a.STAGETABLENAME =b.STAGETABLENAME
    AND a.SOURCESYSTEMID = b.SOURCESYSTEMID
    AND a.SOURCESYSTEMNAME= b.SOURCESYSTEMNAME
	)
SELECT SOURCESYSTEMID,SOURCESYSTEMNAME,DBMS,SOURCEHOSTNAME,SOURCEPORTNUMBER,SOURCEUSERID,SOURCEPASSWORD,SOURCEDATABASENAME,
SOURCETIMEZONE,SOURCEJDBCDRIVER,SOURCECONNECTIONSTRING,SOURCECURRENTTIMESTAMP,STAGEDATABASENAME,ODSDATABASENAME,SOURCESYSTEM_ACTIVEFLAG,
SOURCESCHEMANAME,SOURCETABLENAME,SOURCECATALOGQUERY,STAGESCHEMANAME,STAGETABLENAME,ODSSCHEMANAME,ODSTABLENAME,STAGETYPE,LOADTYPE,LOADPROCESS_ACTIVEFLAG,
LOADPROCESS_NRTFLAG,WATERMARKCOLUMNNAME,WATERMARKDATATYPE,WATERMARKVALUE,ODS_PK,BACKUPSCHEMANAME,COLUMNLISTEXP,
ISRESTRICTED,RESTRICTEDTABLENAME,RESTRICTEDCOLUMNNAME,SOURCE_SQL,EXPRESSIONS,RESTRICTEDTABLE_RANK,ORPHANDELETE_EXPRESSIONS,ISORPHANDELETE
 FROM (SELECT 
ss.sourcesystemid,
ss.sourcesystemname,
ss.dbms,
ss.sourcehostname,
ss.sourceportnumber,
ss.sourceuserid,
ss.sourcepassword,
ss.sourcedatabasename,
ss.sourcetimezone,
--ss.sourcecatalogquery,
CASE 
	--WHEN dbms='SQL SERVER' THEN 'Microsoft SQL Server'
	WHEN ss.dbms='SQL SERVER'	THEN 'SQL Server (Microsoft Driver)'
	WHEN ss.dbms='MYSQL' 		THEN 'MySQL'
	WHEN ss.dbms='ORACLE' 		THEN 'Oracle'
END AS SOURCEJDBCDRIVER,
CASE 
	WHEN ss.dbms='SQL SERVER' 	THEN 'jdbc:sqlserver://'||ss.sourcehostname||'\\'||ss.sourcedatabasename||':'||ss.sourceportnumber
	WHEN ss.dbms='MYSQL' 		THEN 'jdbc:mysql://'||ss.sourcehostname||':'||ss.sourceportnumber||'/'||ss.sourcedatabasename
	WHEN ss.dbms='ORACLE' 		THEN 'jdbc:oracle:thin:@'||ss.sourcehostname||':'||ss.sourceportnumber||':'||ss.sourcedatabasename
END AS SOURCECONNECTIONSTRING,
CASE 
	WHEN ss.dbms='SQL SERVER' THEN 'select convert(varchar, current_timestamp,120) TS;'
	WHEN ss.dbms='MYSQL' THEN 'select date_format(CURRENT_TIMESTAMP, ''%Y-%m-%d %H:%i:%s'') TS;'
	WHEN ss.dbms='ORACLE' THEN 'select to_char(current_timestamp,''YYYY-MM-DD HH24:MI:SS'') TS FROM dual;'
END AS SOURCEcurrenttimestamp,
ss.stagedatabasename,
ss.odsdatabasename,
ss.activeflag AS sourcesystem_activeflag,
lp.sourceschemaname,
lp.sourcetablename,
CASE 
	WHEN dbms='SQL SERVER' THEN 'select s.name as TABLE_SCHEMA, o.name as TABLE_NAME from sys.all_objects o inner join sys.schemas s on o.schema_id=s.schema_id where s.name = '''||lp.sourceschemaname||''' and o.type in (''U'');'
	WHEN dbms='MYSQL' THEN 'select o.TABLE_SCHEMA, o.TABLE_NAME from information_schema.TABLES o where o.table_schema='''||lp.sourceschemaname||''';'
	WHEN dbms='ORACLE' THEN 'select o.owner as TABLE_SCHEMA, o.OBJECT_NAME as TABLE_NAME from sys.all_objects o WHERE o.object_type = ''TABLE'' AND o.owner='''||lp.sourceschemaname||''';'
END AS SOURCECATALOGQUERY,
lp.stageschemaname,
lp.stagetablename,
lp.odsschemaname,
lp.odstablename,
lp.stagetype,
lp.loadtype,
lp.activeflag AS loadprocess_activeflag,
lp.nrtflag AS loadprocess_nrtflag,
lp.watermarkcolumnname,
lp.watermarkdatatype,
--lp.watermarklastvalue,
CASE 
	WHEN upper(ss.dbms)='ORACLE' AND upper(lp.stagetype) = 'INCREMENTAL' AND upper(lp.WATERMARKDATATYPE) ='TIMESTAMP' THEN 'TO_TIMESTAMP('||lp.WATERMARKLASTVALUE||', \'YYYY-MM-DD HH24:MI:SS\')' 
	ELSE lp.WATERMARKLASTVALUE 
END AS watermarkvalue,
lp.ods_pk,
ss.backupschemaname,
pcl.ColumnListExp,
lp.IsRestricted,
lp.RestrictedTablename,
lp.RestrictedColumnName,
lp.SOURCE_SQL,
lp.Expressions,
lp.RestrictedTable_Rank,
lp.OrphanDelete_Expressions,
lp.IsOrphanDelete
FROM dw.control.sourcesystem ss
LEFT OUTER JOIN control.loadprocess lp ON ss.sourcesystemid=lp.sourcesystemid
LEFT OUTER JOIN  PSEUDONYMISEDCOLUMNLISTEXP pcl
ON ss.sourcesystemid=pcl.sourcesystemid
AND ss.STAGEDATABASENAME=pcl.STAGEDATABASENAME
AND lp.STAGETABLENAME=pcl.STAGETABLENAME
      ) t	
GROUP BY SOURCESYSTEMID,SOURCESYSTEMNAME,DBMS,SOURCEHOSTNAME,SOURCEPORTNUMBER,SOURCEUSERID,SOURCEPASSWORD,SOURCEDATABASENAME,
SOURCETIMEZONE,SOURCEJDBCDRIVER,SOURCECONNECTIONSTRING,SOURCECURRENTTIMESTAMP,STAGEDATABASENAME,ODSDATABASENAME,SOURCESYSTEM_ACTIVEFLAG,
SOURCESCHEMANAME,SOURCETABLENAME,SOURCECATALOGQUERY,STAGESCHEMANAME,STAGETABLENAME,ODSSCHEMANAME,ODSTABLENAME,STAGETYPE,LOADTYPE,LOADPROCESS_ACTIVEFLAG,
LOADPROCESS_NRTFLAG,WATERMARKCOLUMNNAME,WATERMARKDATATYPE,WATERMARKVALUE,ODS_PK,BACKUPSCHEMANAME,COLUMNLISTEXP,
ISRESTRICTED,RESTRICTEDTABLENAME,RESTRICTEDCOLUMNNAME,SOURCE_SQL,EXPRESSIONS,RESTRICTEDTABLE_RANK,ORPHANDELETE_EXPRESSIONS,ISORPHANDELETE
;


