CREATE ROLE "TEAM_EU_ENTERPRISEINTEGRATION" WITH COMMENT = 'EU ENTERPRISE INTEGRATION TEAM';

CREATE ROLE "TEAM_EU_IP_DATAENGINEERING" WITH COMMENT = 'EU INTELLIGENT PRODUCTS DATA ENGINEERING TEAM';

CREATE ROLE "TEAM_EU_SIS_DATAENGINEERING" WITH COMMENT = 'EU SIS DATA ENGINEERING TEAM';

CREATE ROLE "TEAM_EU_SIS_DATASCIENCE" WITH COMMENT = 'EU SIS DATA SCIENCE TEAM';

CREATE ROLE "USECASE_DATAGOVERNANCE" WITH COMMENT = 'DATA GOVERNANCE TEAM';

CREATE ROLE "USECASE_EU_MYSECURITAS" WITH COMMENT = 'EU MYSECURITAS USE CASE'; 

CREATE ROLE "USECASE_EU_RISKPREDICTION" WITH COMMENT = 'EU RISK PREDICTION USE CASE'; 

CREATE ROLE "DECRYPT_ODS_GRS_NO" WITH COMMENT = 'Decrypt privilege for ODS_GRS_NO.'; 

CREATE ROLE "DECRYPT_ODS_KONTROLSYS_NO" WITH COMMENT = 'Decrypt privilege for ODS_KONTROLSYS_NO.'; 

CREATE ROLE "MASKING_ADMIN" WITH COMMENT = 'Masked Columns'; 

----------------------GRANTS

GRANT ROLE "TEAM_EU_ENTERPRISEINTEGRATION" TO ROLE "SYSADMIN";
GRANT ROLE "TEAM_EU_IP_DATAENGINEERING" TO ROLE "SYSADMIN";
GRANT ROLE "TEAM_EU_SIS_DATAENGINEERING" TO ROLE "SYSADMIN";
GRANT ROLE "TEAM_EU_SIS_DATASCIENCE" TO ROLE "SYSADMIN";
GRANT ROLE "USECASE_EU_RISKPREDICTION" TO ROLE "SYSADMIN";
GRANT ROLE "USECASE_EU_MYSECURITAS" TO ROLE "SYSADMIN";
GRANT ROLE "USECASE_EU_MYSECURITAS" TO ROLE "TEAM_EU_ENTERPRISEINTEGRATION";
GRANT ROLE "USECASE_EU_MYSECURITAS" TO ROLE "TEAM_EU_IP_DATAENGINEERING";

GRANT ROLE "USECASE_EU_RISKPREDICTION" TO ROLE "SYSADMIN";
GRANT ROLE "USECASE_EU_RISKPREDICTION" TO ROLE "TEAM_EU_SIS_DATAENGINEERING";
GRANT ROLE "USECASE_EU_RISKPREDICTION" TO ROLE "TEAM_EU_SIS_DATASCIENCE";

GRANT ROLE "DECRYPT_ODS_GRS_NO" TO ROLE "USECASE_EU_RISKPREDICTION";
GRANT ROLE "DECRYPT_ODS_GRS_NO" TO ROLE "USECASE_EU_MYSECURITAS";

GRANT ROLE "DECRYPT_ODS_KONTROLSYS_NO" TO ROLE "SYSADMIN";
GRANT ROLE "MASKING_ADMIN" TO ROLE "SYSADMIN";