--USE SECURITYADMIN
--GRANT ROLE 
--GRANT SELECT ON VIEWS to ROLE
--GRANT ROLE TO USERS 

USE ROLE SECURITYADMIN;
REVOKE IMPORTED  PRIVILEGES ON DATABASE  SNOWFLAKE_SAMPLE_DATA FROM ROLE PUBLIC;
GRANT USAGE ON DATABASE DW TO ROLE SISEU_DATAREADER;
GRANT USAGE ON SCHEMA DW.SIS TO ROLE SISEU_DATAREADER; --Confirm again USAGE ON SCHEMA exists or not if not run again

GRANT ALL ON DATABASE DATASCIENCE TO ROLE SISEU_DATASCIENCE;
GRANT ALL ON SCHEMA DATASCIENCE.DBO TO ROLE SISEU_DATASCIENCE;

------------
GRANT USAGE ON DATABASE DW TO ROLE SISEU_MYSECURITAS;
GRANT USAGE ON SCHEMA DW.SIS TO ROLE SISEU_MYSECURITAS; 

---------

GRANT USAGE ON DATABASE DATAMART TO ROLE USECASE_EU_MYSECURITAS;
GRANT USAGE ON SCHEMA "DATAMART"."MYSECURITAS" TO ROLE USECASE_EU_MYSECURITAS;

------------

GRANT SELECT ON ALL VIEWS IN SCHEMA  "DATAMART"."MYSECURITAS" TO ROLE USECASE_EU_MYSECURITAS;
----Granting all Objects under DW.SIS
--GRANT SELECT ON ALL VIEWS IN SCHEMA DW.SIS TO ROLE SISEU_DATAREADER;

GRANT SELECT ON ALL VIEWS IN SCHEMA  DW.SIS to Role SISEU_MYSECURITAS;
------------------------------------------------------------------------

--GRANT ROLE TO VIEWS SISEU_DATAREADER


GRANT SELECT ON VIEW DW.SIS.GRSNO_GCS_EXPORT_ERP_CALL_OUTS to Role SISEU_DATAREADER;
-----
GRANT SELECT ON VIEW DW.SIS.GRSNO_GCS_EXPORT_ERP_CALL_OUT_GUARDS to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_ALARM to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_ALARM_CODES to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_ALARM_GROUP to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_ASSIGNMENT_TYPE to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_CONTRACT_PART to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_CONTR_PART_VER to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_CONTRACT_TYPE to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_CUST_CUST_OBJECT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_GD to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_LOCATION_OBJECT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_PRODUCTION_OBJECT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_PROFITCENTER to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_REPORT_MARK to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_GRS_ADDONINFO to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_COMMIT_LOC_OBJECT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_COMMITMENT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_CONTRACT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_CUSTOMER_OBJECT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_CUSTOMER to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.GRSNO_LOCATION_MARK to Role SISEU_DATAREADER;
--------
GRANT SELECT ON VIEW DW.SIS.GRSNO_PROD_CUST_OBJECT to Role SISEU_DATAREADER;
-------
GRANT SELECT ON VIEW DW.SIS.GRSNO_SFU_COMMITMENTPERFORMED to Role SISEU_DATAREADER;
-------
GRANT SELECT ON VIEW DW.SIS.GRSNO_SFU_COMMITMENTPERFORMEDEXTRAVISITS to Role SISEU_DATAREADER;

-------

GRANT SELECT ON VIEW DW.SIS.GRSNO_REPORT_MARK_CULTURE to Role SISEU_DATAREADER;
GRANT SELECT ON VIEW DW.SIS.GRSNO_LOC_MARK_REPORT to Role SISEU_DATAREADER;
GRANT SELECT ON VIEW DW.SIS.GRSNO_PROCESSED_TRANSACTIONS to Role SISEU_DATAREADER;
GRANT SELECT ON VIEW DW.SIS.GRSNO_TEMP_TRANSACTIONS to Role SISEU_DATAREADER;
GRANT SELECT ON VIEW DW.SIS.GRSNO_USERS to Role SISEU_DATAREADER;

--------

GRANT SELECT ON VIEW DW.SIS.GRSNO_XPROCESSED_BARCODES to Role SISEU_DATAREADER;
GRANT SELECT ON VIEW DW.SIS.GRSNO_xTEMP_TRANSACTIONS to Role SISEU_DATAREADER;
GRANT SELECT ON VIEW DW.SIS.GRSNO_XREPORT_MARK to Role SISEU_DATAREADER;
GRANT SELECT ON VIEW DW.SIS.GRSNO_xPROCESSED_TRANSACTIONS to Role SISEU_DATAREADER;

--------

-----GRANT ROLE TO USERS----

--------SISEU_DATAREADER

GRANT ROLE SISEU_DATAREADER TO USER "SISEU_DS";
GRANT ROLE SISEU_DATAREADER TO USER "kriti.paliwal";
GRANT ROLE SISEU_DATAREADER TO USER "zachary.peterson";
GRANT ROLE SISEU_DATAREADER TO USER "shuainan.zhao";
GRANT ROLE SISEU_DATAREADER TO USER "anlai.gao";
GRANT ROLE SISEU_DATAREADER TO USER "sebastian.nyberg";
GRANT ROLE SISEU_DATAREADER TO USER "johannes.skog";
GRANT ROLE SISEU_DATAREADER TO USER "malin.lundqvist";
GRANT ROLE SISEU_DATAREADER TO USER "henrik.gronholtjensen";
GRANT ROLE SISEU_DATAREADER TO USER "jonas.alstrom.mortin";
GRANT ROLE SISEU_DATAREADER TO USER "daniel.sandberg";
GRANT ROLE SISEU_DATAREADER TO USER "carl.frolund";
GRANT ROLE SISEU_DATAREADER TO USER "Alex.bespalko";
GRANT ROLE SISEU_DATAREADER TO USER "jussi.kempinen";
GRANT ROLE SISEU_DATAREADER TO USER "andreas.timglas";

-------SISEU_DATASCIENCE

GRANT ROLE SISEU_DATASCIENCE TO USER "SISEU_DS";
GRANT ROLE SISEU_DATASCIENCE TO USER "kriti.paliwal";
GRANT ROLE SISEU_DATASCIENCE TO USER "zachary.peterson";
GRANT ROLE SISEU_DATASCIENCE TO USER "shuainan.zhao";
GRANT ROLE SISEU_DATASCIENCE TO USER "anlai.gao";
GRANT ROLE SISEU_DATASCIENCE TO USER "sebastian.nyberg";
GRANT ROLE SISEU_DATASCIENCE TO USER "johannes.skog";
GRANT ROLE SISEU_DATASCIENCE TO USER "malin.lundqvist";
GRANT ROLE SISEU_DATASCIENCE TO USER "henrik.gronholtjensen";
GRANT ROLE SISEU_DATASCIENCE TO USER "jonas.alstrom.mortin";
GRANT ROLE SISEU_DATASCIENCE TO USER "daniel.sandberg";
GRANT ROLE SISEU_DATASCIENCE TO USER "carl.frolund";
GRANT ROLE SISEU_DATASCIENCE TO USER "daniel.sandberg";

---------SISEU_MYSECURITAS

GRANT ROLE SISEU_MYSECURITAS TO USER "xiaohu.chen";
GRANT ROLE SISEU_MYSECURITAS TO USER "pawel.grudzien";

