CREATE OR REPLACE VIEW DATABASE ODS_KONTROLSYS_NO;
DROP SCHEMA ODS_KONTROLSYS_NO.PUBLIC;
CREATE OR REPLACE VIEW SCHEMA ODS_KONTROLSYS_NO.DBO;

USE SCHEMA ODS_KONTROLSYS_NO.DBO; 

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TICKETINCIDENTTYPE_CUSTOMER AS
SELECT ID, CUSTOMERID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP 
	FROM ODS_KONTROLSYS_NO.DBO.TICKETINCIDENTTYPE_CUSTOMER;

-------

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TICKETINCIDENTTYPE_BASE AS
SELECT ID,
	DESCRIPTION,
	SORTINDEX,
	ISACTIVE,
	REGISTERISTICKETPAID,
	REGISTERFEETYPE,
	REGISTERCOMMENT,
	REGISTERAGE,
	REGISTERCONTROLNO,
	REGISTERISUNDERAGE,
	REGISTERISDRUGADDICT,
	MODE,
	ABBREVIATION,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.TICKETINCIDENTTYPE_BASE;
	
------------

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TICKETINCIDENTTYPECONTRACT AS
SELECT	TICKECTINCIDENTTYPEBASEID,
	TICKETINCIDENTCONTRACTID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.TICKETINCIDENTTYPECONTRACT;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TICKETINSPECTION_PASSENGERFERRY AS
SELECT	ID,
	VESSELNAME,
	TRIPREFERENCENO,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.TICKETINSPECTION_PASSENGERFERRY;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CONTROLSERVICEREPORT AS 
SELECT CONTROLID, REGISTRATIONTIME, REGISTEREDBYID, 
	LASTCHANGEDBYID, LASTCHANGEDTIME,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(LOCATION,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
	ELSE TO_VARCHAR(LOCATION)
	END AS LOCATION,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(INSPECTORLIST,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
	ELSE TO_VARCHAR(INSPECTORLIST)
	END AS INSPECTORLIST,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(EXPLANATION,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
	ELSE TO_VARCHAR(EXPLANATION)
	END AS EXPLANATION,
	ISREGISTRATIONINPROGRESS, ISDELETED,
	ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.CONTROLSERVICEREPORT,
	DW.CONTROL.KEY_STORE KS
WHERE ARRAYS_OVERLAP(ARRAY_CONSTRUCT(ODS_SRC_SYSTEM_ID),SOURCESYSTEMID) =TRUE;

------------

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALTASK_OBJECT AS
SELECT ID, OBJECTID,
	ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_KONTROLSYS_NO.DBO.JOURNALTASK_OBJECT;

---------

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALADDITIONALSUBTYPE_OBJECT AS
SELECT ID, JOURNALADDITIONALTYPECUSTOMERID,	OBJECTID,
	ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALADDITIONALSUBTYPE_OBJECT;
	
-------

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMER(
	ID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(NAME,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(NAME)
	END AS NAME, 
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(ADDRESS,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ADDRESS)
	END AS ADDRESS,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(CONTACTPERSONNAME,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CONTACTPERSONNAME)
	END AS CONTACTPERSONNAME,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(CONTACTPERSONID,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CONTACTPERSONID)
	END AS CONTACTPERSONID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(CONTACTPERSONPHONE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CONTACTPERSONPHONE)
	END AS CONTACTPERSONPHONE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(CONTACTPERSONEMAIL,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CONTACTPERSONEMAIL)
	END AS CONTACTPERSONEMAIL,
	SECUDEPT,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(CUSTOMEROWNER,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CUSTOMEROWNER)
	END AS CUSTOMEROWNER,
	MFCJOURNALID,
	MFCCONTROLID,
	ISDELETED,
	CUSTOMERJOURNALINSTRUCTIONID,
	CUSTOMERCATEGORYID,
	FOLLOWUPACTIVATED,
	NEXTFOLLOWUP,
	FOLLOWUPINTERVAL,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(FOLLOWUPCOPIESTO,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(FOLLOWUPCOPIESTO)
	END AS FOLLOWUPCOPIESTO,
	DATARETENTIONAGREEMENTID,
	CUSTOMERWORKSCHEDULEACTIVATED,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(CONTRACTNAME,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CONTRACTNAME)
	END AS CONTRACTNAME,	
	ENABLEJOURNALTASKS,
	ENABLECONTROLZONES,
	JOURNALNUMBEROFPEOPLEACTIVATED,
	SHOWCONTROLFINALIZED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMER,
	DW.CONTROL.KEY_STORE KS
	WHERE  ARRAYS_OVERLAP(ARRAY_CONSTRUCT(ODS_SRC_SYSTEM_ID),SOURCESYSTEMID) =TRUE;
	
---------

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALANMELDELSETOOL AS
SELECT JOURNALID,
	TOOLID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALANMELDELSETOOL;

----------

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALTASK AS
SELECT ID,
	JOURNALADDITIONALTYPE_BASEID,
	TIME,
	HEADING,
	STRING,
	ISAPPROVED,
	VERSION,
	ISDELETED,
	ORIGINALJOURNALTASKID,
	NEXTSCHEDULEDTIME,
	PERFORMWINDOWHOURS,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	ODS_KONTROLSYS_NO.DBO.JOURNALTASK
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALTASK;

------------

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALADDITIONALTYPE_CUSTOMER_EXCLUDEFOROBJECT(
	JOURNALADDITIONALTYPE_CUSTOMERID,
	OBJECTID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALADDITIONALTYPE_CUSTOMER_EXCLUDEFOROBJECT;
	
--------------

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_DBO.TICKETINSPECTION_FERRY AS
SELECT ID,
	CARCOUNT,
	ISPAXBEFORECARS,
	CASE 
	WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(PAXFIRSTCOMMENT,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(PAXFIRSTCOMMENT)
	END AS PAXFIRSTCOMMENT,
	VESSELNAME,
	TRIPREFERENCENO,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
FROM ODS_KONTROLSYS_NO.DBO.TICKETINSPECTION_FERRY,
	DW.CONTROL.KEY_STORE KS
WHERE ARRAYS_OVERLAP(ARRAY_CONSTRUCT(ODS_SRC_SYSTEM_ID),SOURCESYSTEMID) =TRUE;
	
CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_ROUTE
SELECT ID,
	ZONEID,
	ROUTENO,
	DESCRIPTION,
	ISDELETED,
	CONTROLPERCENTAGE,
	REPORTINGCATEGORY,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
FROM ODS_KONTROLSYS_NO.DBO.ROUTE;
	
CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_DBO.CONTRACTS AS
SELECT ID,
	CUSTOMERID,
	CONTRACTNO,
	STARTDATE,
	ENDDATE,
	TERMINATED,
	TERMINATIONCODE,
	TERMINATIONINFO,
	CASE
	WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(CUSTOMERSIGNEE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CUSTOMERSIGNEE)
	END AS CUSTOMERSIGNEE,
	WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) THEN TO_VARCHAR(DECRYPT(SECURITASSIGNEE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(SECURITASSIGNEE)
	END AS SECURITASSIGNEE,
	REMARKS,
	TERMS,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.CONTRACTS,
	DW.CONTROL.KEY_STORE KS
WHERE ARRAYS_OVERLAP(ARRAY_CONSTRUCT(ODS_SRC_SYSTEM_ID),SOURCESYSTEMID) =TRUE;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CONTRACTELEMENT AS
SELECT ID,
	CONTRACTID,
	CONTROLTYPEID,
	CUSTOMERINSTRUCTIONID,
	NAME,
	NUMBEROFCONTROLS,
	CONTROLSPEROBJECT,
	PORTEFOLIO,
	CONTROLPRICE NUMERIC,
	PRICEPERMONTH ,
	ISDELETED,
	CREATEDBYID,
	LASTEDITEDBYID,
	CANADDOBJECTS,
	ISCONTROLREMARKSMANDATORY,
	HIDEEXACTTIMEFORCUSTOMER,
	SHOWSENDCOPYTOFIELD,
	ISNOTIFICATIONMANDATORY,
	ISSIGNATUREREQUIRED,
	ISINTERNAL,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.CONTRACTELEMENT; 

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALCHECKLIST_ADDITIONALTYPE AS
SELECT ID,
	JOURNALADDITIONALTYPE_BASEID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALCHECKLIST_ADDITIONALTYPE; 

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALADDITIONALTYPE_OBJECT AS
SELECT ID,
	OBJECTID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALADDITIONALTYPE_OBJECT;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_USER AS
SELECT ID,
	USERNAME,
	SECUIDNO BINARY,
	DEPARTMENTNO VARCHAR(10),
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP
	FROM ODS_KONTROLSYS_NO.DBO.USER;
	
CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_SERVICEREPORT AS
SELECT	ID,
	REGISTEREDBYID,
	REGISTRATIONTIME,
	LASTCHANGEDBYID,
	LASTCHANGEDTIME,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(LOCATION,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(LOCATION)
	END AS LOCATION,
	INCIDENTTYPEID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(INSPECTORLIST,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(INSPECTORLIST)
	END AS INSPECTORLIST,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(EXPLANATION,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(EXPLANATION)
	END AS EXPLANATION,
	ISREGISTRATIONINPROGRESS,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.SERVICEREPORT;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMFIELDGROUP AS
SELECT	ID,
	NAME,
	CONTRACTELEMENTID,
	POSITION,
	ISDYNAMIC,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMFIELDGROUP;
	
CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALADDITIONALTYPE_CUSTOMER AS
SELECT	ID,
	CUSTOMERID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALADDITIONALTYPE_CUSTOMER;
	
CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALANMELDELSEPRODUCT AS
SELECT	ID,
	JOURNALID,
	PRODUCTTYPEID,
	COUNT,
	VALUE,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALANMELDELSEPRODUCT;
	
CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMCONTROLTYPEFIELDANSWER AS
SELECT	ID,
	CUSTOMCONTROLTYPEFIELDID,
	CONTROLID,
	ANSWER BINARY ,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMCONTROLTYPEFIELDANSWER;
	
CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALANMELDELSEPERSON AS
SELECT	ID,
	JOURNALID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ISKNOWN,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ISKNOWN)
	END AS ISKNOWN,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ISMALE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ISMALE)
	END AS ISMALE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(AGE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(AGE)
	END AS AGE,
	NATIONALITYID,
	RESIDENCEID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALANMELDELSEPERSON;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_KASSECONTROL AS
SELECT	ID,
	ISMALE,
	NAME BINARY,
	AGE,
	HEIGHT,
	HAIRCOLOR,
	BODYBUILD,
	DISTINCTFEATURES,
	ADDITIONALSECUIDS,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.KASSECONTROL;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALADDITIONALTYPE_BASE AS
SELECT	ID,
	NAME,
	ISDELETED,
	FORCENOTIFICATION,
	ISREPORTTYPE,
	BOXCOLOR,
	TEXTCOLOR,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALADDITIONALTYPE_BASE;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_KASSECONTROLPURCHASE AS
SELECT	ID,
	KASSECONTROLID,
	PURCHASETYPE,
	TIME,
	EXACTAMOUNT,
	REQUESTEDSCAN,
	CORRECTAMOUNTREGISTERED,
	MONEYPUTINCASHREGISTER,
	RECEIPTGIVEN,
	RECEIPTNO,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.KASSECONTROLPURCHASE;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_KASSECONTROLPURCHASEPRODUCT AS
SELECT	ID,
	KASSECONTROLPURCHASEID,
	PRODUCTDESC,
	PRICE ,
	RETURNED,
	RETURNDATE,
	RETURNREGISTEREDBY,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.KASSECONTROLPURCHASEPRODUCT;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_OBJECT AS
SELECT	ID,
	CUSTOMERID,
	SECUDEPARTMENTID,
	OBJECTNO,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(NAME,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(NAME)
	END AS NAME,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ADDRESS,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ADDRESS)
	END AS ADDRESS,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(LATITUDE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(LATITUDE)
	END AS LATITUDE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(LONGITUDE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(LONGITUDE)
	END AS LONGITUDE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(PHONE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(PHONE)
	END AS PHONE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(CUSTOMERNO,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CUSTOMERNO)
	END AS CUSTOMERNO,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ORGANIZATIONNO,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ORGANIZATIONNO)
	END AS ORGANIZATIONNO,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(CUSTOMERNOINVOICE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CUSTOMERNOINVOICE)
	END AS CUSTOMERNOINVOICE,
	LOCATIONNO,
	CONTACTPERSONID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(CONTACTPERSONNAME,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CONTACTPERSONNAME)
	END AS CONTACTPERSONNAME,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(CONTACTPERSONPHONE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CONTACTPERSONPHONE)
	END AS CONTACTPERSONPHONE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(CONTACTPERSONEMAIL,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CONTACTPERSONEMAIL)
	END AS CONTACTPERSONEMAIL,
	OBJECTJOURNALINSTRUCTIONID,
	MFCJOURNALID,
	MFCCONTROLID,
	ISDELETED,
	FOLLOWUPACTIVATED,
	NEXTFOLLOWUP,
	FOLLOWUPINTERVAL,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(FOLLOWUPCOPIESTO,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(FOLLOWUPCOPIESTO)
	END AS FOLLOWUPCOPIESTO,
	CAPACITY,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ABBREVIATION,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ABBREVIATION)
	END AS ABBREVIATION,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.OBJECT;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CONTROLFILE AS
SELECT	ID,
	CONTROLID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CONTROLFILE;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_UTPASSERINGCONTROL AS
SELECT	ID,
	NOTCONTROLLED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.UTPASSERINGCONTROL;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_EMPLOYEE AS
SELECT	ID,
	OBJECTID,
	ISEMPLOYED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.EMPLOYEE;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_MISSEDJOURNALTASK AS
SELECT	ID,
	JOURNALTASKID,
	DATETIME,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.MISSEDJOURNALTASK;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALANMELDELSE AS
SELECT	ID,
	TIME,
	WASPLANNED,
	TOTALVALUE,
	STOPPEDBYID,
	POLICEWAITTIMEINMINUTES,
	ORGANIZEDID,
	POLICEID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALANMELDELSE;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALCOLLECTIONCONTROL AS
SELECT	ID,
	CUSTOMERID,
	OBJECTID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALCOLLECTIONCONTROL;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_PERSON AS
SELECT	ID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(FIRSTNAME,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(FIRSTNAME)
	END AS FIRSTNAME,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(LASTNAME,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(LASTNAME)
	END AS LASTNAME,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(EMAIL,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(EMAIL)
	END AS EMAIL,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(PHONE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(PHONE)
	END AS PHONE,
	ISDELETED,
	FULLNAME,
	PHONEPREFIXID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.PERSON;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALADDITIONALSUBTYPE_GENERAL AS
SELECT	ID,
	JOURNALADDITIONALTYPEBASEID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALADDITIONALSUBTYPE_GENERAL;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALADDITIONALSUBTYPE_BASE AS
SELECT	ID,
	NAME,
	POSITION,
	ISDELETED,
	BOXCOLOR,
	TEXTCOLOR,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALADDITIONALSUBTYPE_BASE;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_STATION AS
SELECT	ID,
	ROUTEID,
	NAME,
	SORTINDEX,
	ISDELETED,
	STATIONNO,
	GRUNNKRETSNO,
	GRUNNKRETS,
	BOROUGHNO,
	BOROUGH,
	MUNICIPALITYNO,
	MUNICIPALITY,
	REGION,
	FAREZONE,
	CONTROLZONE,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.STATION;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMFIELD AS
SELECT	ID,
	NAME,
	TYPE,
	CUSTOMFIELDGROUPID,
	POSITION,
	OPTIONS,
	BOOLEANMANDATORYCOMMENTFORTRUE,
	BOOLEANMANDATORYCOMMENTFORFALSE,
	ISMANDATORY,
	POINTSRANGESTART,
	POINTSRANGEEND,
	ISDELETED,
	ISLARGETEXTFIELD,
	RANDOMLYCHOSENCOUNT,
	ANSWERUITYPE,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMFIELD;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CONTRACTELEMENTOBJECT AS
SELECT	ID,
	CONTRACTELEMENTID,
	OBJECTID,
	OBJECTINSTRUCTIONID,
	CONTROLSSOLD,
	HOURSSOLD,
	CONTROLSPAIDBYOBJECT,
	NUMBEROFCONTROLSOVERRIDE,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CONTRACTELEMENTOBJECT;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALCOMMENT AS
SELECT	ID,
	JOURNALID,
	USERID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(TEXT,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(TEXT)
	END AS TEXT,
	TIME,
	ISINTERNAL,
	ISAUTOGENERATEDOREMPTY,
	REGISTEREDWITHSHOWFORALL,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALCOMMENT;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALFILE AS
SELECT	ID,
	JOURNALID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALFILE;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_UTPASSERINGCONTROLPERSON AS
SELECT	ID,
	UTPASSERINGCONTROLID,
	EMPLOYEEID,
	REGISTREREDDATE,
	CONTROLLEDDATE,
	ISOK,
	PERSONALDECLARATION,
	PERSONELLPURCHASE,
	RECEIPTNUMBER,
	PURCHASEDATE,
	PURCHASEEMPLOYEEID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(COMMENT,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(COMMENT)
	END AS COMMENT,
	ISDELETED,
	PRODUCTDESCRIPTION,
	BARCODE,
	PRIS,
	PRODUCTCONDITION,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(EMPLOYEEEXPLANATION,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(EMPLOYEEEXPLANATION)
	END AS EMPLOYEEEXPLANATION,
	IDENTIFICATIONSHOWNTYPE,
	HASSIGNATURE,
	SIGNATUREFILEGUID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.UTPASSERINGCONTROLPERSON;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMFIELDALTERNATIVE AS
SELECT	ID,
	CUSTOMFIELDID,
	STRING,
	POINTS,
	ISINCIDENT,
	MANDATORYCOMMENT,
	POSITION,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMFIELDALTERNATIVE;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TICKETINCIDENT_BASE AS
SELECT	ID,
	COUNT,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(AGE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(AGE)
	END AS AGE,
	FEETYPE,
	ISFEEPAID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ISUNDERISUNDERAGEDD,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ISUNDERISUNDERAGEDD)
	END AS ISUNDERISUNDERAGEDD,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(COMMENT,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(COMMENT)
	END AS COMMENT,
	ISDELETED,
	CONTROLNUMBER,
	ISDRUGADDICT,
	TICKETINSPECTIONBASEID,
	TICKETINCIDENTTYPEID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.TICKETINCIDENT_BASE;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_BASEFILE AS
SELECT	ID,
	FILEDATAID,
	SIZE,
	FILENAME,
	CONTENTTYPE,
	DATEUPLOADED,
	UPLOADEDBYID,ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.BASEFILE;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_FILEDATA AS
SELECT	ID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(DATA,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(DATA)
	END AS DATA,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.FILEDATA;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TICKETINSPECTIONUSER AS
SELECT	TICKETINSPECTIONID,
	USERID,
	SORTINDEX,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.TICKETINSPECTIONUSER;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CONTROLCOMMENT AS
SELECT	ID,
	CONTROLID,
	USERID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(TEXT,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(TEXT)
	END AS TEXT,
	TIME,
	ISINTERNAL,
	ISAUTOGENERATEDOREMPTY,
	REGISTEREDWITHSHOWFORALL,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CONTROLCOMMENT;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALCHECKLIST_JOURNAL AS
SELECT	ID,
	JOURNALID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALCHECKLIST_JOURNAL;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALCHECKLIST_BASE AS
SELECT	ID,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALCHECKLIST_BASE;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TICKETINSPECTION_BUS AS
SELECT	ID,
	BUSNO,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(DRIVERNO,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(DRIVERNO)
	END AS DRIVERNO,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.TICKETINSPECTION_BUS;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TICKETINSPECTION_BASE AS
SELECT	ID,
	TICKETINSPECTIONCONTRACTID,
	TIME,
	INSPECTORCOUNT,
	PASSENGERCOUNT,
	CONTROLLEDCOUNT,
	ROUTEID,
	STARTSTATIONID,
	ENDSTATIONID,
	DELAYINMINUTES,
	UNIFORMRATING,
	CLEANNESSRATING,
	SERVICERATING,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(COMMENT,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(COMMENT)
	END AS COMMENT,
	ISREGISTRATIONINPROGRESS,
	ISDELETED,
	DIRECTION,
	VEHICLETYPE,
	REGISTRATIONCOMPLEDEDTIME,
	PERFORMEDBYID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ADDITIONALOFFICERIDS,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ADDITIONALOFFICERIDS)
	END AS ADDITIONALOFFICERIDS,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(TEAMNUMBER,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(TEAMNUMBER)
	END AS TEAMNUMBER,
	CONTROLLERUNIFORMTYPE,
	TEAMSIZE,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.TICKETINSPECTION_BASE;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALCOLLECTIONCONTROLJOURNAL AS
SELECT	ID,
	JOURNALCOLLECTIONCONTROLID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALCOLLECTIONCONTROLJOURNAL;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_KVALITETCONTROL AS
SELECT	ID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.KVALITETCONTROL;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CONTROL AS
SELECT	ID,
	CONTRACTELEMENTOBJECTID,
	PERFORMEDBYID,
	CUSTOMERINSTRUCTIONID,
	OBJECTINSTRUCTIONID,
	STARTTIME,
	ENDTIME,
	INSTRUCTIONFOLLOWED,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(REMARKS,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(REMARKS)
	END AS REMARKS,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(INTERNALSECUREMARKS,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(INTERNALSECUREMARKS)
	END AS INTERNALSECUREMARKS,
	LASTEDITEDBYID,
	LASTCHANGEDTIME,
	ISREGISTRATIONINPROGRESS,
	TARGETEDCONTROL,
	PRICE ,
	PAIDBYOBJECT,
	REGISTRATIONSTARTEDTIME,
	REGISTRATIONCOMPLETEDTIME,
	ISFINALIZED,
	ISREADYFORINVOICING,
	CUSTOMERNOTIFIED,
	HASINCIDENT,
	ISDELETED,
	BARCODE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(COPYTOEMAILADDRESSES,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(COPYTOEMAILADDRESSES)
	END AS COPYTOEMAILADDRESSES,
	HASSIGNATURE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(SIGNATURENAME,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(SIGNATURENAME)
	END AS SIGNATURENAME,
	SIGNATUREFILEGUID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(LATITUDE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(LATITUDE)
	END AS LATITUDE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(LONGITUDE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(LONGITUDE)
	END AS LONGITUDE,
	IDENTIFICATIONSHOWNTYPE,
	PROCESSED,
	CONTRACTCATEGORY1TEXT,
	CONTRACTCATEGORY2TEXT,
	CONTRACTCATEGORY3TEXT,
	FINALIZEDDATE,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CONTROL;




CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALCHECKLISTITEM AS
SELECT	ID,
	JOURNALCHECKLIST_BASEID,
	TYPE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(TEXT,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(TEXT)
	END AS TEXT,
	ANSWER,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(COMMENT,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(COMMENT)
	END AS COMMENT,
	SORTPOSITION,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALCHECKLISTITEM;




CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNAL AS
SELECT	ID,
	OBJECTID,
	PERFORMEDBYID,
	OBJECTJOURNALINSTRUCTIONID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(LONGITUDE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(LONGITUDE)
	END AS LONGITUDE,	
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(LATITUDE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(LATITUDE)
	END AS LATITUDE,
	STARTTIME,
	ENDTIME,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(REMARKS,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(REMARKS)
	END AS REMARKS,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(INTERNALSECUREMARKS,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(INTERNALSECUREMARKS)
	END AS INTERNALSECUREMARKS,
	LASTEDITEDBYID,
	LASTCHANGEDTIME,
	ISREGISTRATIONINPROGRESS,
	REGISTRATIONSTARTEDTIME,
	REGISTRATIONCOMPLETEDTIME,
	INCIDENTMESSAGETYPE,
	INCIDENTTYPEID,
	SUBTYPE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ACTIONTAKEN,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ACTIONTAKEN)
	END AS ACTIONTAKEN,
	FORCEUSED,
	POLICECALLED,
	HANDCUFFSUSED,
	CUSTOMERNOTIFIED,
	ISDELETED,
	NOTIFICATIONSSENT,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(SECUID,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(SECUID)
	END AS SECUID,
	ISALARM,
	CUSTOMERJOURNALINSTRUCTIONID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ADDITIONALOFFICERIDS,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ADDITIONALOFFICERIDS)
	END AS ADDITIONALOFFICERIDS,
	NUMBEROFPEOPLE,
	JOURNALTASKID,
	PROCESSED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNAL;




CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMFIELDVALUE AS
SELECT	ID,
	CUSTOMFIELDID,
	CUSTOMFIELDTEXT,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(VALUE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(VALUE)
	END AS VALUE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(COMMENT,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(COMMENT)
	END AS COMMENT,
	DYNAMICINDEX,
	ISDELETED,
	POINTS,
	ISINCIDENT,
	MAXPOINTS,
	MANDATORYCHOSENVALUES,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMFIELDVALUE;



CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMFIELDVALUECONTROL AS
SELECT	CUSTOMFIELDVALUEID,
	CONTROLID,ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMFIELDVALUECONTROL;

CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMERCATEGORY AS
SELECT	ID,
	NAME,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(FOLLOWUPEMAILSTO,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(FOLLOWUPEMAILSTO)
	END AS FOLLOWUPEMAILSTO,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMERCATEGORY;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CONTRACTCATEGORY1 AS
SELECT	ID,
	NAME,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CONTRACTCATEGORY1;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CONTRACTCATEGORY2 AS
SELECT	ID,
	NAME,
	CONTRACTCATEGORY1ID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CONTRACTCATEGORY2;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CONTRACTELEMENT AS
SELECT	ID,
	CONTRACTID,
	CONTROLTYPEID,
	CUSTOMERINSTRUCTIONID,
	NAME,
	NUMBEROFCONTROLS,
	CONTROLSPEROBJECT,
	PORTEFOLIO,
	CONTROLPRICE ,
	PRICEPERMONTH ,
	ISDELETED,
	CREATEDBYID,
	LASTEDITEDBYID,
	CANADDOBJECTS,
	ISCONTROLREMARKSMANDATORY,
	HIDEEXACTTIMEFORCUSTOMER,
	SHOWSENDCOPYTOFIELD,
	ISNOTIFICATIONMANDATORY,
	ISSIGNATUREREQUIRED,
	ISINTERNAL,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CONTRACTELEMENT;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CONTRACTELEMENTCONTRACTCATEGORY1 AS
SELECT	ID,
	CONTRACTELEMENTID,
	CONTRACTCATEGORY1ID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CONTRACTELEMENTCONTRACTCATEGORY1;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMCONTROLTYPE AS
SELECT	ID,
	DESCRIPTION,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMCONTROLTYPE;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMCONTROLTYPECUSTOMER AS
SELECT	CUSTOMCONTROLTYPEID,
	CUSTOMERID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMCONTROLTYPECUSTOMER;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMCONTROLTYPEFIELD AS
SELECT  ID,
	CUSTOMCONTROLTYPEID,
	QUESTION,
	TYPE,
	ISMANDATORY,
	ALTERNATIVES,
	ISMAINREPORTFIELD,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMCONTROLTYPEFIELD;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_CUSTOMERCONTRACTCATEGORY1 AS
SELECT	ID,
	CUSTOMERID,
	CONTRACTCATEGORY1ID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.CUSTOMERCONTRACTCATEGORY1;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALTASK_CUSTOMER AS
SELECT	ID,
	CUSTOMERID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALTASK_CUSTOMER;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_JOURNALTASKFILE AS
SELECT	ID,
	JOURNALTASKID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.JOURNALTASKFILE;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_OBJECTFILE AS
SELECT	ID,
	OBJECTID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.OBJECTFILE;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_PHONEPREFIX AS
SELECT	ID,
	COUNTRY,
	PHONEPREFIX VARCHAR(6),
	ISDEFAULT,
	PHONEVALIDATIONREGEX,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.PHONEPREFIX;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_PRODUCTTYPE AS
SELECT	ID,
	DESCRIPTION,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.PRODUCTTYPE;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_SECUDEPARTMENT AS
SELECT	ID,
	SECUREGIONID,
	NAME,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.SECUDEPARTMENT;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_SECUREGION AS
SELECT	ID,
	NAME,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.SECUREGION;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_SIVILTVAKTHOLDCONTROL AS
SELECT	CONTROLID,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.SIVILTVAKTHOLDCONTROL;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_SIVILTVAKTHOLDCONTROLINCIDENT AS
SELECT	ID,
	SIVILTVAKTHOLDCONTROLID,
	INCIDENTTIME,
	INCIDENTTYPEID,
	INCIDENTSUBTYPEID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(DESCRIPTION,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(DESCRIPTION)
	END AS DESCRIPTION,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ACTIONTAKEN,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ACTIONTAKEN)
	END AS ACTIONTAKEN,
	FORCEUSED,
	HANDCUFFSUSED,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.SIVILTVAKTHOLDCONTROLINCIDENT;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TARGETEDCONTRACTELEMENT AS
SELECT	ID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(TARGETDESCRIPTION,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(TARGETDESCRIPTION)
	END AS TARGETDESCRIPTION,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.TARGETEDCONTRACTELEMENT;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TICKETINSPECTIONCONTRACT AS
SELECT	ID,
	CUSTOMERID,
	CONTRACTNO,
	NAME,
	TICKETINSPECTIONTYPEID,
	STARTDATE,
	ENDDATE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(CUSTOMERSIGNEE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(CUSTOMERSIGNEE)
	END AS CUSTOMERSIGNEE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(SECURITASSIGNEE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(SECURITASSIGNEE)
	END AS SECURITASSIGNEE,
	REMARKS,
	TERMS,
	CREATEDBYID,
	LASTEDITEDBYID,
	ISDELETED,
	SHOWUNIFORM,
	SHOWCLEANNESS,
	SHOWSERVICE,
	SHOWDIRECTION,
	SHOWVEHICLETYPE,
	SHOWTEAMNUMBER,
	SHOWCONTROLLERUNIFORMTYPE,
	SHOWTEAMSIZE,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.TICKETINSPECTIONCONTRACT;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_TICKETINSPECTIONCONTRACTZONE AS
SELECT	ID,
	TICKETINSPECTIONCONTRACTID,
	ZONEID,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.TICKETINSPECTIONCONTRACTZONE;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_UTREDNINGCONTROL AS
SELECT	ID,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(EMPLOYMENTSTART,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(EMPLOYMENTSTART)
	END AS EMPLOYMENTSTART,
	THEFTSTART,
	GOODS,
	GOODSDESC,
	NUMERIC,
	OTHER,
	CONCEDEDAMOUNT,
	METHOD,
	NUMBEROFCONTROLS,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(EMPLOYMENTEND,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(EMPLOYMENTEND)
	END AS EMPLOYMENTEND,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(AFTERCARE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(AFTERCARE)
	END AS AFTERCARE,
	AFTERCAREDATE,
	AFTERCARECOMMENT,
	HOURS,
	FEE NUMERIC,
	RECORDING,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(RECORDINGCOMMENT,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(RECORDINGCOMMENT)
	END AS RECORDINGCOMMENT,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(ISMALE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(ISMALE)
	END AS ISMALE,
	CASE WHEN ARRAYS_OVERLAP(ARRAY_CONSTRUCT(CURRENT_ROLE()),VALID_ROLES) 
	THEN TO_VARCHAR(DECRYPT(AGE,KS.PASSPHARSE,KS.KEY_VALUE,KS.ADVANCED_ENCRYPTION_STD),'UTF-8') 
    ELSE TO_VARCHAR(AGE)
	END AS AGE,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.UTREDNINGCONTROL;


CREATE OR REPLACE VIEW DW.SIS.KONTROLSYS_NO_ZONE AS
SELECT	ID,
	CUSTOMERID,
	NAME,
	ISDELETED,
	ODS_SRC_SYSTEM_ID,
	ODS_CREATEDBY,
	ODS_MODIFIEDBY,
	ODS_MODIFIEDBY_TIMESTAMP,
	ODS_CREATEDBY_TIMESTAMP,
	FROM ODS_KONTROLSYS_NO.DBO.ZONE;