-- IN PRODUCTION ENVIRONMENT ---

--PROD_DATAMART
---------------------------------------------------------------START  PROD SCRIPT------------------------
USE ROLE ACCOUNTADMIN;
--CREATE OR REPLACE SHARE PROD_DATAMART; -- SET COMMENT ='PRODUCTION DATAMART SHARE'

CREATE OR REPLACE SHARE PROD_DATAMART_MYSECURITAS;
CREATE OR REPLACE SHARE PROD_DATAMART_RISKPREDICTION;

GRANT USAGE ON DATABASE DATAMART TO SHARE PROD_DATAMART_MYSECURITAS;
GRANT USAGE ON DATABASE DATAMART TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT USAGE ON SCHEMA DATAMART.MYSECURITAS TO SHARE PROD_DATAMART_MYSECURITAS;
GRANT USAGE ON SCHEMA DATAMART.RISKPREDICTION TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT REFERENCE_USAGE ON DATABASE ODS_KONTROLSYS_NO TO SHARE PROD_DATAMART_MYSECURITAS;
GRANT REFERENCE_USAGE ON DATABASE DW TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT REFERENCE_USAGE ON DATABASE ODS_KONTROLSYS_NO TO SHARE PROD_DATAMART_RISKPREDICTION;
GRANT REFERENCE_USAGE ON DATABASE DW TO SHARE PROD_DATAMART_RISKPREDICTION;

--GRANT SELECT ON VIEW "DATAMART"."MYSECURITAS"."GRSNO_ALARM" TO SHARE PROD_DATAMART;

--- GRANT GRS NO MYSECURITAS MYSECURITAS ----
GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_GCS_EXPORT_ERP_CALL_OUTS TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_GCS_EXPORT_ERP_CALL_OUT_GUARDS TO SHARE PROD_DATAMART_MYSECURITAS;


GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_ALARM TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_ALARM_CODES TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_ALARM_GROUP TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_ASSIGNMENT_TYPE TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_CONTRACT_PART TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_CONTR_PART_VER TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_CONTRACT_TYPE TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_CUST_CUST_OBJECT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_GD TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_LOCATION_OBJECT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_PRODUCTION_OBJECT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_PROFITCENTER TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_REPORT_MARK TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_GRS_ADDONINFO TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_COMMIT_LOC_OBJECT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_COMMITMENT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_CONTRACT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_CUSTOMER_OBJECT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_CUSTOMER TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_LOCATION_MARK TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_PROD_CUST_OBJECT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_SFU_COMMITMENTPERFORMED TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_SFU_COMMITMENTPERFORMEDEXTRAVISITS TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_REPORT_MARK_CULTURE TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_PROCESSED_TRANSACTIONS TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_TEMP_TRANSACTIONS TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_USERS TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_XPROCESSED_BARCODES TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_XTEMP_TRANSACTIONS TO SHARE PROD_DATAMART_MYSECURITAS;

--GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_XREPORT_MARK TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_XPROCESSED_TRANSACTIONS TO SHARE PROD_DATAMART_MYSECURITAS;

--GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_XTEMP_TRANSACTIONS_ATTACHMENT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_LOC_MARK_TYPE TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_TEMP_TRANSACTIONS_ATTACHMENT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_TEMP_TRANSACTIONS_ATTACHMENT_CULTURE TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_LOC_MARK_REPORT TO SHARE PROD_DATAMART_MYSECURITAS;

GRANT SELECT ON VIEW DATAMART.MYSECURITAS.GRSNO_XTEMP_TRANSACTIONS_ATTACHMENT TO SHARE PROD_DATAMART_MYSECURITAS;

--GRANT SELECT ON ALL VIEWS  IN SCHEMA DATAMART.MYSECURITAS  TO SHARE PROD_DATAMART; -- BULK VIEW SHARE IS RESTRICTED.

--END GRS NO MYSECURITAS ----

--- GRANT KONTROLSYSNO MYSECURITAS MYSECURITAS ----
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_BASEFILE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTRACT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTRACTCATEGORY1 TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTRACTCATEGORY2 TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTRACTELEMENT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTRACTELEMENTCONTRACTCATEGORY1 TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTRACTELEMENTOBJECT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTROL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTROLCOMMENT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTROLFILE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTROLSERVICEREPORT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CONTROLTYPE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMCONTROLTYPE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMCONTROLTYPECUSTOMER TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMCONTROLTYPEFIELD TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMCONTROLTYPEFIELDANSWER TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMER TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMERCATEGORY TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMERCONTRACTCATEGORY1 TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMFIELD TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMFIELDALTERNATIVE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMFIELDGROUP TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMFIELDVALUE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_CUSTOMFIELDVALUECONTROL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_EMPLOYEE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNAL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALADDITIONALSUBTYPE_BASE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALADDITIONALSUBTYPE_GENERAL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALADDITIONALSUBTYPE_OBJECT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALADDITIONALTYPE_BASE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALADDITIONALTYPE_CUSTOMER TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALADDITIONALTYPE_CUSTOMER_EXCLUDEFOROBJECT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALADDITIONALTYPE_OBJECT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALANMELDELSE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALANMELDELSEPERSON TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALANMELDELSEPRODUCT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALANMELDELSETOOL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALCHECKLISTITEM TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALCHECKLIST_ADDITIONALTYPE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALCHECKLIST_BASE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALCHECKLIST_JOURNAL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALCOLLECTIONCONTROL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALCOLLECTIONCONTROLJOURNAL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALCOMMENT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALFILE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALTASK TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALTASKFILE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALTASK_CUSTOMER TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_JOURNALTASK_OBJECT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_KASSECONTROL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_KASSECONTROLPURCHASE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_KASSECONTROLPURCHASEPRODUCT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_KVALITETCONTROL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_MISSEDJOURNALTASK TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_OBJECT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_OBJECTFILE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_PERSON TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_PHONEPREFIX TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_PRODUCTTYPE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_ROUTE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_SECUDEPARTMENT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_SECUREGION TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_SERVICEREPORT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_SIVILTVAKTHOLDCONTROL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_SIVILTVAKTHOLDCONTROLINCIDENT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_STATION TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TARGETEDCONTRACTELEMENT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINCIDENTTYPECONTRACT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINCIDENTTYPE_BASE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINCIDENTTYPE_CUSTOMER TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINCIDENT_BASE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINSPECTIONCONTRACT TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINSPECTIONCONTRACTZONE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINSPECTIONUSER TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINSPECTION_BASE TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINSPECTION_BUS TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINSPECTION_FERRY TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_TICKETINSPECTION_PASSENGERFERRY TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_USER TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_UTPASSERINGCONTROL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_UTPASSERINGCONTROLPERSON TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_UTREDNINGCONTROL TO SHARE PROD_DATAMART_MYSECURITAS;		
GRANT	SELECT	ON	VIEW	DATAMART.MYSECURITAS.KONTROLSYSNO_ZONE TO SHARE PROD_DATAMART_MYSECURITAS;		

--END KONTROLSYSNO MYSECURITAS ----



----- GRANT GRS NO RISKPREDICTION VIEWS-----

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORT_ERP_CALL_OUTS TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORT_ERP_CALL_OUT_GUARDS TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_CODES TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_GROUP TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_ASSIGNMENT_TYPE TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_CONTRACT_PART TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_CONTR_PART_VER TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_CONTRACT_TYPE TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_CUST_CUST_OBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_GD TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_LOCATION_OBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_PRODUCTION_OBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_PROFITCENTER TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_GRS_ADDONINFO TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_COMMIT_LOC_OBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_COMMITMENT TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_CONTRACT TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_CUSTOMER_OBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_CUSTOMER TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_LOCATION_MARK TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_PROD_CUST_OBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_SFU_COMMITMENTPERFORMED TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_SFU_COMMITMENTPERFORMEDEXTRAVISITS TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_CULTURE TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_PROCESSED_TRANSACTIONS TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_TEMP_TRANSACTIONS TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_USERS TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_XPROCESSED_BARCODES TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_XTEMP_TRANSACTIONS TO SHARE PROD_DATAMART_RISKPREDICTION;

--GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_XREPORT_MARK TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_XPROCESSED_TRANSACTIONS TO SHARE PROD_DATAMART_RISKPREDICTION;

--GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_XTEMP_TRANSACTIONS_ATTACHMENT TO SHARE PROD_DATAMART_RISKPREDICTION;

GRANT SELECT ON VIEW DATAMART.RISKPREDICTION.GRSNO_LOC_MARK_REPORT TO SHARE PROD_DATAMART_RISKPREDICTION;

--------END GRS NO RISKPREDICTION ---

--- GRANT KONTROLSYSNO MYSECURITAS RISKPREDICTION ----
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_BASEFILE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTRACT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTRACTCATEGORY1 TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTRACTCATEGORY2 TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTRACTELEMENT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTRACTELEMENTCONTRACTCATEGORY1 TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTRACTELEMENTOBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTROL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTROLCOMMENT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTROLFILE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTROLSERVICEREPORT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CONTROLTYPE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMCONTROLTYPE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMCONTROLTYPECUSTOMER TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMCONTROLTYPEFIELD TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMCONTROLTYPEFIELDANSWER TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMER TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMERCATEGORY TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMERCONTRACTCATEGORY1 TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMFIELD TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMFIELDALTERNATIVE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMFIELDGROUP TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMFIELDVALUE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_CUSTOMFIELDVALUECONTROL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_EMPLOYEE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNAL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALADDITIONALSUBTYPE_BASE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALADDITIONALSUBTYPE_GENERAL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALADDITIONALSUBTYPE_OBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALADDITIONALTYPE_BASE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALADDITIONALTYPE_CUSTOMER TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALADDITIONALTYPE_CUSTOMER_EXCLUDEFOROBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALADDITIONALTYPE_OBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALANMELDELSE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALANMELDELSEPERSON TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALANMELDELSEPRODUCT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALANMELDELSETOOL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALCHECKLISTITEM TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALCHECKLIST_ADDITIONALTYPE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALCHECKLIST_BASE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALCHECKLIST_JOURNAL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALCOLLECTIONCONTROL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALCOLLECTIONCONTROLJOURNAL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALCOMMENT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALFILE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALTASK TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALTASKFILE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALTASK_CUSTOMER TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_JOURNALTASK_OBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_KASSECONTROL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_KASSECONTROLPURCHASE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_KASSECONTROLPURCHASEPRODUCT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_KVALITETCONTROL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_MISSEDJOURNALTASK TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_OBJECT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_OBJECTFILE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_PERSON TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_PHONEPREFIX TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_PRODUCTTYPE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_ROUTE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_SECUDEPARTMENT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_SECUREGION TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_SERVICEREPORT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_SIVILTVAKTHOLDCONTROL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_SIVILTVAKTHOLDCONTROLINCIDENT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_STATION TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TARGETEDCONTRACTELEMENT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINCIDENTTYPECONTRACT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINCIDENTTYPE_BASE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINCIDENTTYPE_CUSTOMER TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINCIDENT_BASE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINSPECTIONCONTRACT TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINSPECTIONCONTRACTZONE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINSPECTIONUSER TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINSPECTION_BASE TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINSPECTION_BUS TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINSPECTION_FERRY TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_TICKETINSPECTION_PASSENGERFERRY TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_USER TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_UTPASSERINGCONTROL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_UTPASSERINGCONTROLPERSON TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_UTREDNINGCONTROL TO SHARE PROD_DATAMART_RISKPREDICTION;		
GRANT	SELECT	ON	VIEW	DATAMART.RISKPREDICTION.KONTROLSYSNO_ZONE TO SHARE PROD_DATAMART_RISKPREDICTION;

--END KONTROLSYSNO RISKPREDICTION --

ALTER SHARE PROD_DATAMART_MYSECURITAS ADD ACCOUNTS = SECURITASTEST;
ALTER SHARE PROD_DATAMART_RISKPREDICTION ADD ACCOUNTS = SECURITASTEST;
---------------------------------------------------------------END PROD SCRIPT------------------------

--PRD_DATAMART
---------------------------------------------------------------START  QA SCRIPT------------------------
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE  DATABASE PRD_DATAMART_MYSECURITAS FROM SHARE SECURITAS.PROD_DATAMART_MYSECURITAS;
CREATE OR REPLACE  DATABASE PRD_DATAMART_RISKPREDICTION FROM SHARE SECURITAS.PROD_DATAMART_RISKPREDICTION;


USE ROLE SECURITYADMIN;
------- DATABASE ACCESS
GRANT IMPORTED PRIVILEGES ON DATABASE PRD_DATAMART_MYSECURITAS  TO ROLE TEAM_EU_ENTERPRISEINTEGRATION;
GRANT IMPORTED PRIVILEGES ON DATABASE PRD_DATAMART_MYSECURITAS  TO ROLE TEAM_EU_IP_DATAENGINEERING;
GRANT IMPORTED PRIVILEGES ON DATABASE PRD_DATAMART_RISKPREDICTION  TO ROLE TEAM_EU_SIS_DATAENGINEERING;
GRANT IMPORTED PRIVILEGES ON DATABASE PRD_DATAMART_RISKPREDICTION  TO ROLE TEAM_EU_SIS_DATASCIENCE;