CREATE OR REPLACE WAREHOUSE "WH_SIS_DATAENGINEERING" WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 10 SCALING_POLICY = 'STANDARD' COMMENT = 'SIS DATA ENGINEERING USE CASE WORKLOADS';

CREATE OR REPLACE WAREHOUSE "WH_ENTERPRISEINTEGRATION" WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 10 SCALING_POLICY = 'ECONOMY' COMMENT = 'ENTERPRISE INTEGRATION WORKLOADS';

CREATE OR REPLACE WAREHOUSE "WH_IP_DATAENGINEERING" WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 10 SCALING_POLICY = 'ECONOMY' COMMENT = 'IP DATA ENGINEERING USE CASE WORKLOADS';

CREATE OR REPLACE WAREHOUSE "WH_DATASCIENCE" WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 10 SCALING_POLICY = 'ECONOMY' COMMENT = 'DATA SCIENCE USE CASE WORKLOADS';

CREATE OR REPLACE WAREHOUSE "WH_DATA_LOAD" WITH WAREHOUSE_SIZE = 'SMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 10 SCALING_POLICY = 'STANDARD' COMMENT = 'ALL DATA LOADING (ELT) WORKLOADS';

CREATE OR REPLACE WAREHOUSE "WH_ADMIN" WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 10 SCALING_POLICY = 'ECONOMY' COMMENT = 'ALL ADMINISTRATIVE WORKLOADS (USERS, ROLES, GRANTS, TASKS, ETC)';


------------------ALTER WAREHOUSE


--ALTER WAREHOUSE "WH_SIS_DATAENGINEERING" SET WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE MIN_CLUSTER_COUNT = 1 MAX_CLUSTER_COUNT = 10 SCALING_POLICY = 'STANDARD' COMMENT = 'SIS DATA ENGINEERING USE CASE WORKLOADS';

