GET_DDL('DATABASE','STG_REFERENCE')

CREATE OR REPLACE DATABASE STG_REFERENCE;    

CREATE OR REPLACE SCHEMA STG_REFERENCE.BASE;    

CREATE OR REPLACE TABLE STG_REFERENCE.BASE.AZURE_IP (   APPLICATION VARIANT NOT NULL  );  

CREATE OR REPLACE TABLE STG_REFERENCE.BASE.NETWORK_POLICY (   IP_RANGE VARCHAR(2000),   CATEGORY VARCHAR(2000),   NOTES VARCHAR(2000),   DEV_ACTIVEFLAG BOOLEAN,   TEST_ACTIVEFLAG BOOLEAN,   PROD_ACTIVEFLAG BOOLEAN  );