CREATE OR REPLACE DATABASE DATAMART;
CREATE OR REPLACE SCHEMA DATAMART.RISKPREDICTION;
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_ALARM_CODES AS	
SELECT	
	ALARM_ID,ALARM_CODE_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_ALARM_CODES;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_ALARM_TYPE AS	
SELECT 	
 	ALARM_ID,ALARM_TYPE_ID,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_ALARM_TYPE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_CENTRAL AS	
SELECT 	
 	ALARM_CENTRAL_ID,ALARM_CENTRAL_NO,DESCRIPTION,TO_VARCHAR(PHONE_NO,'utf-8') AS PHONE_NO,SORT_ORDER,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ADMINISTRATING,DISTRIBUTING,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_CENTRAL;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_CODES_OBJECT AS	
SELECT 	
 	ALARM_CODE_ID,ALARM_CODE_OBJECT_ID,CUSTOMER_ID,CUST_OBJ_ID,PROD_OBJ_ID,LOC_OBJ_ID,COMMITMENT_ID,AP_COMMITMENT_ID,DAY_T_ID,VERSION_FROM,ASSIGNM_TIMEFROM,DATEFROM,DATETO,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_CODES_OBJECT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_ITEM AS	
SELECT 	
 	ALARM_ITEM_ID,ALARM_ID,PROD_OBJ_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_ITEM;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_PORTABLE AS	
SELECT 	
 	ALARM_PORTABLE_ID,ALARM_PORTABLE_NO,DESCRIPTION,PROFITCENTER_ID,ALARM_GROUP_ID,ROWID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,BARCODE,TO_VARCHAR(NOTES,'utf-8') AS NOTES,ALARM_CODE_NO,ALARM_CODE_SHORT_DESCRIPTION,ALARM_CODE_DESCRIPTION,ALARM_CODE_EXCLUDE_FROM_REPORT,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_PORTABLE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_PORTABLE_ITEM AS	
SELECT 	
 	ALARM_PORTABLE_ITEM_ID,ALARM_PORTABLE_ID,CONTRACT_ID,VALIDFROM,VALIDTO,ROWID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,VALIDTIMEFROM,VALIDTIMETO,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_PORTABLE_ITEM;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_PORTABLE_ITEM_LOC_MARK AS	
SELECT 	
 	ALARM_PORTABLE_ITEM_ID,LOCATION_MARK_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_PORTABLE_ITEM_LOC_MARK;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_TEST AS	
SELECT 	
 	ALARM_TEST_ID,ALARM_TEST_NO,ALARM_TEST_GROUP_ID,ALARM_TEST_TYPE_ID,ALARM_TEST_KEY_STORAGE_INCL,CUST_OBJ_ID,UNIT_PROD_OBJ_ID,UNIT_LOC_OBJ_ID,CENTRAL_UNIT_TYPE,ALARM_TEST_ADM_CENTRAL_ID,ALARM_TEST_DISTRIB_CENTRAL_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,TO_VARCHAR(NOTES,'utf-8') AS NOTES,ALARM_TEST_PORTABLE_ID,TURN_OUT_COUNT,DATEFROM,DATETO,ALARM_TEST_PORTABLE_ITEM_ID,APPERANCE_TIME,APPERANCE_TIME_EXCEPTION,APPERANCE_TIME_EXCEPTION_START,APPERANCE_TIME_EXCEPTION_STOP,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_TEST;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ALARM_TYPE AS	
SELECT 	
 	ALARM_TYPE_ID,ALARM_TYPE_NO,DESCRIPTION,SORT_ORDER,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_TYPE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ASSIGNMENT_PART AS	
SELECT 	
 	COMMITMENT_ID,DAY_T_ID,VERSION_FROM,ASSIGNM_TIMEFROM,ASSIGNM_TIMETO,ASS_TIME_CALC,ROAD_TIME_CALC,ASS_TIME_PLANNED,ROAD_TIME_PLANNED,HOUR_PRICE_CALC,VERSION_TO,CONTRACT_INCOME,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,EXECUTE_COUNT,EXECUTE_PERIOD,EXECUTE_GROUP,INCOME,TIME_BANK_HOURS,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ASSIGNMENT_PART;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ASSIGNMENT_PART_CALCULATION AS	
SELECT 	
 	COMMITMENT_ID,DAY_T_ID,AP_VERSION_FROM,ASSIGNM_TIMEFROM,VALIDFROM,VALIDTO,ASS_TIME_CALC,ROAD_TIME_CALC,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,INCOME,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ASSIGNMENT_PART_CALCULATION;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_ASSIGNMENT_PART_MODIFICATIONS AS	
SELECT 	
 	COMMITMENT_ID,DAY_T_ID,VERSION_FROM,ASSIGNM_TIMEFROM,EXECUTE_DATE,ADJUSTED_EXECUTE_TIME,LOGG_ID,TO_VARCHAR(NOTES,'utf-8') AS NOTES,ROWID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ASSIGNMENT_PART_MODIFICATIONS;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_COMMITMENT_CULTURE AS	
SELECT 	
 	COMMITMENT_ID,CULTURE_ID,DESCRIPTION,INSTRUCTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.COMMITMENT_CULTURE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_COMMITMENT_EXCEPT AS	
SELECT 	
 	COMMITMENT_ID,EXCEPTION,DAY_T_ID,DATEFROM,TIMEFROM,GD_ID,GD_DATEFROM,GD_TIMEFROM,GD_DAY_T_ID,TIMETO,ASS_TIME_CALC,ASS_TIME_PLANNED,ROAD_TIME_CALC,ROAD_TIME_PLANNED,HOUR_PRICE_CALC,CONTRACT_INCOME,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,TIMEFROM_REF,GD_DAY_T_OFFSET,EXECUTE_TIMEFROM,EXECUTE_TIMETO,EXECUTE_ORDER,EXECUTE_ROADTIME,GD_EXCEPT_GD_ID,GD_EXCEPT_EXCEPTION,GD_EXCEPT_DATEFROM,GD_EXCEPT_TIMEFROM,LAST_GD_ID,REF_VALUE,ADJUSTED_EXECUTE_TIME,LOGG_ID,TO_VARCHAR(NOTES,'utf-8') AS NOTES,INCOME,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.COMMITMENT_EXCEPT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_COMMITMENT_EXECUTE AS	
SELECT 	
 	COMMITMENT_ID,EXECUTETIME,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.COMMITMENT_EXECUTE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_COMMITMENT_GROUP AS	
SELECT 	
 	COMMITMENT_GROUP_ID,ROWID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.COMMITMENT_GROUP;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_COMMITMENT_GROUP_MEMBER AS	
SELECT 	
 	COMMITMENT_GROUP_ID,COMMITMENT_ID,VALIDFROM,VALIDTO,ROWID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.COMMITMENT_GROUP_MEMBER;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_COMMITMENT_LOC_MARK AS	
SELECT 	
 	COMMITMENT_ID,LOCATION_MARK_ID,DATEFROM,DATETO,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,REQUIRED,USER_ORDER_BY,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.COMMITMENT_LOC_MARK;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_COMMITMENT_NOTES AS	
SELECT 	
 	COMMITMENT_ID,TO_VARCHAR(NOTES,'utf-8') AS NOTES,ROWID,INSERT_DATE,TO_VARCHAR(INSERT_USER,'utf-8') AS INSERT_USER,CHANGE_DATE,TO_VARCHAR(CHANGE_USER,'utf-8') AS CHANGE_USER,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.COMMITMENT_NOTES;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_COMMITMENT_SCHEDULE AS	
SELECT 	
 	COMMITMENT_ID,DATEFROM,DAY_T_ID,ITERATION,TIMEFROM,TIMETO,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.COMMITMENT_SCHEDULE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_COMMITMENT_SCHEDULE_VERSION AS	
SELECT 	
 	COMMITMENT_ID,DATEFROM,DATETO,HOURS_PER_MONTH,ITERATION_COUNT,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.COMMITMENT_SCHEDULE_VERSION;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CONTACT_OBJECT AS	
SELECT 	
 	CONTACT_OBJECT_ID,PROD_OBJ_ID,LOC_OBJ_ID,CUST_OBJ_ID,CUSTOMER_ID,CONTACT_PERSON_ID,DEFAULT_OBJECT,CONTACT_ORDER,TO_VARCHAR(CONTACT_FOR_THIS_OBJECT,'utf-8') AS CONTACT_FOR_THIS_OBJECT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,DATEFROM,DATETO,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTACT_OBJECT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CONTACT_PERSON AS	
SELECT 	
 	CONTACT_PERSON_ID,TO_VARCHAR(LASTNAME,'utf-8') AS LASTNAME,TO_VARCHAR(FIRSTNAME,'utf-8') AS FIRSTNAME,TO_VARCHAR(SHORT_NOTES,'utf-8') AS SHORT_NOTES,TO_VARCHAR(ADDRESS_VALID,'utf-8') AS ADDRESS_VALID,TO_VARCHAR(NOTES,'utf-8') AS NOTES,TO_VARCHAR(ADDRESS,'utf-8') AS ADDRESS,TO_VARCHAR(POSTCODE,'utf-8') AS POSTCODE,TO_VARCHAR(POSTADDRESS,'utf-8') AS POSTADDRESS,TO_VARCHAR(CARE_OF,'utf-8') AS CARE_OF,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,TO_VARCHAR(POSTDELIVERY_ADDRESS_EXTRA,'utf-8') AS POSTDELIVERY_ADDRESS_EXTRA,TO_VARCHAR(TITLE,'utf-8') AS TITLE,ORDINAL_NO,TO_VARCHAR(GUARD_NOTES,'utf-8') AS GUARD_NOTES,DATETO,ACCOUNT_ID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTACT_PERSON;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CONTRACT_CONDITION AS	
SELECT 	
 	CONTRACT_CONDITION_ID,CONTRACT_CONDITION_NO,DESCRIPTION,ROWID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTRACT_CONDITION;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CONTRACT_CUSTOMER_CHANGE AS	
SELECT 	
 	CONTRACT_ID,CUSTOMER_CHANGE_DATE,CUSTOMER_ID,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTRACT_CUSTOMER_CHANGE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CONTRACT_INVOICED AS	
SELECT 	
 	PROFITCENTER_NO,CONTRACT_NO,CUSTOMER_NO,PERIOD,CONTRACT_TYPE_ID,PRODUCT_NO,CUSTOMER_CATEGORY_NO,AMOUNT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTRACT_INVOICED;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CONTRACT_INVOICED_A AS	
SELECT 	
 	PROFITCENTER_NO,CONTRACT_NO,CUSTOMER_NO,PERIOD,CONTRACT_TYPE_ID,PRODUCT_NO,CUSTOMER_CATEGORY_NO,AMOUNT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTRACT_INVOICED_A;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CONTRACT_INVOICED_B AS	
SELECT 	
 	PROFITCENTER_NO,CONTRACT_NO,CUSTOMER_NO,PERIOD,CONTRACT_TYPE_ID,PRODUCT_NO,CUSTOMER_CATEGORY_NO,AMOUNT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTRACT_INVOICED_B;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CUSTOMER_GROUP AS	
SELECT 	
 	CUSTOMER_GROUP_ID,CUSTOMER_GROUP_NO,TO_VARCHAR(NAME,'utf-8') AS NAME,TO_VARCHAR(ADDRESS,'utf-8') AS ADDRESS,TO_VARCHAR(POSTCODE,'utf-8') AS POSTCODE,TO_VARCHAR(POSTADDRESS,'utf-8') AS POSTADDRESS,TO_VARCHAR(REF_PERSON,'utf-8') AS REF_PERSON,TO_VARCHAR(TELEPHONE,'utf-8') AS TELEPHONE,TO_VARCHAR(TELEFAX,'utf-8') AS TELEFAX,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,TO_VARCHAR(POSTDELIVERY_ADDRESS_EXTRA,'utf-8') AS POSTDELIVERY_ADDRESS_EXTRA,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CUSTOMER_GROUP;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CUSTOMER_OBJECT_MAP_IMAGE AS	
SELECT 	
 	CUST_OBJ_ID,TO_VARCHAR(GEOLOCATION,'utf-8') AS GEOLOCATION,TO_VARCHAR(GEO_LAT,'utf-8') AS GEO_LAT,TO_VARCHAR(GEO_LONG,'utf-8') AS GEO_LONG,TO_VARCHAR(DATA,'utf-8') AS DATA,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CUSTOMER_OBJECT_MAP_IMAGE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CUSTOMER_TYPE AS	
SELECT 	
 	CUSTOMER_TYPE_ID,CUSTOMER_TYPE_NO,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CUSTOMER_TYPE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_CUST_GR_CUSTOMER AS	
SELECT 	
 	CUSTOMER_GROUP_ID,CUSTOMER_ID,DATEFROM,DATETO,INSERT_DATE,TO_VARCHAR(INSERT_USER,'utf-8') AS INSERT_USER,CHANGE_DATE,TO_VARCHAR(CHANGE_USER,'utf-8') AS CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CUST_GR_CUSTOMER;
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTALARM AS	
SELECT 	
 	GCS_EXPORTALARM_ID,GCS_EXPORTORDER_ID,CUSTOMEROBJECT_ID,ALARM_GROUP_NO,ALARM_NO,ALARM_KEY_STORAGE_INCL,CENTRAL_UNIT_TYPE,TO_VARCHAR(NOTES,'utf-8') AS NOTES,FACT_GROUP_NO,FACT_GROUP_DESCRIPTION,TO_VARCHAR(FACT_GROUP_NOTES,'utf-8') AS FACT_GROUP_NOTES,TURN_OUT_COUNT,APPEARANCE_TIME,APPEARANCE_TIME_EXCEPTION,APPEARANCE_TIME_EXCEPTION_START,APPEARANCE_TIME_EXCEPTION_STOP,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTALARM;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTALARMBUNCHOFKEYS AS	
SELECT 	
 	GCS_EXPORTALARMBUNCHOFKEYS_ID,GCS_EXPORTALARM_ID,BUNCHOFKEYS_ID,MARK,PURPOSE,HOOK,KEY_DEPOT,DEPOT_INFO,GD_BOX,TO_VARCHAR(ADDRESS,'utf-8') AS ADDRESS,TO_VARCHAR(POSTCODE,'utf-8') AS POSTCODE,TO_VARCHAR(POSTADDRESS,'utf-8') AS POSTADDRESS,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTALARMBUNCHOFKEYS;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTALARMCODES AS	
SELECT 	
 	GCS_EXPORTALARMCODES_ID,GCS_EXPORTALARM_ID,ALARMCODE_ID,ALARM_CODE_NO,SHORT_DESCRIPTION,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTALARMCODES;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTALARMINSTRUCTIONS AS	
SELECT 	
 	GCS_EXPORTALARMINSTRUCTIONS_ID,GCS_EXPORTALARM_ID,INSTRUCTION_ID,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTALARMINSTRUCTIONS;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTALARMKEYS AS	
SELECT 	
 	GCS_EXPORTALARMKEYS_ID,GCS_EXPORTALARMBUNCHOFKEYS_ID,KEY_ID,KEY_TYPE_NO,KEY_MAN_NO,MARK,BELONG_TO,CODE,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTALARMKEYS;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTCOP_ACTIONGROUP AS	
SELECT 	
 	GCS_EXPORTCOP_ACTIONGROUP_ID,GCS_EXPORTORDER_ID,COP_ACTIONGROUP_ID,DESCRIPTION,ACTIONGROUP_TYPE_ID,CCT_NO,TO_VARCHAR(NOTES,'utf-8') AS NOTES,INCLUDEINMAXCOUNT,INFORMATIONMANDATORY,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTCOP_ACTIONGROUP;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTCOP_ACTIONGROUP_ALARM AS	
SELECT 	
 	GCS_EXPORTCOP_ACTIONGROUP_ALARM_ID,GCS_EXPORTCOP_ACTIONGROUP_ID,ALARM_GROUP_NO,ALARM_NO,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTCOP_ACTIONGROUP_ALARM;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTCOP_ACTIONGROUP_CCT AS	
SELECT 	
 	GCS_EXPORTCOP_ACTIONGROUP_CCT_ID,GCS_EXPORTCOP_ACTIONGROUP_ID,CCT_NO,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTCOP_ACTIONGROUP_CCT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTCOP_ACTIONGROUP_CUSTOMER_OBJECT AS	
SELECT 	
 	GCS_EXPORTCOP_ACTIONGROUP_CUSTOMER_OBJECT_ID,GCS_EXPORTCOP_ACTIONGROUP_ID,CUSTOMEROBJECT_ID,CUST_OBJ_NO,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTCOP_ACTIONGROUP_CUSTOMER_OBJECT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTCOP_ACTIONGROUP_MU AS	
SELECT 	
 	GCS_EXPORTCOP_ACTIONGROUP_MU_ID,GCS_EXPORTCOP_ACTIONGROUP_ID,CCT_NO,MU_NO,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTCOP_ACTIONGROUP_MU;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTCOP_ACTIONGROUP_PERFORMINGMU AS	
SELECT 	
 	GCS_EXPORTCOP_ACTIONGROUP_PERFORMINGMU_ID,GCS_EXPORTCOP_ACTIONGROUP_ID,CCT_NO,MU_NO,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTCOP_ACTIONGROUP_PERFORMINGMU;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTCUSTOMEROBJECT AS	
SELECT 	
 	GCS_EXPORTCUSTOMEROBJECT_ID,GCS_EXPORTORDER_ID,CCT_NO,CUSTOMEROBJECT_ID,CUSTOMER_NO,ORGANIZATION_NO,INVOICECUSTOMER_NO,CUST_OBJ_NO,CUST_OBJ_NO_ALT,TO_VARCHAR(NAME,'utf-8') AS NAME,TO_VARCHAR(ADDRESS,'utf-8') AS ADDRESS,TO_VARCHAR(POSTDELIVERY_ADDRESS,'utf-8') AS POSTDELIVERY_ADDRESS,TO_VARCHAR(POSTCODE,'utf-8') AS POSTCODE,TO_VARCHAR(POSTADDRESS,'utf-8') AS POSTADDRESS,TO_VARCHAR(BLOCK,'utf-8') AS BLOCK,TO_VARCHAR(DISTRICT,'utf-8') AS DISTRICT,TO_VARCHAR(TELEPHONE,'utf-8') AS TELEPHONE,TO_VARCHAR(TELEFAX,'utf-8') AS TELEFAX,TO_VARCHAR(ADDRESS_2,'utf-8') AS ADDRESS_2,PROTECTED,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,SUBCONTRACTOR_CCT_NO,EXTRA_INFORMATION,PRODUCTS,TO_VARCHAR(CUSTOMER_NAME,'utf-8') AS CUSTOMER_NAME,IS_EXTERNAL,TO_VARCHAR(LONGITUDE,'utf-8') AS LONGITUDE,TO_VARCHAR(LATITUDE,'utf-8') AS LATITUDE,ALLOW_CAMERA,ASSIGNMENT_POSTCODE,ISBLACKLISTED,BLACKLISTCOMMENT,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTCUSTOMEROBJECT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTLOCATIONMARK AS	
SELECT 	
 	GCS_EXPORTLOCATIONMARK_ID,GCS_EXPORTORDER_ID,CUSTOMEROBJECT_ID,LOCATIONMARK_ID,BARCODE_NO,LOCMARKTYPE,TO_VARCHAR(MARKPOSITION,'utf-8') AS MARKPOSITION,MARKACTION,PROD_OBJ_NAME,LOC_OBJ_NAME,MARKPOSITIONDETAIL,RGB_COLOUR,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTLOCATIONMARK;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTORDER AS	
SELECT 	
 	GCS_EXPORTORDER_ID,GCS_EXPORTTYPE_ID,EXPORTSTATUS,ERRORCODE,PERIODSTART,PERIODSTOP,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTORDER;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTORDER_PARAMETERS AS	
SELECT 	
 	GCS_EXPORTORDER_ID,PARAMETER_RECORD,PARAMETER_1,PARAMETER_2,PARAMETER_3,PARAMETER_4,PARAMETER_5,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTORDER_PARAMETERS;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTPOSITION AS	
SELECT 	
 	GCS_EXPORTPOSITION_ID,GCS_EXPORTORDER_ID,CUSTOMEROBJECT_ID,CCT_NO,POSITION_NO,PROD_OBJ_NAME,TO_VARCHAR(ADDRESS,'utf-8') AS ADDRESS,TO_VARCHAR(ADDRESS_2,'utf-8') AS ADDRESS_2,TRANSPORT_DESCRIPTION,TRANSPORT_DETAIL,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTPOSITION;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GCS_EXPORTTYPE AS	
SELECT 	
 	GCS_EXPORTTYPE_ID,GCS_EXPORTTYPE_NO,DESCRIPTION,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_EXPORTTYPE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_DETAIL_TYPE AS	
SELECT 	
 	GD_DETAIL_TYPE_ID,DESCRIPTION,SORT_ORDER,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_DETAIL_TYPE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_EXCEPT AS	
SELECT 	
 	GD_ID,EXCEPTION,DATEFROM,TIMEFROM,PAUSE_START,PAUSE_LEN,TIMETO,ROAD_TIME_PERCENT,ROAD_TIME_MEAN,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,TIMEFROM_REF,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_EXCEPT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_EXCEPT_DETAIL AS	
SELECT 	
 	GD_ID,EXCEPTION,DATEFROM,TIMEFROM,GD_DETAIL_TYPE_ID,MINUTES,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_EXCEPT_DETAIL;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_EXTRA_INCOME AS	
SELECT 	
 	GD_ID,PERIOD,EXTRA_INCOME,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_EXTRA_INCOME;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_GROUP AS	
SELECT 	
 	GD_GROUP_ID,PROFITCENTER_ID,GD_GROUP_NO,DESCRIPTION,DATEFROM,DATETO,PG_COMPANY,PG_PROFC,PG_NO,TO_VARCHAR(PG_NAME,'utf-8') AS PG_NAME,TO_VARCHAR(NOTES,'utf-8') AS NOTES,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_GROUP;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_GROUP_ITEM AS	
SELECT 	
 	GD_GROUP_ID,GD_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_GROUP_ITEM;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_INVOICED AS	
SELECT 	
 	PROFITCENTER_NO,GD_NO,PERIOD,CONTRACT_TYPE_ID,PRODUCT_NO,CUSTOMER_CATEGORY_NO,AMOUNT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_INVOICED;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_INVOICED_A AS	
SELECT 	
 	PROFITCENTER_NO,GD_NO,PERIOD,CONTRACT_TYPE_ID,PRODUCT_NO,CUSTOMER_CATEGORY_NO,AMOUNT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_INVOICED_A;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_INVOICED_B AS	
SELECT 	
 	PROFITCENTER_NO,GD_NO,PERIOD,CONTRACT_TYPE_ID,PRODUCT_NO,CUSTOMER_CATEGORY_NO,AMOUNT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_INVOICED_B;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_MAP_IMAGE AS	
SELECT 	
 	GD_ID,TO_VARCHAR(GEOLOCATION,'utf-8') AS GEOLOCATION,TO_VARCHAR(GEO_LAT,'utf-8') AS GEO_LAT,TO_VARCHAR(GEO_LONG,'utf-8') AS GEO_LONG,TO_VARCHAR(DATA,'utf-8') AS DATA,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_MAP_IMAGE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_MARK AS	
SELECT 	
 	GD_MARK_ID,GD_ID,BARCODE,TO_VARCHAR(POSITION,'utf-8') AS POSITION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_MARK;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_NOTES AS	
SELECT 	
 	GD_ID,TO_VARCHAR(NOTES,'utf-8') AS NOTES,ROWID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_NOTES;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_NOTES_CULTURE AS	
SELECT 	
 	GD_ID,CULTURE_ID,TO_VARCHAR(NOTES,'utf-8') AS NOTES,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_NOTES_CULTURE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_PRECALCULATED_INCOME AS	
SELECT 	
 	GD_ID,PERIOD,INCOME_TYPE,INCOME,INVALID_INCOME,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,INCOME_CHANGE_DATE,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_PRECALCULATED_INCOME;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_SHIFT AS	
SELECT 	
 	GD_ID,GD_DATEFROM,DAY_T_ID,GD_TIMEFROM,GD_TIMETO,PAUSE_START,PAUSE_LEN,ROAD_TIME_PERCENT,ROAD_TIME_MEAN,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_SHIFT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_SHIFT_DETAIL AS	
SELECT 	
 	GD_ID,GD_DATEFROM,DAY_T_ID,GD_TIMEFROM,GD_DETAIL_TYPE_ID,MINUTES,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_SHIFT_DETAIL;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_SHIFT_DETAIL_PLANNED AS	
SELECT 	
 	GD_ID,GD_DATEFROM,GD_TIMEFROM,GD_DETAIL_TYPE_ID,DAY_T_ID,DATEFROM,DATETO,TIMEFROM,MINUTES,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_SHIFT_DETAIL_PLANNED;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_SHIFT_DETAIL_PLANNED_DATE AS	
SELECT 	
 	GD_ID,GD_DATEFROM,GD_DETAIL_TYPE_ID,DATEFROM,TIMEFROM,MINUTES,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_SHIFT_DETAIL_PLANNED_DATE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_TYPE AS	
SELECT 	
 	GD_TYPE_ID,GD_TYPE_NO,D0700,D0701,D0702,D0703,D0704,D0705,D0706,D0707,D0708,D0709,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,AUTO_ADJUST,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_TYPE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GD_VERSION AS	
SELECT 	
 	GD_ID,GD_DATEFROM,GD_DATETO,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GD_VERSION;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GRSR_CUSTOMER_REPORT_MARK_FOLDER AS	
SELECT 	
 	GRSR_CUSTOMER_REPORT_MARK_FOLDER_ID,CUSTOMER_ID,REPORT_MARK_FOLDER_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GRSR_CUSTOMER_REPORT_MARK_FOLDER;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GUARD_COMMENT AS	
SELECT 	
 	GUARD_COMMENT_ID,GD_ID,STARTDATE,COMMITMENT_ID,ASSIGNMENT_TYPE_ID,ASSIGNMENT_TYPE_NO,CUST_OBJ_ID,READER_NO,TO_VARCHAR(EMPLOYEE_NO,'utf-8') AS EMPLOYEE_NO,TO_VARCHAR(FIRSTNAME,'utf-8') AS FIRSTNAME,TO_VARCHAR(LASTNAME,'utf-8') AS LASTNAME,GUARD_COMMENT_TEXT_ID,NOTE_TYPE,TO_VARCHAR(NOTE,'utf-8') AS NOTE,INSERT_DATE,TO_VARCHAR(INSERT_USER,'utf-8') AS INSERT_USER,CHANGE_DATE,TO_VARCHAR(CHANGE_USER,'utf-8') AS CHANGE_USER,ROWID,BARCODE,RESPONSIBLECHECKDATETIME,COMMITMENT_DATE,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GUARD_COMMENT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GUARD_COMMENT_TEXT AS	
SELECT 	
 	GUARD_COMMENT_TEXT_ID,DESCRIPTION,COMMENT_TYPE,COMMENT_REQUIRED,SORT_ORDER,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GUARD_COMMENT_TEXT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GUARD_OBJECT AS	
SELECT 	
 	GUARD_OBJECT_ID,GUARD_OBJECT_TYPE_ID,GUARD_ORDER_ID,CUSTOMER_ID,CUST_OBJ_ID,PROD_OBJ_ID,LOC_OBJ_ID,COMMITMENT_ID,ASSIGNMENT_VERSION,GD_ID,GD_DATEFROM,EMPLOYEE_ID,LOCATION_MARK_ID,PACKET_ID,INSTRUCTION_ID,BUNCH_KEY_ID,ALARM_CODE_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GUARD_OBJECT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GUARD_ORDER AS	
SELECT 	
 	GUARD_ORDER_ID,GUARD_ORDER_TYPE_ID,VALIDFROM,VALIDTO,CUSTOMER_DATE,TO_VARCHAR(CUSTOMER_NAME,'utf-8') AS CUSTOMER_NAME,TO_VARCHAR(CUSTOMER_PHONE,'utf-8') AS CUSTOMER_PHONE,SEC_DATE,TO_VARCHAR(SEC_NAME,'utf-8') AS SEC_NAME,TO_VARCHAR(SEC_PHONE,'utf-8') AS SEC_PHONE,REG_DATE,TO_VARCHAR(REG_NAME,'utf-8') AS REG_NAME,TO_VARCHAR(REG_PHONE,'utf-8') AS REG_PHONE,CREATE_INSTRUCTION,CREATE_INSTRUCTION_FROM,GUARD_HEADLINE_TEXT,TO_VARCHAR(GUARD_TEXT,'utf-8') AS GUARD_TEXT,CENTRAL_REF_NO,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,REG_AFTERWARDS,REG_AFTERWARDS_TIME,CANCELLED,TIMEFROM,TIMETO,DISPLAYFROM,DISPLAYTO,SHOWCUSTOMERREF_ON_REPORT,CONFIRMATION_TEXT,PROFITCENTER_ID,CANCELLEDDATE,CANCELLEDREASON,EXTRAORDER_ID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GUARD_ORDER;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GUARD_ORDER_CULTURE AS	
SELECT 	
 	GUARD_ORDER_ID,CULTURE_ID,GUARD_TEXT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GUARD_ORDER_CULTURE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_GUARD_ORDER_ENDTEXT_CULTURE AS	
SELECT 	
 	GUARD_ORDER_ID,CULTURE_ID,ENDTEXT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GUARD_ORDER_ENDTEXT_CULTURE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_INVOICE_FEE AS	
SELECT 	
 	INVOICE_FEE_ID,INVOICE_FEE_NO,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.INVOICE_FEE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_INVOICE_TEXT AS	
SELECT 	
 	INVOICE_TEXT_ID,INVOICE_TEXT_NO,DESCRIPTION,INVOICE_TEXT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.INVOICE_TEXT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_INVOICE_TYPE AS	
SELECT 	
 	INVOICE_TYPE_ID,INVOICE_TYPE_NO,DESCRIPTION,ROWIDMASTER,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.INVOICE_TYPE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_LOCATION_MARK_CULTURE AS	
SELECT 	
 	LOCATION_MARK_ID,CULTURE_ID,POSITION,POSITION_GUARD_INFO,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOCATION_MARK_CULTURE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_LOC_MARK_INFO AS	
SELECT 	
 	LOCATION_MARK_ID,INFORMATION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,TO_VARCHAR(LOC_MARK_SERVICE_NOTES,'utf-8') AS LOC_MARK_SERVICE_NOTES,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOC_MARK_INFO;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_LOC_MARK_INFO_CULTURE AS	
SELECT 	
 	LOCATION_MARK_ID,CULTURE_ID,INFORMATION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOC_MARK_INFO_CULTURE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_LOC_MARK_SERVICE_EXT_INTERVAL AS	
SELECT 	
 	LOC_MARK_SERVICE_EXT_INTERVAL_ID,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOC_MARK_SERVICE_EXT_INTERVAL;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_LOC_MARK_SERVICE_INTERVAL AS	
SELECT 	
 	LOC_MARK_SERVICE_INTERVAL_ID,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOC_MARK_SERVICE_INTERVAL;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_LOC_MARK_SERVICE_TYPE AS	
SELECT 	
 	LOC_MARK_SERVICE_TYPE_ID,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOC_MARK_SERVICE_TYPE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_LOC_MARK_SERVICE_TYPE_ITEM AS	
SELECT 	
 	LOC_MARK_SERVICE_TYPE_ITEM_ID,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOC_MARK_SERVICE_TYPE_ITEM;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_LOC_MARK_SERVICE_TYPE_ITEM_2 AS	
SELECT 	
 	LOC_MARK_SERVICE_TYPE_ITEM_2_ID,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOC_MARK_SERVICE_TYPE_ITEM_2;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_LOC_MARK_SERVICE_TYPE_ITEM_LINK AS	
SELECT 	
 	LOC_MARK_SERVICE_TYPE_ITEM_ID,LOC_MARK_SERVICE_TYPE_ITEM_2_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOC_MARK_SERVICE_TYPE_ITEM_LINK;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_LOC_MARK_TYPE AS	
SELECT 	
 	LOC_MARK_TYPE_ID,FORCING,COLOUR,TO_VARCHAR(NAME,'utf-8') AS NAME,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,RGB_COLOUR,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOC_MARK_TYPE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_PROCESSED_COLLECTION AS	
SELECT 	
 	LOGG_ID,PROCESS_DATE,PROCESS_STATE,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.PROCESSED_COLLECTION;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_PRODUCT AS	
SELECT 	
 	PRODUCT_ID,PRODUCT_GROUP_ID,PRODUCT_NO,DESCRIPTION,REQ_PES_VALUE_2,REQ_PES_VALUE_TIME,ALLOW_OVERLAPPING,ALLOW_TO_OVERLAP,ALLOW_TO_SPLIT,ALLOW_CHANGE_SPLIT,ALLOW_OUTSIDE_GD,ALLOW_CHANGE_OUT,MINUTES_REDUCE_ST,MINUTES_REDUCE_END,ALLOW_TO_DISPLACE,ALLOW_CHANGE_DISPL,MINUTES_ADVANCE,MINUTES_AFTERWARDS,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ALLOW_MULTIPLE_ASSIGNM_PER_DAYT,ALLOW_CHANGE_MULTIPLE_ASSIGNM,GROUPED_COMMITMENT,GROUPED_COMMITMENT_MEMBER,ALLOW_REPLACE_CO_WITH_PO,PORTABLE_ALARM,IMPORT_TO_142_TAB_1,TIME_BANK_NOT_USED,EXCLUDE_FROM_TIME_BANK,ISACTIVE,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.PRODUCT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_PRODUCT_ASSIGNMENT_TYPE AS	
SELECT 	
 	PRODUCT_ID,ASSIGNMENT_TYPE_ID,ROWID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.PRODUCT_ASSIGNMENT_TYPE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_PRODUCT_DAY_TYPE_RELATION AS	
SELECT 	
 	PRODUCT_ID,DAY_T_ID,TIMEFROM,TIMETO,RELATION_FACTOR_ASSIGNM,RELATION_FACTOR_ROAD,VALIDFROM,VALIDTO,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.PRODUCT_DAY_TYPE_RELATION;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_PRODUCT_GROUP AS	
SELECT 	
 	PRODUCT_GROUP_ID,CONCEPT_ID,PRODUCT_GROUP_NO,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.PRODUCT_GROUP;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_PROFITC_LOC_OFF AS	
SELECT 	
 	PROFITCENTER_ID,LOC_OFFICE_ID,DATEFROM,DATETO,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.PROFITC_LOC_OFF;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_FILTER_GROUP AS	
SELECT 	
 	REPORT_MARK_FILTER_GROUP_ID,DESCRIPTION,FILTER_TYPE,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,PROFITCENTER_ID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_FILTER_GROUP;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_FILTER_ITEM AS	
SELECT 	
 	REPORT_MARK_FILTER_GROUP_ID,REPORT_MARK_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_FILTER_ITEM;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_FOLDER AS	
SELECT 	
 	REPORT_MARK_FOLDER_ID,PROFITCENTER_ID,DESCRIPTION,SYSTEM_OWNER,TO_VARCHAR(NOTES,'utf-8') AS NOTES,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_FOLDER;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_FOLDER_ITEM AS	
SELECT 	
 	REPORT_MARK_FOLDER_ID,REPORT_MARK_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_FOLDER_ITEM;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_FOLDER_ITEM_COMBI AS	
SELECT 	
 	REPORT_MARK_FOLDER_ID,REPORT_MARK_SET_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_FOLDER_ITEM_COMBI;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_FOLDER_ITEM_EMP AS	
SELECT 	
 	REPORT_MARK_FOLDER_ID,EMPLOYEE_MARK_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_FOLDER_ITEM_EMP;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_FOLDER_ITEM_GD AS	
SELECT 	
 	REPORT_MARK_FOLDER_ID,GD_MARK_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_FOLDER_ITEM_GD;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_GROUP AS	
SELECT 	
 	REPORT_MARK_GROUP_ID,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,FILTER_TYPE,PROFITCENTER_ID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_GROUP;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_GROUP_REP_MARK AS	
SELECT 	
 	REPORT_MARK_GROUP_ID,REPORT_MARK_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_GROUP_REP_MARK;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_SET AS	
SELECT 	
 	REPORT_MARK_SET_ID,BARCODE,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,SYSTEM,DESCRIPTION,ONLYFORFORMS,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_SET;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_SET_CULTURE AS	
SELECT 	
 	REPORT_MARK_SET_ID,CULTURE_ID,DESCRIPTION,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_SET_CULTURE;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_REPORT_MARK_SET_ITEM AS	
SELECT 	
 	REPORT_MARK_SET_ITEM_ID,REPORT_MARK_SET_ID,REPORT_MARK_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,SORT_ORDER,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.REPORT_MARK_SET_ITEM;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_SFU_COMMITMENTPLANNED AS	
SELECT 	
 	COMMITMENT_ID,DATEPLANNED,GD_ID,GD_STARTDATE,EMPLOYEE_ID,CUST_OBJ_ID,STARTDATETIME,STOPDATATIME,PLANNEDSTARTDATETIME,PLANNEDSTOPDATATIME,ASSTIMEPLANNED,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.SFU_COMMITMENTPLANNED;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_SFU_EVENT AS	
SELECT 	
 	EVENT_ID,EMPLOYEE_ID,PROD_OBJ_ID,LOC_OBJ_ID,RISK_LEVEL,EVENT_DATE,COMMENT,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,PUBLISHED,DELETED,MULTIPLICATION_FACTOR,TIME_CONSUMPTION,CREATED_BY_USER_ID,TO_VARCHAR(EMPLOYEE_NO,'utf-8') AS EMPLOYEE_NO,TO_VARCHAR(FIRSTNAME,'utf-8') AS FIRSTNAME,TO_VARCHAR(LASTNAME,'utf-8') AS LASTNAME,GD_ID,GMS_CASENUMBER,SDF_EVENT,SDF_CORRELATIONID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.SFU_EVENT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_SFU_EVENT_ATTACHMENT AS	
SELECT 	
 	SFU_EVENT_ATTACHMENT_ID,STATISTICSATTACHMENT_ID,EVENT_ID,ATTACHMENT,ATTACHMENT_BASESTR,CHECKSUM,MIMETYPE,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,PUBLISH,DESCRIPTION,FILENAME,FILE_VERSION,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.SFU_EVENT_ATTACHMENT;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_SFU_EVENT_ITEM AS	
SELECT 	
 	EVENT_ITEM_ID,EVENT_ID,EVENT_ITEM_TYPE_ID,REPORT_MARK_ID,INSERT_DATE,INSERT_USER,CHANGE_DATE,CHANGE_USER,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.SFU_EVENT_ITEM;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_SFU_GDPLANNED AS	
SELECT 	
 	GD_ID,GD_STARTDATE,GD_DATETIMEFROM,GD_DATETIMETO,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.SFU_GDPLANNED;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_SFU_PROCESSEDCOLLECTION AS	
SELECT 	
 	LOGG_ID,PROCESSTIME,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.SFU_PROCESSEDCOLLECTION;	
	
CREATE OR REPLACE SECURE VIEW DATAMART.RISKPREDICTION.GRSNO_SFU_VISITSPERFORMED AS	
SELECT 	
 	SFU_VISITSPERFORMED,DATEPERFORMED,GD_ID,GD_STARTDATE,EMPLOYEE_ID,CUST_OBJ_ID,STARTDATETIME,STOPDATATIME,LOGG_ID,NOREPORTS,NOATTACHMENTS,INSERT_USER,INSERT_DATE,CHANGE_USER,CHANGE_DATE,ROWID,MANUALREGISTRATIONDATETIME,START_TRANS_ID,STOP_TRANS_ID,ODS_SRC_SYSTEM_ID,ODS_CREATEDBY,ODS_MODIFIEDBY,ODS_MODIFIEDBY_TIMESTAMP,ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.SFU_VISITSPERFORMED;
