--STAGE DB CREATION - START --

CREATE OR REPLACE DATABASE STG_GRS_NO;

DROP  SCHEMA IF EXISTS STG_GRS_NO.PUBLIC;

CREATE OR REPLACE SCHEMA STG_GRS_NO.DBO;



--STAGE DB CREATION - END --

--ODS DB CREATION - START --

CREATE OR REPLACE DATABASE ODS_GRS_NO;

DROP  SCHEMA IF EXISTS ODS_GRS_NO.PUBLIC;

CREATE OR REPLACE SCHEMA ODS_GRS_NO.DBO;

CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.ALARM_CODES (
	ALARM_CODE_ID NUMBER(38,0) NOT NULL,
	SHORT_DESCRIPTION VARCHAR(4000),
	DESCRIPTION VARCHAR(4000),
	INSERT_DATE TIMESTAMP_NTZ(9),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	EXCLUDE_FROM_REPORT	BOOLEAN,
	ShowForAssignment	BOOLEAN,
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_ALARM_CODES PRIMARY KEY (ALARM_CODE_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.ALARM_GROUP (
	ALARM_GROUP_ID NUMBER(38,0) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	SORT_ORDER	NUMBER(10,0),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	PORTABLE_ALARM	NUMBER(10,0),
	TransferToGCS	BOOLEAN,
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_ALARM_GROUP PRIMARY KEY (ALARM_GROUP_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.ASSIGNMENT_TYPE (
	ASSIGNMENT_TYPE_ID NUMBER(38,0) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	ALLOW_TO_SPLIT	NUMBER(10,0),
	ALLOW_OUTSIDE_GD	NUMBER(10,0),
	MINUTES_REDUCE_ST	NUMBER(10,0),
	MINUTES_REDUCE_END	NUMBER(10,0),
	ALLOW_TO_DISPLACE	NUMBER(10,0),
	MINUTES_ADVANCE	NUMBER(10,0),
	MINUTES_AFTERWARDS	NUMBER(10,0),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	ALLOW_MULTIPLE_ASSIGNM_PER_DAYT	BOOLEAN,
	GROUPED_COMMITMENT	NUMBER(10,0),
	GROUPED_COMMITMENT_MEMBER	NUMBER(10,0),
	RAZZIA	NUMBER(10,0),
	SHOW_PO	NUMBER(10,0),
	Y_TYPE	NUMBER(10,0),
	ICON_ID	VARCHAR(20),
	TIME_BANK_NOT_USED	NUMBER(10,0),
	EXCLUDE_FROM_TIME_BANK	NUMBER(10,0),
	INTERNAL	NUMBER(10,0),
	UIColor	VARCHAR(20),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_ASSIGNMENT_TYPE PRIMARY KEY (ASSIGNMENT_TYPE_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.COMMITMENT (
	COMMITMENT_ID NUMBER(38,0) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	INSTRUCTION VARCHAR(4000),
	ASSIGNMENT_TYPE_NO	NUMBER(10,0),
	ASSIGNMENT_TYPE_ID	NUMBER(10,0),
	CONTRACT_ID	NUMBER(10,0),
	CONTRACT_PART_ID	NUMBER(10,0),
	ROAD_TIME_FROM_GD	NUMBER(10,0),
	DATEFROM	TIMESTAMP_NTZ(9),
	DATETO	TIMESTAMP_NTZ(9),
	VERSION_FROM	TIMESTAMP_NTZ(9),
	VERSION_TO	TIMESTAMP_NTZ(9),
	DISTRIBUTION_TYPE	NUMBER(10,0),
	RANDOM_COUNT	NUMBER(10,0),
	RANDOM_PERIOD	NUMBER(10,0),
	RANDOM_PERIOD_TYPE	NUMBER(10,0),
	RANDOM_MIN_DIST	NUMBER(10,0),
	PERIOD_LENGTH	NUMBER(10,0),
	PERIOD_TOTALLENGTH	NUMBER(10,0),
	PERIOD_START	TIMESTAMP_NTZ(9),
	ABS_COUNT	NUMBER(10,0),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	PRIORITY_TYPE	NUMBER(5,0),
	INCOME_TYPE	NUMBER(5,0),
	EXECUTE_TYPE	NUMBER(5,0),
	MULTIPLE_EXECUTION	NUMBER(5,0),
	SEASON_TYPE	NUMBER(5,0),
	PROCESS_TYPE	NUMBER(5,0),
	INCOME	NUMBER(19,4),
	ON_REPORT_REPLACE_CO_WITH_PO	NUMBER(10,0),
	RED	NUMBER(10,0),
	ENABLE_MONITORING	NUMBER(10,0),
	ENABLE_PRE_START_MONITORING	NUMBER(10,0),
	ENABLE_POST_START_MONITORING	NUMBER(10,0),
	PRE_START	NUMBER(10,0),
	POST_START	NUMBER(10,0),
	ENABLE_PRE_STOP_MONITORING	NUMBER(10,0),
	ENABLE_POST_STOP_MONITORING	NUMBER(10,0),
	PRE_STOP	NUMBER(10,0),
	POST_STOP	NUMBER(10,0),
	ENABLE_PERIOD_MONITORING	NUMBER(10,0),
	MONITORING_PERIOD	NUMBER(10,0),
	ENABLE_NOTIFY	NUMBER(10,0),
	PRE_TRANSPORT_NOTIFY_TIME	NUMBER(10,0),
	NOTIFY_PERIOD	NUMBER(10,0),
	ENABLE_NOTIFY_TRANSPORT	NUMBER(10,0),
	HIDDEN	NUMBER(10,0),
	AllowFingerScanning	BOOLEAN,
	EXTRAORDER_ID	NUMBER(10,0),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_COMMITMENT PRIMARY KEY (COMMITMENT_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.CONTRACT (
	CONTRACT_ID NUMBER(38,0) NOT NULL,
	CONTRACT_NO VARCHAR(4000),
	CUSTOMER_ID NUMBER(38,0),
	CONTACT BINARY(8388608),
	INVOICE_LATEST DATE,
	INVOICED_TO DATE,
	VALIDTO DATE,
	VALIDFROM	TIMESTAMP_NTZ(9),
	RENEWED	TIMESTAMP_NTZ(9),
	TERMINATE	TIMESTAMP_NTZ(9),
	CANCELLED	TIMESTAMP_NTZ(9),
	CONTRACT_TYPE_ID	NUMBER(10,0),
	TERM_OF_NOTICE	NUMBER(10,0),
	CANCEL_TYPE_ID	NUMBER(10,0),
	CANCEL_GROUND_ID	NUMBER(10,0),
	INVOICE_TYPE_ID	NUMBER(10,0),
	PAYMENT_MONTH	VARCHAR(12),
	JOINT_INVOICE	VARCHAR(2),
	JOINT_INVOICE_SORT	VARCHAR(10),
	INVOICE_FEE_ID	NUMBER(10,0),
	INVOICE_ACCEPT	NUMBER(10,0),
	TERMS_OF_PAYMNT_ID	NUMBER(10,0),
	MANUAL_ENVELOPE	NUMBER(10,0),
	MONTHLY_INC_CONT	NUMBER(19,4),
	MONTHLY_INC_ALL	NUMBER(19,4),
	CUSTOMER_REF	VARCHAR(25),
	INVOICE_TEXT_CODE	VARCHAR(2),
	SALESMAN_ID	VARCHAR(5),
	ENGINEER_ID	VARCHAR(4),
	SIGNED_CONTRACT	NUMBER(10,0),
	PRICE_CHANGE_PERC	NUMBER(18,0),
	PRICE_CHANGE_ID	VARCHAR(4),
	TOTAL_INV	NUMBER(19,4),
	TOTAL_INV_PREV_Y	NUMBER(19,4),
	TOTAL_INV_THIS_Y	NUMBER(19,4),
	LATEST_INVOICE_ID	NUMBER(10,0),
	LATEST_EXTRA_ID	NUMBER(10,0),
	NEW_CONTRACT	NUMBER(10,0),
	UPDATE_CODE	VARCHAR(1),
	CANCELLED_BY	VARCHAR(30),
	PRICE_CHANGE_EARL	TIMESTAMP_NTZ(9),
	REPLACE_OTHER_CONT	VARCHAR(1),
	REGISTRATION_DATE	TIMESTAMP_NTZ(9),
	REGISTERED_BY	VARCHAR(10),
	LATEST_CHANGE_DATE	TIMESTAMP_NTZ(9),
	LATEST_CHANGED_BY	VARCHAR(10),
	ROWIDMASTER	VARCHAR(30),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	CONTRACT_CONDITION_ID	NUMBER(10,0),
	PROFITCENTER_ID	NUMBER(10,0),
	MASTER_DATE	TIMESTAMP_NTZ(9),
	CENTRAL_VALIDTO	TIMESTAMP_NTZ(9),
	SYSTEM_CONTRACT_TYPE_ID	NUMBER(5,0),
	CENTRAL_USER	VARCHAR(60),
	CENTRAL_COMPANY	VARCHAR(60),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_CONTRACT PRIMARY KEY (CONTRACT_ID)
);

CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.CONTRACT_PART(
    CONTRACT_ID                 INTEGER           NOT NULL, ---TO BE ADDED
    CONTRACT_PART_ID            INTEGER           NOT NULL,
    CONTRACT_PART_NO            VARCHAR(4000),
    CUST_OBJ_ID                 INTEGER,
    CONTRACT_PART_CENTRAL_NO	VARCHAR(20),
	PRODUCT_ID	NUMBER(10,0),
	INVOICE_ADDR_CODE	VARCHAR(1),
	INVOICE_TEXT_CODE	VARCHAR(2),
	TRANSMITTER_NO	VARCHAR(12),
	PLANNED_PROD_START	TIMESTAMP_NTZ(9),
	TERMINATION_CODE	VARCHAR(1),
	LATEST_CONTR_CHAN	NUMBER(10,0),
	CONTR_REG_DATE	TIMESTAMP_NTZ(9),
	VALIDFROM	TIMESTAMP_NTZ(9),
	VALIDTO	TIMESTAMP_NTZ(9),
	PORTF_PROFITC_ID	NUMBER(10,0),
	PORTF_MONTH_INCOME	NUMBER(19,4),
	REGISTRATION_DATE	TIMESTAMP_NTZ(9),
	REGISTERED_BY	VARCHAR(10),
	LATEST_CHANGE_DATE	TIMESTAMP_NTZ(9),
	LATEST_CHANGED_BY	VARCHAR(10),
	ROWIDMASTER	VARCHAR(30),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	MASTER_DATE	TIMESTAMP_NTZ(9),
	CENTRAL_USER	VARCHAR(60),
	CENTRAL_COMPANY	VARCHAR(60),
	COMMITMENT_INCOME_TYPE	NUMBER(10,0),
	DESCRIPTION	VARCHAR(60),
	MULTIPLE_ASSIGNMENTS	NUMBER(10,0),
	COMMITMENT_INCOME_MONEY	NUMBER(19,4),
	TIME_BANK	NUMBER(10,0),
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),
    ODS_MODIFIEDBY              VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
   CONSTRAINT PK_CONTRACT_PART PRIMARY KEY (CONTRACT_ID,CONTRACT_PART_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.CONTRACT_TYPE (
	CONTRACT_TYPE_ID NUMBER(38,0) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	CONTRACT_TYPE_NO	VARCHAR(10),
	ROWIDMASTER	VARCHAR(30),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_CONTRACT_TYPE PRIMARY KEY (CONTRACT_TYPE_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.CONTR_PART_VER (
	CONTRACT_ID NUMBER(38,0) NOT NULL,
	CONTRACT_PART_ID NUMBER(38,0) NOT NULL,
	VERSION_FROM DATE NOT NULL,
	PROFITCENTER_ID NUMBER(38,0),
	VERSION_TO	TIMESTAMP_NTZ(9),
	MONTHLY_INCOME	NUMBER(19,4),
	CONTR_REG_DATE	TIMESTAMP_NTZ(9),
	INVOICE_STATUS	NUMBER(10,0),
	ALTERATION_TYPE	VARCHAR(1),
	PRICE_CHANGE_CONST	NUMBER(18,0),
	REGISTRATION_DATE	TIMESTAMP_NTZ(9),
	REGISTERED_BY	VARCHAR(10),
	LATEST_CHANGE_DATE	TIMESTAMP_NTZ(9),
	LATEST_CHANGED_BY	VARCHAR(10),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	DAYTYPE_MINUTES	NUMBER(10,0),
	DATE_MINUTES	NUMBER(10,0),
	DAYTYPE_CALCULATION_READY	NUMBER(5,0),
	DATE_CALCULATION_READY	NUMBER(5,0),
	MASTER_DATE	TIMESTAMP_NTZ(9),
	change_type_1	NUMBER(5,0),
	change_type_2	NUMBER(5,0),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_CONTR_PART_VER PRIMARY KEY (CONTRACT_ID, CONTRACT_PART_ID, VERSION_FROM)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.CUSTOMER (
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	NAME_SEARCH BINARY(8388608),
	CUSTOMER_TYPE_ID NUMBER(38,0),
	CUSTOMER_NO VARCHAR(4000),
	NAME_1 BINARY(8388608),
	ADDRESS BINARY(8388608),
	POSTCODE BINARY(8388608),
	POSTADDRESS BINARY(8388608),
	VALIDTO DATE,
	ORGANIZATION_NO	VARCHAR(11),
	NAME_2	VARCHAR(30),
	POSTDELIVERY_ADDRESS	VARCHAR(40),
	TELEPHONE_1	VARCHAR(20),
	TELEPHONE_2	VARCHAR(20),
	TELEFAX	VARCHAR(20),
	ROWIDMASTER	VARCHAR(30),
	MARKET_CODE	VARCHAR(5),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	POSTDELIVERY_ADDRESS_Extra	VARCHAR(40),
	MASTER_DATE	TIMESTAMP_NTZ(9),
	SYSTEM_CUSTOMER_TYPE_ID	NUMBER(5,0),
	SYSTEM_PROFITCENTER_ID	NUMBER(5,0),
	CENTRAL_COMPANY	VARCHAR(60),
	CENTRAL_USER	VARCHAR(60),
	CONFIRM_QUESTION_LIMIT	NUMBER(10,0),
	GrsrwEnable	NUMBER(5,0),
	RequiresKAMpermission	BOOLEAN,	
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);


CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.CUSTOMER_OBJECT (
	CUST_OBJ_NO VARCHAR(4000),
	CUST_OBJ_ID NUMBER(38,0) NOT NULL,
	PROFITCENTER_ID VARCHAR(4000),
	NAME VARCHAR(4000),
	ADDRESS VARCHAR(4000),
	POSTDELIVERY_ADDRESS VARCHAR(4000),
	POSTCODE VARCHAR(4000),
	ADDRESS_2 VARCHAR(4000),
	POSTADDRESS VARCHAR(4000),
	ASSIGNMENTGEOLOCATION BINARY(8388608),
	TERMINATE_DATE DATE,
	GEO_LAT BINARY(8388608),
	GEO_LONG BINARY(8388608),
	BLOCK	VARCHAR(40),
	DISTRICT	VARCHAR(40),
	REF_PERSON	VARCHAR(40),
	TELEPHONE	VARCHAR(20),
	TELEFAX	VARCHAR(20),
	TELEMODEM	VARCHAR(20),
	MARKET_ID	NUMBER(10,0),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	POSTDELIVERY_ADDRESS_Extra	VARCHAR(40),
	MASTER_DATE	TIMESTAMP_NTZ(9),
	CITY_ID	NUMBER(10,0),
	CITY_PART_ID	NUMBER(10,0),
	BLOCK_ID	NUMBER(10,0),
	InvoiceCustomer_no	VARCHAR(25),
	Customer_Object_type	VARCHAR(2),
	AddressCode	VARCHAR(1),
	Profitcenter_no	VARCHAR(4),
	XPos	VARCHAR(20),
	YPos	VARCHAR(20),
	CENTRAL_USER	VARCHAR(60),
	CENTRAL_COMPANY	VARCHAR(60),
	MARKET_ITEM_ID	NUMBER(10,0),
	PROFITCENTER_ID	NUMBER(10,0),
	NOTES	VARCHAR(16777216),
	PROTECTED	NUMBER(10,0),
	ENABLE_PROD_OBJ_POSITION	NUMBER(10,0),
	VISION_ID	VARCHAR(15),
	AssignmentPostcode	VARCHAR(12),
	AllowCamera	BOOLEAN,
	CALENDAR_TEMPLATE_ID	NUMBER(10,0),
	UseCustomerAddress	BOOLEAN,
	XDE_SUBCONTRACTOR_CCT_NO	VARCHAR(20),
	XDE_EXTRA_INFORMATION	VARCHAR(300),
	XDE_PRODUCTS	VARCHAR(100),
	XDE_CUSTOMER_NAME	VARCHAR(40),
	XDE_IS_EXTERNAL	BOOLEAN,
	IsBlacklisted	BOOLEAN,
	BlacklistComment	VARCHAR(1000),
	GLOBAL_MASTER_NO	VARCHAR(50),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_CUSTOMER_OBJECT PRIMARY KEY (CUST_OBJ_ID)
);

CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.CUST_CUST_OBJECT (
	CUST_OBJ_ID NUMBER(38,0) NOT NULL,
	CUSTOMER_ID NUMBER(38,0) NOT NULL,
	DATEFROM DATE NOT NULL,
	DATETO DATE,
	INSERT_DATE	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	ROWID	VARCHAR(16),
	MASTER_DATE	TIMESTAMP_NTZ(9),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_CUST_CUST_OBJECT PRIMARY KEY (CUST_OBJ_ID, CUSTOMER_ID, DATEFROM)
);

CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.GCS_EXPORT_ERP_CALL_OUTS (
	case_number	VARCHAR(14),
	transferring_time	VARCHAR(10),
	free_text_from_guard	VARCHAR(8388608),
	free_text_from_operator	VARCHAR(8388608),
	handle_manually	BOOLEAN
	alarm_center_number	VARCHAR(3),
	alarm_center_reference	VARCHAR(36),
	alarm_center_address	VARCHAR(255),
	alarm_center_zip_code	VARCHAR(50),
	alarm_center_location	VARCHAR(30),
	alarm_center_telephone_number	VARCHAR(40),
	alarm_center_name	VARCHAR(50),
	alarm_center_contract_number	VARCHAR(30),
	alarm_number	VARCHAR(50),
	alarm_time	VARCHAR(10),
	alarm_reach_time	VARCHAR(10),
	alarm_type	VARCHAR(55),
	alarm_type_text	VARCHAR(50),
	alarm_issue_code	NUMBER(10,0),
	alarm_issue_description	VARCHAR(60),
	guard_section	VARCHAR(40000),
	measures_code	NUMBER(38,0),
	measures_text	VARCHAR(60),
	building_number	VARCHAR(60),
	building_name	VARCHAR(100),
	building_address	VARCHAR(300),
	building_location	VARCHAR(255),
	building_section	VARCHAR(4000),
	building_zip_code	VARCHAR(30),
	customer_object	VARCHAR(30),
	customer_number	VARCHAR(120),
	customer_organization_id	VARCHAR(15),
	customer_vat_number	VARCHAR(14),
	customer_social_security_number	VARCHAR(14),
	CUSTOMER_NAME_1 BINARY(8388608),
	customer_name_2	BINARY(8388608),
	customer_address	VARCHAR(255),
	customer_zip_code	VARCHAR(30),
	customer_location	VARCHAR(255),
	invoice_customer_name_1	VARCHAR(255),
	invoice_customer_name_2	VARCHAR(255),
	invoice_customer_address	VARCHAR(255),
	invoice_customer_zipcode	VARCHAR(30),
	invoice_customer_location	VARCHAR(30),
	exported_time_stamp	TIMESTAMP_NTZ(9),
	INSERT_USER	VARCHAR(254),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	ROWID VARCHAR(16),
	call_out_barcode VARCHAR(200),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_GCS_EXPORT_ERP_CALL_OUTS PRIMARY KEY (CASE_NUMBER)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.GCS_EXPORT_ERP_CALL_OUT_GUARDS (
	case_number	VARCHAR(14),
	arrival_time	VARCHAR(10),
	departure_time	VARCHAR(10),
	elapsed_time	NUMBER(30,0),
	employment_number	VARCHAR(10),
	cost_centre	VARCHAR(20),
	base_location_number	VARCHAR(20),
	guard_type	VARCHAR(1),
	visit_detail	VARCHAR(16777216),
	INSERT_USER	VARCHAR(254),
	INSERT_DATE	TIMESTAMP_NTZ(9),
	CHANGE_USER	VARCHAR(254),
	CHANGE_DATE	TIMESTAMP_NTZ(9),
	ROWID	VARCHAR(16),
	on_way_time	VARCHAR(10),
	return_time_back_to_office	VARCHAR(10),
	INSERT_DATE TIMESTAMP_NTZ(9),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.GD (
	GD_ID NUMBER(38,0) NOT NULL,
	GD_NO VARCHAR(4000),
	PROFITCENTER_ID NUMBER(10,0),
	GD_TYPE_ID NUMBER(10,0),
	GD_KNOWREQ NUMBER(10,0),
	DATEFROM TIMESTAMP_NTZ(9),
	DATETO TIMESTAMP_NTZ(9),
	NAME VARCHAR(40),
	ADDRESS VARCHAR(40),
	POSTCODE VARCHAR(12),
	POSTADDRESS VARCHAR(40),
	REF_PERSON VARCHAR(40),
	TELEPHONE VARCHAR(20),
	TELEFAX VARCHAR(20),
	TELEMODEM VARCHAR(20),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	"POSTDELIVERY_ADDRESS_Extra" VARCHAR(40),
	PE_PROFITC VARCHAR(4),
	PE_NO VARCHAR(4),
	REPORT_MARK_FOLDER_ID NUMBER(10,0),
	EXPORT_TO_GMP NUMBER(10,0),
	VISIBLE_IN_153 NUMBER(10,0),
	EXCLUDE_EMPTY_GD_SHIFT NUMBER(10,0),
	"StartLocation" VARCHAR(50),
	"GeoLocation" VARCHAR(16777216),
	CALENDAR_TEMPLATE_ID NUMBER(10,0),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_GD PRIMARY KEY (GD_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.GRS_ADDONINFO (
	CASE_NUMBER VARCHAR(14),
	CUST_OBJ_NO VARCHAR(15),
	CUSTOMER_NO VARCHAR(25),
	GRSR_EVENT_ID NUMBER(38,0),
	Alarm_NO VARCHAR(50),
	Alarm_group_no VARCHAR(50),
	Alarm_group_name VARCHAR(60),
	Alarm_portable_no VARCHAR(50),
	Alaram_portable_name VARCHAR(60),
	Cust_obj_no VARCHAR(15),
	Cust_obj_no_alt VARCHAR(15),
	Alarm_id NUMBER(10,0),
	Alarm_time TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	INSERT_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	ROWID VARCHAR(16),
	ID NUMBER(10,0),
	SFU_EVENT_ID NUMBER(10,0),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_GRS_ADDONINFO PRIMARY KEY (CASE_NUMBER)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.LOCATION_MARK (
	LOCATION_MARK_ID NUMBER(38,0) NOT NULL,
	BARCODE VARCHAR(4000),
	POSITION BINARY(8388608),
	POSITION_GUARD_INFO VARCHAR(4000),
	PROD_OBJ_ID NUMBER(10,0),
	LOC_OBJ_ID NUMBER(10,0),
	LOC_MARK_TYPE_ID NUMBER(10,0),
	ACTION VARCHAR(100),
	ORDER_NO NUMBER(10,0),
	ORDER_NO_EXTRA NUMBER(10,0),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	VALIDTO TIMESTAMP_NTZ(9),
	VALIDFROM TIMESTAMP_NTZ(9),
	LOC_MARK_SERVICE_NO VARCHAR(60),
	LOC_MARK_SERVICE_LOCATION VARCHAR(60),
	LOC_MARK_SERVICE_INTERVAL_ID NUMBER(10,0),
	LOC_MARK_SERVICE_EXT_INTERVAL_ID NUMBER(10,0),
	LOC_MARK_SERVICE_TYPE_ID NUMBER(10,0),
	LOC_MARK_SERVICE_TYPE_ITEM_ID NUMBER(10,0),
	LOC_MARK_SERVICE_TYPE_ITEM_2_ID NUMBER(10,0),
	LOC_MARK_SERVICE_YEAR NUMBER(10,0),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_LOCATION_MARK PRIMARY KEY (LOCATION_MARK_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.LOCATION_OBJECT (
	PROD_OBJ_ID NUMBER(38,0) NOT NULL,
	LOC_OBJ_ID NUMBER(38,0) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	VALIDFROM TIMESTAMP_NTZ(9),
	VALIDTO TIMESTAMP_NTZ(9),
	LOCATION_OBJ_ID NUMBER(10,0),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_LOCATION_OBJECT PRIMARY KEY (PROD_OBJ_ID, LOC_OBJ_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.PROCESSED_TRANSACTIONS (
	LOGG_ID NUMBER(38,0) NOT NULL,
	TRANS_ID NUMBER(38,0) NOT NULL,
	SUB_ID NUMBER(38,0) NOT NULL,
	GD_ID NUMBER(38,0),
	PROD_OBJ_ID NUMBER(38,0),
	LOC_OBJ_ID NUMBER(38,0),
	MULTIPLICATION_FACTOR NUMBER(38,0),
	REPORT_NOTES BINARY(8388608),
	COMMITMENT_ID NUMBER(38,0),
	POSITION BINARY(8388608),
	BARCODE_DATE TIMESTAMP_NTZ(9),
	BARCODE_TIME TIMESTAMP_NTZ(9),
	BARCODE_NO VARCHAR(16),
	BARCODE_GROUP NUMBER(10,0),
	BARCODE_TYPE NUMBER(10,0),
	LOC_MARK_TYPE NUMBER(10,0),
	REQUIRED BOOLEAN,
	EMPLOYEE_ID NUMBER(10,0),
	VALID_ASSOCIATION BOOLEAN,
	DAY_T_ID NUMBER(10,0),
	VERSION_FROM TIMESTAMP_NTZ(9),
	ASSIGNM_TIMEFROM TIMESTAMP_NTZ(9),
	CE_VALID_ASSOCIATION BOOLEAN,
	CE_COMMITMENT_ID NUMBER(10,0),
	CE_EXCEPTION NUMBER(10,0),
	CE_DAY_T_ID NUMBER(10,0),
	CE_DATEFROM TIMESTAMP_NTZ(9),
	CE_TIMEFROM TIMESTAMP_NTZ(9),
	REQ_CORRECTION_TYPE NUMBER(10,0),
	ERROR_FLAG BOOLEAN,
	NOTES VARCHAR(100),
	ASSOCIATION_NORMAL NUMBER(5,0),
	ASSOCIATION_CE NUMBER(5,0),
	LOCATION_MARK_ID NUMBER(10,0),
	ACTION VARCHAR(100),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	EMPLOYEE_NO VARCHAR(6),
	FIRSTNAME VARCHAR(20),
	LASTNAME VARCHAR(28),
	TIME_CONSUMPTION NUMBER(10,0),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_PROCESSED_TRANSACTIONS PRIMARY KEY (LOGG_ID, TRANS_ID, SUB_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.PRODUCTION_OBJECT (
	PROD_OBJ_ID NUMBER(38,0) NOT NULL,
	PROD_OBJ_NO VARCHAR(4000),
	DESCRIPTION VARCHAR(4000),
	ADDRESS VARCHAR(4000),
	POSTDELIVERY_ADDRESS VARCHAR(40),
	POSTCODE VARCHAR(12),
	POSTADDRESS VARCHAR(40),
	REF_PERSON VARCHAR(40),
	TELEPHONE VARCHAR(20),
	TELEFAX VARCHAR(20),
	TELEMODEM VARCHAR(20),
	XPOS VARCHAR(20),
	YPOS VARCHAR(20),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	ADDRESS_2 VARCHAR(40),
	"POSTDELIVERY_ADDRESS_Extra" VARCHAR(40),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_PRODUCTION_OBJECT PRIMARY KEY (PROD_OBJ_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.PROFITCENTER (
	PROFITCENTER_ID NUMBER(38,0) NOT NULL,
	PROFITCENTER_NO VARCHAR(4000),
	RESPONSIBLE VARCHAR(40),
	DESCRIPTION VARCHAR(60),
	DATEFROM TIMESTAMP_NTZ(9),
	DATETO TIMESTAMP_NTZ(9),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	POSITION_TYPE_REF NUMBER(10,0),
	"visible" BOOLEAN,
	CO_OWNERSHIP_ALLOWED NUMBER(10,0),
	"KPIStartDate" TIMESTAMP_NTZ(9),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_PROFITCENTER PRIMARY KEY (PROFITCENTER_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.REPORT_MARK (
	REPORT_MARK_ID NUMBER(38,0) NOT NULL,
	REPORT_LABEL VARCHAR(4000),
	REP_MARK_TYPE_ID NUMBER(10,0),
	BARCODE VARCHAR(20),
	ACTIVITY_CODE VARCHAR(1),
	TIMELIMIT_CODE VARCHAR(3),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	"report_mark_version" NUMBER(5,0),
	RISK_LEVEL NUMBER(10,0),
	SYSTEM BOOLEAN,
	REPORT_FOLDER_LABEL VARCHAR(30),
	STATISTICS_MEMBER NUMBER(10,0),
	CODE VARCHAR(10),
	"report_label_2" VARCHAR(60),
	REPORT_MARK_SET_ONLY NUMBER(10,0),
	SBA NUMBER(10,0),
	"report_label_GCS_Sync" VARCHAR(60),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_REPORT_MARK PRIMARY KEY (REPORT_MARK_ID)
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.TEMP_TRANSACTIONS (
	LOGG_ID NUMBER(38,0) NOT NULL,
	TRANS_ID NUMBER(38,0) NOT NULL,
	BARCODE_TIME TIMESTAMP_NTZ(9),
	BARCODE_NO VARCHAR(4000),
	BARCODE_GROUP NUMBER(10,0),
	LATITUDE BINARY(8388608),
	LONGITUDE BINARY(8388608),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	NOTES VARCHAR(2000),
	ADJUSTED_GD_ID NUMBER(10,0),
	ADJUSTED_EMPLOYEE_ID NUMBER(10,0),
	"MUAssignment_ID" NUMBER(10,0),
	"Report_Notes" VARCHAR(2000),
	"multiplication_factor" NUMBER(10,0),
	"AssignmentPlannedID" VARCHAR(20),
	"Is_Fingerscanned" BOOLEAN,
	GPSTIMESTAMP TIMESTAMP_NTZ(9),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_TEMP_TRANSACTIONS PRIMARY KEY (LOGG_ID, TRANS_ID)
);

CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.XREPORT_MARK (
	REPORT_MARK_ID NUMBER(38,0),
	REP_MARK_TYPE_ID NUMBER(38,0),
	BARCODE VARCHAR(20),
	REPORT_LABEL VARCHAR(60),
	ACTIVITY_CODE VARCHAR(1),
	TIMELIMIT_CODE VARCHAR(3),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	REPORT_MARK_VERSION NUMBER(38,0),
	RISK_LEVEL NUMBER(38,0),
	SYSTEM BOOLEAN,
	REPORT_FOLDER_LABEL VARCHAR(30),
	STATISTICS_MEMBER NUMBER(38,0),
	CODE VARCHAR(10),
	REPORT_LABEL_2 VARCHAR(60),
	REPORT_MARK_SET_ONLY NUMBER(38,0),
	SBA NUMBER(38,0),
	CULTURE_ID NUMBER(38,0),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.XPROCESSED_TRANSACTIONS (
	LOGG_ID NUMBER(38,0),
	TRANS_ID NUMBER(38,0),
	SUB_ID NUMBER(38,0),
	BARCODE_DATE TIMESTAMP_NTZ(9),
	BARCODE_TIME TIMESTAMP_NTZ(9),
	BARCODE_NO VARCHAR(16),
	BARCODE_GROUP NUMBER(38,0),
	BARCODE_TYPE NUMBER(38,0),
	LOC_MARK_TYPE NUMBER(38,0),
	REQUIRED BOOLEAN,
	EMPLOYEE_ID NUMBER(38,0),
	GD_ID NUMBER(38,0),
	VALID_ASSOCIATION BOOLEAN,
	COMMITMENT_ID NUMBER(38,0),
	DAY_T_ID NUMBER(38,0),
	VERSION_FROM TIMESTAMP_NTZ(9),
	ASSIGNM_TIMEFROM TIMESTAMP_NTZ(9),
	CE_VALID_ASSOCIATION BOOLEAN,
	CE_COMMITMENT_ID NUMBER(38,0),
	CE_EXCEPTION NUMBER(38,0),
	CE_DAY_T_ID NUMBER(38,0),
	CE_DATEFROM TIMESTAMP_NTZ(9),
	CE_TIMEFROM TIMESTAMP_NTZ(9),
	REQ_CORRECTION_TYPE NUMBER(38,0),
	ERROR_FLAG BOOLEAN,
	NOTES BINARY(8388608),
	ASSOCIATION_NORMAL NUMBER(38,0),
	ASSOCIATION_CE NUMBER(38,0),
	LOCATION_MARK_ID NUMBER(38,0),
	PROD_OBJ_ID NUMBER(38,0),
	LOC_OBJ_ID NUMBER(38,0),
	POSITION BINARY(8388608),
	ACTION VARCHAR(100),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	REPORT_NOTES BINARY(8388608),
	EMPLOYEE_NO VARCHAR(6),
	FIRSTNAME BINARY(8388608),
	LASTNAME BINARY(8388608),
	MULTIPLICATION_FACTOR NUMBER(38,0),
	TIME_CONSUMPTION NUMBER(38,0),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
CREATE OR REPLACE TABLE ODS_GRS_NO.DBO.XPROCESSED_BARCODES (
	LOGG_ID NUMBER(38,0),
	TRANS_ID NUMBER(38,0),
	SUB_ID NUMBER(38,0),
	BARCODE_DATE TIMESTAMP_NTZ(9),
	BARCODE_TIME TIMESTAMP_NTZ(9),
	BARCODE_NO VARCHAR(16),
	BARCODE_GROUP NUMBER(38,0),
	BARCODE_TYPE NUMBER(38,0),
	LOC_MARK_TYPE NUMBER(38,0),
	REQUIRED BOOLEAN,
	EMPLOYEE_ID NUMBER(38,0),
	GD_ID NUMBER(38,0),
	VALID_ASSOCIATION BOOLEAN,
	COMMITMENT_ID NUMBER(38,0),
	DAY_T_ID NUMBER(38,0),
	VERSION_FROM TIMESTAMP_NTZ(9),
	ASSIGNM_TIMEFROM TIMESTAMP_NTZ(9),
	CE_VALID_ASSOCIATION BOOLEAN,
	CE_COMMITMENT_ID NUMBER(38,0),
	CE_EXCEPTION NUMBER(38,0),
	CE_DAY_T_ID NUMBER(38,0),
	CE_DATEFROM TIMESTAMP_NTZ(9),
	CE_TIMEFROM TIMESTAMP_NTZ(9),
	REQ_CORRECTION_TYPE NUMBER(38,0),
	ERROR_FLAG BOOLEAN,
	NOTES BINARY(8388608),
	ASSOCIATION_NORMAL NUMBER(38,0),
	ASSOCIATION_CE NUMBER(38,0),
	LOCATION_MARK_ID NUMBER(38,0),
	PROD_OBJ_ID NUMBER(38,0),
	LOC_OBJ_ID NUMBER(38,0),
	POSITION BINARY(8388608),
	ACTION VARCHAR(100),
	INSERT_DATE TIMESTAMP_NTZ(9),
	INSERT_USER VARCHAR(254),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	CHANGE_USER VARCHAR(254),
	ROWID VARCHAR(16),
	REPORT_NOTES BINARY(8388608),
	EMPLOYEE_NO BINARY(8388608),
	FIRSTNAME BINARY(8388608),
	LASTNAME BINARY(8388608),
	MULTIPLICATION_FACTOR NUMBER(38,0),
	TIME_CONSUMPTION NUMBER(38,0),
	ODS_SRC_SYSTEM_ID NUMBER(38,0),
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

---Cluster xProcessed_transactions, x_processed_barcodes--

ALTER   TABLE "ODS_GRS_NO"."DBO"."XPROCESSED_TRANSACTIONS" CLUSTER BY (BARCODE_NO);
ALTER   TABLE "ODS_GRS_NO"."DBO"."XPROCESSED_BARCODES" CLUSTER BY (BARCODE_NO);
------


--ODS DB CREATION - END --


--DW DB CREATION - START --
CREATE OR REPLACE DATABASE DW;

DROP  SCHEMA IF EXISTS DW.PUBLIC;

CREATE OR REPLACE SCHEMA DW.BASE;

CREATE OR REPLACE SCHEMA DW.CONTROL;


CREATE OR REPLACE TABLE DW.CONTROL.LOGGING (
	LOGGING_ID NUMBER(38,0) NOT NULL,
	PROCESS_TYPE VARCHAR(100) NOT NULL,
	PROCESS_ID NUMBER(38,0),
	OBJECT_NAME VARCHAR(255),
	COMMAND VARCHAR(16777216) NOT NULL,
	RUN_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL,
	RUN_RESULT VARCHAR(100) NOT NULL,
	RECORDS_INSERTED NUMBER(38,0),
	RECORDS_UPDATED NUMBER(38,0),
	RECORDS_DELETED NUMBER(38,0),
	SRC_SYSTEM_ID NUMBER(38,0) NOT NULL,
	DW_SRC_SYSTEM_ID NUMBER(38,0),
	DW_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	DW_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	DW_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	DW_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP());
	
CREATE OR REPLACE TABLE DW.CONTROL.PROCESS (
	PROCESS_ID NUMBER(38,0) NOT NULL,
	TABLE_CATALOG VARCHAR(200) NOT NULL,
	PROCESS_TYPE VARCHAR(100) NOT NULL,
	PROCESS_ORDER NUMBER(38,0) NOT NULL,
	LAST_RUN_TIMESTAMP TIMESTAMP_LTZ(9),
	NOTES VARCHAR(16777216),
	COMMAND VARCHAR(16777216),
	DW_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	DW_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	DW_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	DW_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP());
	
	
CREATE OR REPLACE TABLE DW.CONTROL.SOURCESYSTEM (
	SOURCESYSTEMID NUMBER(38,0) NOT NULL,
	SOURCESYSTEMNAME VARCHAR(100) NOT NULL,
	SOURCEHOSTNAME VARCHAR(100),
	SOURCEDATABASENAME VARCHAR(100),
	SOURCEPORTNUMBER VARCHAR(10),
	SOURCECONNECTIONSTRING VARCHAR(100),
	SOURCEUSERID VARCHAR(50),
	SOURCEPASSWORD VARCHAR(50),
	SOURCECATALOGQUERY VARCHAR(1000),
	SOURCETIMEZONE VARCHAR(30),
	STAGEDATABASENAME VARCHAR(100),
	ODSDATABASENAME VARCHAR(100),
	ACTIVEFLAG BOOLEAN,
	CREATEDUSERID VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
	CREATEDDATETIME TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	LASTUPDATEDUSERID VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
	LASTUPDATEDDATETIME TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	DBMS VARCHAR(100),
	BACKUPSCHEMANAME VARCHAR(100),
	EKEY VARCHAR(100),
	PASSPHARSE VARCHAR(100),
	CONSTRAINT PK_SOURCESYSTEM PRIMARY KEY (SOURCESYSTEMID)
);

CREATE OR REPLACE TABLE DW.CONTROL.LOADPROCESS (
	SOURCESYSTEMID NUMBER(38,0) NOT NULL,
	SOURCESCHEMANAME VARCHAR(100) NOT NULL,
	SOURCETABLENAME VARCHAR(100) NOT NULL,
	STAGESCHEMANAME VARCHAR(100),
	STAGETABLENAME VARCHAR(100),
	ODSSCHEMANAME VARCHAR(100),
	ODSTABLENAME VARCHAR(100),
	STAGETYPE VARCHAR(20),
	LOADTYPE VARCHAR(20),
	ACTIVEFLAG BOOLEAN DEFAULT FALSE,
	WATERMARKCOLUMNNAME VARCHAR(100) DEFAULT '2',
	WATERMARKDATATYPE VARCHAR(100),
	WATERMARKLASTVALUE VARCHAR(100) DEFAULT '1',
	LASTSTAGEDATETIME TIMESTAMP_LTZ(9),
	LASTLOADDATETIME TIMESTAMP_LTZ(9),
	CREATEDUSERID VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
	CREATEDDATETIME TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	LASTUPDATEDUSERID VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
	LASTUPDATEDDATETIME TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_PK VARCHAR(200),
	NRTFLAG BOOLEAN DEFAULT FALSE,
	ISRESTRICTED BOOLEAN,
	RESTRICTEDCOLUMNNAME VARCHAR(100),
	RESTRICTEDTABLENAME VARCHAR(100),
	SOURCE_SQL VARCHAR(4000),
	EXPRESSIONS     VARCHAR(4000),
	RESTRICTEDTABLE_RANK NUMBER,
	CONSTRAINT PK_LOADPROCESS PRIMARY KEY (SOURCESYSTEMID, SOURCESCHEMANAME, SOURCETABLENAME)
);



CREATE OR REPLACE TABLE DW.CONTROL.COLUMNDETAILS (
		SOURCESYSTEMID NUMBER(38,0) NOT NULL,
		STAGEDATABASENAME VARCHAR(100),
		STAGESCHEMANAME VARCHAR(100),
		STAGETABLENAME VARCHAR(100),
		STAGETABLECOLUMN VARCHAR(100),
		ODSDATABASENAME VARCHAR(100),
		ODSSCHEMANAME VARCHAR(100),
		ODSTABLENAME VARCHAR(100),
		ODSTABLECOLUMN VARCHAR(100),
		ACTIVEFLAG BOOLEAN DEFAULT FALSE,
		ISPSEUDONYMISED BOOLEAN DEFAULT FALSE,
		EXPRESSIONS VARCHAR(100),
		CREATEDUSERID VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
		CREATEDDATETIME TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
		LASTUPDATEDUSERID VARCHAR(50) NOT NULL DEFAULT CURRENT_USER(),
		LASTUPDATEDDATETIME TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
		ISPKEY BOOLEAN,
		DATATYP VARCHAR(100),
		CONSTRAINT PK_COLUMNDETAILS PRIMARY KEY (SOURCESYSTEMID, STAGESCHEMANAME, STAGETABLENAME, STAGETABLECOLUMN)
	);

CREATE OR REPLACE TABLE DW.CONTROL.KEY_STORE (
	SOURCESYSTEM VARCHAR(100),
	KEY_VALUE VARCHAR(100),
	PASSPHARSE VARCHAR(100),
	ADVANCED_ENCRYPTION_STD VARCHAR(100),
	VALID_ROLES ARRAY
);

CREATE OR REPLACE VIEW SOURCESYSTEM_LOADPROCESS3 AS  
With PSEUDONYMISEDCOLUMNLISTEXP AS 
  (
	SELECT a.SOURCESYSTEMID,NVL(a.Column_List||','||b.Column_List_exp,a.Column_List) ColumnListExp,a.STAGEDATABASENAME,a.STAGETABLENAME from   
     (
     SELECT SOURCESYSTEMID,STAGEDATABASENAME,STAGETABLENAME,
    listagg( NVL(EXPRESSIONS,'') || '  "' ||(STAGETABLECOLUMN) ||'" as ' ||UPPER(STAGETABLECOLUMN), ',') 
        within GROUP (ORDER BY (STAGETABLENAME)) AS Column_List
    FROM "DW"."CONTROL"."COLUMNDETAILS" WHERE 
    ACTIVEFLAG = 'TRUE' 
    AND NVL(ISPSEUDONYMISED,'FALSE')  = 'FALSE'
    --AND SOURCESYSTEMID=1 
    GROUP BY SOURCESYSTEMID,STAGEDATABASENAME,STAGETABLENAME) a 
    LEFT OUTER JOIN 
     (SELECT c.SOURCESYSTEMID,c.STAGEDATABASENAME,c.STAGETABLENAME,
    listagg( NVL('encrypt("'||c.STAGETABLECOLUMN||'",'||s.PASSPHARSE||','''||s.EKEY||''',''aes-gcm'')','') || ' ' ||UPPER(c.STAGETABLECOLUMN), '  ,') 
        within GROUP (ORDER BY (c.STAGETABLENAME)) AS Column_List_exp
    FROM "DW"."CONTROL"."COLUMNDETAILS" c, "DW"."CONTROL"."SOURCESYSTEM" s WHERE 
    c.ACTIVEFLAG = 'TRUE'
    AND c.ISPSEUDONYMISED  = 'TRUE' AND c.SOURCESYSTEMID=s.SOURCESYSTEMID
    --AND c.SOURCESYSTEMID=1 
    GROUP BY c.SOURCESYSTEMID,c.STAGEDATABASENAME,c.STAGETABLENAME) b
    on a.STAGETABLENAME=b.STAGETABLENAME
	)
SELECT SOURCESYSTEMID,SOURCESYSTEMNAME,DBMS,SOURCEHOSTNAME,SOURCEPORTNUMBER,SOURCEUSERID,SOURCEPASSWORD,SOURCEDATABASENAME,
SOURCETIMEZONE,SOURCEJDBCDRIVER,SOURCECONNECTIONSTRING,SOURCECURRENTTIMESTAMP,STAGEDATABASENAME,ODSDATABASENAME,SOURCESYSTEM_ACTIVEFLAG,
SOURCESCHEMANAME,SOURCETABLENAME,SOURCECATALOGQUERY,STAGESCHEMANAME,STAGETABLENAME,ODSSCHEMANAME,ODSTABLENAME,STAGETYPE,LOADTYPE,LOADPROCESS_ACTIVEFLAG,
LOADPROCESS_NRTFLAG,WATERMARKCOLUMNNAME,WATERMARKDATATYPE,WATERMARKVALUE,ODS_PK,BACKUPSCHEMANAME,COLUMNLISTEXP,
ISRESTRICTED,RESTRICTEDTABLENAME,RESTRICTEDCOLUMNNAME,SOURCE_SQL,EXPRESSIONS,RESTRICTEDTABLE_RANK
 FROM (SELECT 
ss.sourcesystemid,
ss.sourcesystemname,
ss.dbms,
ss.sourcehostname,
ss.sourceportnumber,
ss.sourceuserid,
ss.sourcepassword,
ss.sourcedatabasename,
ss.sourcetimezone,
--ss.sourcecatalogquery,
CASE 
	--WHEN dbms='SQL SERVER' THEN 'Microsoft SQL Server'
	WHEN ss.dbms='SQL SERVER'	THEN 'SQL Server (Microsoft Driver)'
	WHEN ss.dbms='MYSQL' 		THEN 'MySQL'
	WHEN ss.dbms='ORACLE' 		THEN 'Oracle'
END AS SOURCEJDBCDRIVER,
CASE 
	WHEN ss.dbms='SQL SERVER' 	THEN 'jdbc:sqlserver://'||ss.sourcehostname||'\\'||ss.sourcedatabasename||':'||ss.sourceportnumber
	WHEN ss.dbms='MYSQL' 		THEN 'jdbc:mysql://'||ss.sourcehostname||':'||ss.sourceportnumber||'/'||ss.sourcedatabasename
	WHEN ss.dbms='ORACLE' 		THEN 'jdbc:oracle:thin:@'||ss.sourcehostname||':'||ss.sourceportnumber||':'||ss.sourcedatabasename
END AS SOURCECONNECTIONSTRING,
CASE 
	WHEN ss.dbms='SQL SERVER' THEN 'select convert(varchar, current_timestamp,120) TS;'
	WHEN ss.dbms='MYSQL' THEN 'select date_format(CURRENT_TIMESTAMP, ''%Y-%m-%d %H:%i:%s'') TS;'
	WHEN ss.dbms='ORACLE' THEN 'select to_char(current_timestamp,''YYYY-MM-DD HH24:MI:SS'') TS FROM dual;'
END AS SOURCEcurrenttimestamp,
ss.stagedatabasename,
ss.odsdatabasename,
ss.activeflag AS sourcesystem_activeflag,
lp.sourceschemaname,
lp.sourcetablename,
CASE 
	WHEN dbms='SQL SERVER' THEN 'select s.name as TABLE_SCHEMA, o.name as TABLE_NAME from sys.all_objects o inner join sys.schemas s on o.schema_id=s.schema_id where s.name = '''||lp.sourceschemaname||''' and o.type in (''U'');'
	WHEN dbms='MYSQL' THEN 'select o.TABLE_SCHEMA, o.TABLE_NAME from information_schema.TABLES o where o.table_schema='''||lp.sourceschemaname||''';'
	WHEN dbms='ORACLE' THEN 'select o.owner as TABLE_SCHEMA, o.OBJECT_NAME as TABLE_NAME from sys.all_objects o WHERE o.object_type = ''TABLE'' AND o.owner='''||lp.sourceschemaname||''';'
END AS SOURCECATALOGQUERY,
lp.stageschemaname,
lp.stagetablename,
lp.odsschemaname,
lp.odstablename,
lp.stagetype,
lp.loadtype,
lp.activeflag AS loadprocess_activeflag,
lp.nrtflag AS loadprocess_nrtflag,
lp.watermarkcolumnname,
lp.watermarkdatatype,
--lp.watermarklastvalue,
CASE 
	WHEN upper(ss.dbms)='ORACLE' AND upper(lp.stagetype) = 'INCREMENTAL' AND upper(lp.WATERMARKDATATYPE) ='TIMESTAMP' THEN 'TO_TIMESTAMP('||lp.WATERMARKLASTVALUE||', \'YYYY-MM-DD HH24:MI:SS\')' 
	ELSE lp.WATERMARKLASTVALUE 
END AS watermarkvalue,
lp.ods_pk,
ss.backupschemaname,
pcl.ColumnListExp,
lp.IsRestricted,
lp.RestrictedTablename,
lp.RestrictedColumnName,
lp.SOURCE_SQL,
lp.Expressions,
lp.RestrictedTable_Rank    
FROM dw.control.sourcesystem ss
LEFT OUTER JOIN control.loadprocess lp ON ss.sourcesystemid=lp.sourcesystemid
LEFT OUTER JOIN  PSEUDONYMISEDCOLUMNLISTEXP pcl
ON ss.sourcesystemid=pcl.sourcesystemid
AND ss.STAGEDATABASENAME=pcl.STAGEDATABASENAME
AND lp.STAGETABLENAME=pcl.STAGETABLENAME
      ) t	
GROUP BY SOURCESYSTEMID,SOURCESYSTEMNAME,DBMS,SOURCEHOSTNAME,SOURCEPORTNUMBER,SOURCEUSERID,SOURCEPASSWORD,SOURCEDATABASENAME,
SOURCETIMEZONE,SOURCEJDBCDRIVER,SOURCECONNECTIONSTRING,SOURCECURRENTTIMESTAMP,STAGEDATABASENAME,ODSDATABASENAME,SOURCESYSTEM_ACTIVEFLAG,
SOURCESCHEMANAME,SOURCETABLENAME,SOURCECATALOGQUERY,STAGESCHEMANAME,STAGETABLENAME,ODSSCHEMANAME,ODSTABLENAME,STAGETYPE,LOADTYPE,LOADPROCESS_ACTIVEFLAG,
LOADPROCESS_NRTFLAG,WATERMARKCOLUMNNAME,WATERMARKDATATYPE,WATERMARKVALUE,ODS_PK,BACKUPSCHEMANAME,COLUMNLISTEXP,
ISRESTRICTED,RESTRICTEDTABLENAME,RESTRICTEDCOLUMNNAME,SOURCE_SQL,EXPRESSIONS,RESTRICTEDTABLE_RANK
;


--------------START KEY SCHEMA FOR DW PROCESSING -------

CREATE OR REPLACE SCHEMA DW.KEY;

CREATE OR REPLACE SEQUENCE DW.KEY.SEQ_KEYMAP_ID START = 1 INCREMENT = 1;

CREATE OR REPLACE SEQUENCE DW.KEY.SEQ_CLIENT_ID  START = 1 INCREMENT = 1;

 

CREATE OR REPLACE TABLE DW.KEY.KEYMAP (

    KEYMAP_ID NUMBER(38,0) NOT NULL DEFAULT DW.KEY.SEQ_KEYMAP_ID.NEXTVAL,

    COLUMN_NAME_LIST ARRAY NOT NULL,

    PARENT_KEYMAP_ID NUMBER(38,0),

    SRC_SYSTEM_ID NUMBER(38,0),

    TABLE_CATALOG VARCHAR(255),

    TABLE_SCHEMA VARCHAR(255),

    TABLE_NAME VARCHAR(255),

    KEY_PRECEDENCE NUMBER(38,0),

    DW_SEQUENCE_NAME VARCHAR(255) NOT NULL,

    DW_KEY_NAME VARCHAR(255) NOT NULL,

    DW_TABLE_NAME VARCHAR(255) NOT NULL,

    DW_COLUMN_NAME VARCHAR(255) NOT NULL,

    NOTES VARCHAR(1000),

    FILTER_CRITERIA VARCHAR(16777216),

    DW_SRC_SYSTEM_ID NUMBER(38,0),

    DW_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),

    DW_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),

    DW_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),

    DW_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_KEYMAP PRIMARY KEY (KEYMAP_ID, COLUMN_NAME_LIST)

);

 

 


CREATE OR REPLACE TABLE DW.KEY.CLIENT (

KEYMAP_ID NUMBER(38,0) NOT NULL,

              COLUMN_VALUE_LIST ARRAY NOT NULL,

              CLIENT_ID NUMBER(38,0) NOT NULL,

              DW_SRC_SYSTEM_ID NUMBER(38,0) NOT NULL,

              DW_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),

              DW_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),

              DW_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),

              DW_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),

              CONSTRAINT PK_CLIENT PRIMARY KEY (KEYMAP_ID, COLUMN_VALUE_LIST)

);

 

 

 




--------------END KEY SCHEMA FOR DW PROCESSING ---------


-------AUDIT DB CREATION -------

CREATE OR REPLACE DATABASE AUDIT;

DROP  SCHEMA IF EXISTS AUDIT.PUBLIC;

CREATE OR REPLACE SCHEMA AUDIT.BASE;



CREATE OR REPLACE TABLE AUDIT.BASE.MATILLION_DETAIL (
	ID VARCHAR(2000) NOT NULL,
	TYPE VARCHAR(2000),
	JOBTIMESTAMP VARCHAR(2000),
	COMPONENTNAME VARCHAR(2000),
	STATE VARCHAR(2000),
	ROWCOUNT VARCHAR(2000),
	STARTTIME VARCHAR(2000),
	ENDTIME VARCHAR(2000),
	MESSAGE VARCHAR(2000),
	AUDIT_SRC_SYSTEM_ID VARCHAR(1024),
	AUDIT_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	AUDIT_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	AUDIT_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	AUDIT_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_MATILLION_DETAIL PRIMARY KEY (ID)
);
CREATE OR REPLACE TABLE AUDIT.BASE.MATILLION_LOG (
	ID NUMBER(38,0) NOT NULL,
	JOB_TYPE VARCHAR(1024),
	GROUPNAME VARCHAR(1024),
	PROJECTNAME VARCHAR(1024),
	VERSIONID NUMBER(38,0),
	VERSIONNAME VARCHAR(1024),
	ENVIRONMENTNAME VARCHAR(1024),
	JOBNAME VARCHAR(1024),
	JOB_STATE VARCHAR(250),
	JOB_ENQUEUEDTIME TIMESTAMP_LTZ(9),
	JOB_STARTTIME TIMESTAMP_LTZ(9),
	JOB_ENDTIME TIMESTAMP_LTZ(9),
	JOB_MESSAGE VARCHAR(1024),
	COMPONENT_TYPE VARCHAR(1024),
	JOB_TIMESTAMP TIMESTAMP_LTZ(9),
	COMPONENT_NAME VARCHAR(1024),
	COMPONENT_STATE VARCHAR(256),
	ROWCOUNT NUMBER(38,0),
	COMPONENT_STARTTIME TIMESTAMP_LTZ(9),
	COMPONENT_ENDTIME TIMESTAMP_LTZ(9),
	COMPONENT_MESSAGE VARCHAR(16777216),
	AUDIT_SRC_SYSTEM_ID VARCHAR(1024),
	AUDIT_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	AUDIT_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	AUDIT_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	AUDIT_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_MATILLION_LOG PRIMARY KEY (ID)
);

CREATE OR REPLACE TABLE AUDIT.BASE.MATILLION_SUMMARY (
	ID VARCHAR(2000) NOT NULL,
	TYPE VARCHAR(2000),
	GROUPNAME VARCHAR(2000),
	PROJECTNAME VARCHAR(2000),
	VERSIONID VARCHAR(2000),
	VERSIONNAME VARCHAR(2000),
	ENVIRONMENTNAME VARCHAR(2000),
	JOBNAME VARCHAR(2000),
	STATE VARCHAR(2000),
	ENQUEUEDTIME VARCHAR(2000),
	STARTTIME VARCHAR(2000),
	ENDTIME VARCHAR(2000),
	MESSAGE VARCHAR(2000),
	AUDIT_SRC_SYSTEM_ID VARCHAR(1024),
	AUDIT_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	AUDIT_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	AUDIT_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	AUDIT_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_MATILLION_SUMMARY PRIMARY KEY (ID)
);

/*
CREATE OR REPLACE TABLE AUDIT.BASE.STG_MATILLION_DETAIL (
	"ID" VARCHAR(2000),
	"TYPE" VARCHAR(2000),
	"JOBTIMESTAMP" VARCHAR(2000),
	"COMPONENTNAME" VARCHAR(2000),
	"STATE" VARCHAR(2000),
	"ROWCOUNT" VARCHAR(2000),
	"STARTTIME" VARCHAR(2000),
	"ENDTIME" VARCHAR(2000),
	"MESSAGE" VARCHAR(2000),
	"SINCE" VARCHAR(2000)
);
CREATE OR REPLACE TABLE AUDIT.BASE.STG_MATILLION_SUMMARY (
	"ID" VARCHAR(2000),
	"TYPE" VARCHAR(2000),
	"GROUPNAME" VARCHAR(2000),
	"PROJECTNAME" VARCHAR(2000),
	"VERSIONID" VARCHAR(2000),
	"VERSIONNAME" VARCHAR(2000),
	"ENVIRONMENTNAME" VARCHAR(2000),
	"JOBNAME" VARCHAR(2000),
	"STATE" VARCHAR(2000),
	"ENQUEUEDTIME" VARCHAR(2000),
	"STARTTIME" VARCHAR(2000),
	"ENDTIME" VARCHAR(2000),
	"MESSAGE" VARCHAR(2000)
);
*/

------- AUDIT DB END -----


--DATASCIENCE DB CREATION - START --

CREATE OR REPLACE DATABASE DATASCIENCE;

DROP SCHEMA IF EXISTS DATASCIENCE.PUBLIC;

CREATE OR REPLACE SCHEMA DATASCIENCE.DBO;

--DATASCIENCE DB CREATION -- END--


--STAGE DB REFERENCE CREATION - START --

CREATE OR REPLACE DATABASE STG_REFERENCE;

DROP SCHEMA IF EXISTS STG_REFERENCE.PUBLIC;

CREATE OR REPLACE SCHEMA STG_REFERENCE.BASE;

--STAGE DB CREATION - END --


--ODS DB REFERENCE CREATION - START --

CREATE OR REPLACE DATABASE ODS_REFERENCE;

DROP SCHEMA IF EXISTS ODS_REFERENCE.PUBLIC;

CREATE OR REPLACE SCHEMA ODS_REFERENCE.BASE;

--ODS REF DB CREATION - END --