CREATE or REPLACE SCHEMA "DW"."SIS";

--------
CREATE OR REPLACE VIEW DW.SIS.V_ALARM_CODES as 
SELECT ALARM_CODE_ID, SHORT_DESCRIPTION, DESCRIPTION, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP 
FROM ODS_GRS_NO.DBO.ALARM_CODES;
-----

CREATE OR REPLACE VIEW DW.SIS.V_ALARM_GROUP as 
SELECT ALARM_GROUP_ID, DESCRIPTION, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ALARM_GROUP;
------

CREATE OR REPLACE VIEW DW.SIS.V_ASSIGNMENT_TYPE as 
SELECT ASSIGNMENT_TYPE_ID, DESCRIPTION, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.ASSIGNMENT_TYPE;
------

CREATE OR REPLACE VIEW DW.SIS.V_COMMITMENT as 
SELECT COMMITMENT_ID, DESCRIPTION, INSTRUCTION, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.COMMITMENT;
------

CREATE OR REPLACE VIEW DW.SIS.V_CONTRACT_PART as 
SELECT CONTRACT_PART_ID, CONTRACT_PART_NO, CUST_OBJ_ID, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTRACT_PART;
------

CREATE OR REPLACE VIEW DW.SIS.V_CONTR_PART_VER as 
SELECT CONTRACT_ID, CONTRACT_PART_ID, VERSION_FROM, PROFITCENTER_ID, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTR_PART_VER;
------

CREATE OR REPLACE VIEW DW.SIS.V_CONTRACT_TYPE as 
SELECT CONTRACT_TYPE_ID, DESCRIPTION, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTRACT_TYPE;
------

CREATE OR REPLACE VIEW DW.SIS.V_CONTRACT as 
SELECT CONTRACT_ID, CONTRACT_NO, CUSTOMER_ID, MONTHLY_INC_ALL, CONTACT, INVOICE_LATEST, INVOICED_TO, VALIDTO, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CONTRACT;
------

CREATE OR REPLACE VIEW DW.SIS.V_CUST_CUST_OBJECT as 
SELECT CUST_OBJ_ID, CUSTOMER_ID, DATEFROM, DATETO, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CUST_CUST_OBJECT;
------

CREATE OR REPLACE VIEW DW.SIS.V_CUSTOMER_OBJECT AS 
SELECT CUST_OBJ_NO, CUST_OBJ_ID, PROFITCENTER_ID, "NAME", ADDRESS, POSTDELIVERY_ADDRESS, POSTCODE, ADDRESS_2, POSTADDRESS, 
           GEO_LAT AS LATITUDE,GEO_LONG AS LONGITUDE, CHANGE_DATE, INSERT_DATE, TERMINATE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CUSTOMER_OBJECT;
------

CREATE OR REPLACE VIEW DW.SIS.V_CUSTOMER as 
SELECT CUSTOMER_ID, NAME_SEARCH, CUSTOMER_TYPE_ID, CUSTOMER_NO, NAME_1, ADDRESS, POSTCODE, POSTADDRESS, VALIDTO, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.CUSTOMER;
------

CREATE OR REPLACE VIEW DW.SIS.V_GD as 
SELECT GD_ID, GD_NO, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP 
FROM ODS_GRS_NO.DBO.GD;
------

CREATE OR REPLACE VIEW DW.SIS.V_LOCATION_MARK as 
SELECT LOCATION_MARK_ID, BARCODE, "POSITION", POSITION_GUARD_INFO, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.LOCATION_MARK;
------

CREATE OR REPLACE VIEW DW.SIS.V_LOCATION_OBJECT as 
SELECT PROD_OBJ_ID, LOC_OBJ_ID, DESCRIPTION, CHANGE_DATE, INSERT_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP 
FROM ODS_GRS_NO.DBO.LOCATION_OBJECT;
------

CREATE OR REPLACE VIEW DW.SIS.V_PRODUCTION_OBJECT as 
SELECT PROD_OBJ_ID, PROD_OBJ_NO, DESCRIPTION, ADDRESS, CHANGE_DATE, INSERT_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.PRODUCTION_OBJECT;
------

CREATE OR REPLACE VIEW DW.SIS.V_PROFITCENTER as 
SELECT PROFITCENTER_ID, PROFITCENTER_NO, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP 
FROM ODS_GRS_NO.DBO.PROFITCENTER;
------

CREATE OR REPLACE VIEW DW.SIS.V_REPORT_MARK as 
SELECT REPORT_MARK_ID, REPORT_LABEL, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP 
FROM ODS_GRS_NO.DBO.REPORT_MARK;
------

CREATE OR REPLACE VIEW DW.SIS.V_PROCESSED_TRANSACTIONS as 
SELECT LOGG_ID, TRANS_ID, SUB_ID, GD_ID, PROD_OBJ_ID, LOC_OBJ_ID, MULTIPLICATION_FACTOR, REPORT_NOTES, COMMITMENT_ID, INSERT_DATE, CHANGE_DATE, "POSITION", BARCODE_TIME, BARCODE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.PROCESSED_TRANSACTIONS;
------

CREATE OR REPLACE VIEW DW.SIS.V_TEMP_TRANSACTIONS as 
SELECT LOGG_ID, TRANS_ID, BARCODE_TIME, BARCODE_NO, INSERT_DATE, CHANGE_DATE, LATITUDE, LONGITUDE, GPSTIMESTAMP, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.TEMP_TRANSACTIONS;

------additionale tables----
CREATE OR REPLACE VIEW DW.SIS.V_GCS_Export_ERP_Call_Out_Guards as 
SELECT BASE_LOCATION_NUMBER, COST_CENTRE, ARRIVAL_TIME, DEPARTURE_TIME, ELAPSED_TIME, GUARD_TYPE, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_Export_ERP_Call_Out_Guards;
------

CREATE OR REPLACE VIEW DW.SIS.V_GCS_Export_ERP_Call_Outs as 
SELECT ALARM_NUMBER, CASE_NUMBER, ALARM_CENTER_NAME, ALARM_CENTER_REFERENCE, CUSTOMER_NAME_1, ALARM_TYPE, ALARM_TYPE_TEXT, ALARM_TIME, ALARM_REACH_TIME, BUILDING_NAME, BUILDING_LOCATION, BUILDING_SECTION, BUILDING_ADDRESS, FREE_TEXT_FROM_GUARD, FREE_TEXT_FROM_OPERATOR, ALARM_ISSUE_CODE, ALARM_ISSUE_DESCRIPTION, MEASURES_CODE, MEASURES_TEXT, GUARD_SECTION, INSERT_DATE, CHANGE_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.GCS_Export_ERP_Call_Outs;
------

CREATE OR REPLACE VIEW DW.SIS.V_GRS_AddOnInfo as 
SELECT CASE_NUMBER, CUST_OBJ_NO, CUSTOMER_NO, GRSR_EVENT_ID, CHANGE_DATE, INSERT_DATE, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP 
FROM ODS_GRS_NO.DBO.GRS_AddOnInfo;
--------

CREATE OR REPLACE VIEW DW.SIS.V_xPROCESSED_BARCODES as 
SELECT LOGG_ID, TRANS_ID, SUB_ID, BARCODE_DATE, BARCODE_TIME, BARCODE_NO, BARCODE_GROUP, BARCODE_TYPE, LOC_MARK_TYPE, REQUIRED, EMPLOYEE_ID, GD_ID, VALID_ASSOCIATION, COMMITMENT_ID, DAY_T_ID, VERSION_FROM, ASSIGNM_TIMEFROM, CE_VALID_ASSOCIATION, CE_COMMITMENT_ID, CE_EXCEPTION, CE_DAY_T_ID, CE_DATEFROM, CE_TIMEFROM, REQ_CORRECTION_TYPE, ERROR_FLAG, NOTES, ASSOCIATION_NORMAL, ASSOCIATION_CE, LOCATION_MARK_ID, PROD_OBJ_ID, LOC_OBJ_ID, "POSITION", "ACTION", INSERT_DATE, INSERT_USER, CHANGE_DATE, CHANGE_USER, ROWID, REPORT_NOTES, EMPLOYEE_NO, FIRSTNAME, LASTNAME, MULTIPLICATION_FACTOR, TIME_CONSUMPTION, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.XPROCESSED_BARCODES;
--------------------

CREATE OR REPLACE VIEW DW.SIS.V_xPROCESSED_TRANSACTIONS as 
SELECT LOGG_ID, TRANS_ID, SUB_ID, BARCODE_DATE, BARCODE_TIME, BARCODE_NO, BARCODE_GROUP, BARCODE_TYPE, LOC_MARK_TYPE, REQUIRED, EMPLOYEE_ID, GD_ID, VALID_ASSOCIATION, COMMITMENT_ID, DAY_T_ID, VERSION_FROM, ASSIGNM_TIMEFROM, CE_VALID_ASSOCIATION, CE_COMMITMENT_ID, CE_EXCEPTION, CE_DAY_T_ID, CE_DATEFROM, CE_TIMEFROM, REQ_CORRECTION_TYPE, ERROR_FLAG, NOTES, ASSOCIATION_NORMAL, ASSOCIATION_CE, LOCATION_MARK_ID, PROD_OBJ_ID, LOC_OBJ_ID, "POSITION", "ACTION", INSERT_DATE, INSERT_USER, CHANGE_DATE, CHANGE_USER, ROWID, REPORT_NOTES, EMPLOYEE_NO, FIRSTNAME, LASTNAME, MULTIPLICATION_FACTOR, TIME_CONSUMPTION, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.XPROCESSED_TRANSACTIONS;
-----------------------

CREATE OR REPLACE VIEW DW.SIS.V_xREPORT_MARK as 
SELECT REPORT_MARK_ID, REP_MARK_TYPE_ID, BARCODE, REPORT_LABEL, ACTIVITY_CODE, TIMELIMIT_CODE, INSERT_DATE, INSERT_USER, CHANGE_DATE, CHANGE_USER, ROWID, REPORT_MARK_VERSION, RISK_LEVEL, "SYSTEM", REPORT_FOLDER_LABEL, STATISTICS_MEMBER, CODE, REPORT_LABEL_2, REPORT_MARK_SET_ONLY, SBA, CULTURE_ID, ODS_SRC_SYSTEM_ID, ODS_CREATEDBY, ODS_MODIFIEDBY, ODS_MODIFIEDBY_TIMESTAMP, ODS_CREATEDBY_TIMESTAMP
FROM ODS_GRS_NO.DBO.XREPORT_MARK;
