CREATE OR REPLACE DATABASE ODS_REFERENCE;

CREATE OR REPLACE SCHEMA ODS_REFERENCE.BASE;

CREATE OR REPLACE TABLE ODS_REFERENCE.BASE.NETWORK_POLICY (
	IP_RANGE VARCHAR(19) NOT NULL,
	CATEGORY VARCHAR(200),
	NOTES VARCHAR(1000),
	DEV_ACTIVEFLAG BOOLEAN,
	TEST_ACTIVEFLAG BOOLEAN,
	PROD_ACTIVEFLAG BOOLEAN,
	ODS_SRC_SYSTEM_ID NUMBER(38,0) NOT NULL,
	ODS_CREATEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_CREATEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	ODS_MODIFIEDBY VARCHAR(255) NOT NULL DEFAULT CURRENT_USER(),
	ODS_MODIFIEDBY_TIMESTAMP TIMESTAMP_LTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	CONSTRAINT PK_NETWORK_POLICY PRIMARY KEY (IP_RANGE)
);