--USE SECURITYADMIN
--GRANT ROLE 
--GRANT SELECT ON VIEWS to ROLE
--GRANT ROLE TO USERS 

USE ROLE SECURITYADMIN;
REVOKE IMPORTED  PRIVILEGES ON DATABASE  SNOWFLAKE_SAMPLE_DATA FROM ROLE PUBLIC;
GRANT USAGE ON DATABASE DW TO ROLE SISEU_DATAREADER;
GRANT USAGE ON SCHEMA DW.SIS TO ROLE SISEU_DATAREADER; --Confirm again USAGE ON SCHEMA exists or not if not run again post below REVOKE USAGEs are accomplishes

--GRANT SELECT ON VIEWS to ROLE
GRANT SELECT ON VIEW DW.SIS.V_ALARM_CODES to Role SISEU_DATAREADER;
-----
GRANT SELECT ON VIEW DW.SIS.V_ALARM_GROUP to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_ASSIGNMENT_TYPE to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_COMMITMENT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_CONTRACT_PART to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_CONTR_PART_VER to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_CONTRACT_TYPE to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_CONTRACT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_CUST_CUST_OBJECT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_CUSTOMER_OBJECT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_CUSTOMER to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_GD to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_LOCATION_MARK to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_LOCATION_OBJECT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_PRODUCTION_OBJECT to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_PROFITCENTER to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_REPORT_MARK to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_PROCESSED_TRANSACTIONS to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_TEMP_TRANSACTIONS to Role SISEU_DATAREADER;
------additionale tables----
GRANT SELECT ON VIEW DW.SIS.V_GCS_Export_ERP_Call_Out_Guards to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_GCS_Export_ERP_Call_Outs to Role SISEU_DATAREADER;
------
GRANT SELECT ON VIEW DW.SIS.V_GRS_AddOnInfo to Role SISEU_DATAREADER;
--------
GRANT SELECT ON VIEW DW.SIS.V_xPROCESSED_BARCODES to Role SISEU_DATAREADER;
--------------------
GRANT SELECT ON VIEW DW.SIS.V_xPROCESSED_TRANSACTIONS to Role SISEU_DATAREADER;
-----------------------
GRANT SELECT ON VIEW DW.SIS.V_xREPORT_MARK to Role SISEU_DATAREADER;

------------------------------------------------------------------------

--GRANT ROLE TO USERS 

GRANT ROLE SISEU_DATAREADER TO USER "SISEU_DS";
------------------------------------
GRANT ROLE SISEU_DATAREADER TO USER "kriti.paliwal";

GRANT ROLE SISEU_DATAREADER TO USER "zachary.peterson";

GRANT ROLE SISEU_DATAREADER TO USER "shuainan.zhao";

GRANT ROLE SISEU_DATAREADER TO USER "anlai.gao";

GRANT ROLE SISEU_DATAREADER TO USER "sebastian.nyberg";

GRANT ROLE SISEU_DATAREADER TO USER "johannes.skog";

GRANT ROLE SISEU_DATAREADER TO USER "malin.lundqvist";

GRANT ROLE SISEU_DATAREADER TO USER "henrik.gronholtjensen";

GRANT ROLE SISEU_DATAREADER TO USER "johannes.skog";

GRANT ROLE SISEU_DATAREADER TO USER "malin.lundqvist";

GRANT ROLE SISEU_DATAREADER TO USER "henrik.gronholtjensen";

GRANT ROLE SISEU_DATAREADER TO USER "jonas.alstrom.mortin";

GRANT ROLE SISEU_DATAREADER TO USER "daniel.sandberg";

GRANT ROLE SISEU_DATAREADER TO USER "carl.frolund";

GRANT ROLE SISEU_DATAREADER TO USER "henrik.gronholtjensen";

GRANT ROLE SISEU_DATAREADER TO USER "jonas.alstrom.mortin";

GRANT ROLE SISEU_DATAREADER TO USER "daniel.sandberg";



