---GRANT and REVOKE

USE ROLE SECURITYADMIN;

--REVOKE IMPORTED  PRIVILEGES ON DATABASE  SNOWFLAKE_SAMPLE_DATA FROM ROLE PUBLIC;
GRANT USAGE ON DATABASE DW TO ROLE EU_MYSECURITAS;
GRANT USAGE ON SCHEMA DW.SIS TO ROLE EU_MYSECURITAS;

----Granting all Objects under DW.SISv      (TEMPORARY COMMENTED)-ON HOLD
--GRANT SELECT ON ALL VIEWS IN SCHEMA DW.SIS TO ROLE EU_MYSECURITAS;

----GRANT ROLE TO USERS
GRANT ROLE EU_MYSECURITAS TO USER "xiaohu.chen";
GRANT ROLE EU_MYSECURITAS TO USER "timo.halttunen";
GRANT ROLE EU_MYSECURITAS TO USER "johan.nedin";
GRANT ROLE EU_MYSECURITAS TO USER "pawel.grudzien";