--USE SECURITYADMIN
--GRANT ROLE 
--GRANT SELECT ON VIEWS to ROLE
--GRANT ROLE TO USERS 

USE ROLE SECURITYADMIN;
REVOKE IMPORTED  PRIVILEGES ON DATABASE  SNOWFLAKE_SAMPLE_DATA FROM ROLE PUBLIC;
GRANT USAGE ON DATABASE DW TO ROLE SISEU_DATAREADER;
GRANT USAGE ON SCHEMA DW.SIS TO ROLE SISEU_DATAREADER; --Confirm again USAGE ON SCHEMA exists or not if not run again

GRANT ALL ON DATABASE DATASCIENCE TO ROLE SISEU_DATASCIENCE;
GRANT ALL ON SCHEMA DATASCIENCE.DBO TO ROLE SISEU_DATASCIENCE;

----Granting all Objects under DW.SIS
GRANT SELECT ON ALL VIEWS IN SCHEMA DW.SIS TO ROLE SISEU_DATAREADER;

------------------------------------------------------------------------

--GRANT ROLE TO USERS 

GRANT ROLE SISEU_DATAREADER TO USER "SISEU_DS";
GRANT ROLE SISEU_DATASCIENCE TO USER "SISEU_DS";

------------------------------------
GRANT ROLE SISEU_DATAREADER TO USER "kriti.paliwal";
GRANT ROLE SISEU_DATASCIENCE TO USER "kriti.paliwal";


GRANT ROLE SISEU_DATAREADER TO USER "zachary.peterson";
GRANT ROLE SISEU_DATASCIENCE TO USER "zachary.peterson";

GRANT ROLE SISEU_DATAREADER TO USER "shuainan.zhao";
GRANT ROLE SISEU_DATASCIENCE TO USER "shuainan.zhao";

GRANT ROLE SISEU_DATAREADER TO USER "anlai.gao";
GRANT ROLE SISEU_DATASCIENCE TO USER "anlai.gao";

GRANT ROLE SISEU_DATAREADER TO USER "sebastian.nyberg";
GRANT ROLE SISEU_DATASCIENCE TO USER "sebastian.nyberg";

GRANT ROLE SISEU_DATAREADER TO USER "johannes.skog";
GRANT ROLE SISEU_DATASCIENCE TO USER "johannes.skog";

GRANT ROLE SISEU_DATAREADER TO USER "malin.lundqvist";
GRANT ROLE SISEU_DATASCIENCE TO USER "malin.lundqvist";

GRANT ROLE SISEU_DATAREADER TO USER "henrik.gronholtjensen";
GRANT ROLE SISEU_DATASCIENCE TO USER "henrik.gronholtjensen";

GRANT ROLE SISEU_DATAREADER TO USER "johannes.skog";
GRANT ROLE SISEU_DATASCIENCE TO USER "johannes.skog";

GRANT ROLE SISEU_DATAREADER TO USER "malin.lundqvist";
GRANT ROLE SISEU_DATASCIENCE TO USER "malin.lundqvist";

GRANT ROLE SISEU_DATAREADER TO USER "henrik.gronholtjensen";
GRANT ROLE SISEU_DATASCIENCE TO USER "henrik.gronholtjensen";

GRANT ROLE SISEU_DATAREADER TO USER "jonas.alstrom.mortin";
GRANT ROLE SISEU_DATASCIENCE TO USER "jonas.alstrom.mortin";

GRANT ROLE SISEU_DATAREADER TO USER "daniel.sandberg";
GRANT ROLE SISEU_DATASCIENCE TO USER "daniel.sandberg";

GRANT ROLE SISEU_DATAREADER TO USER "carl.frolund";
GRANT ROLE SISEU_DATASCIENCE TO USER "carl.frolund";

GRANT ROLE SISEU_DATAREADER TO USER "henrik.gronholtjensen";
GRANT ROLE SISEU_DATASCIENCE TO USER "henrik.gronholtjensen";

GRANT ROLE SISEU_DATAREADER TO USER "jonas.alstrom.mortin";
GRANT ROLE SISEU_DATASCIENCE TO USER "jonas.alstrom.mortin";

GRANT ROLE SISEU_DATAREADER TO USER "daniel.sandberg";
GRANT ROLE SISEU_DATASCIENCE TO USER "daniel.sandberg";
