USE ROLE SECURITYADMIN;
GRANT ALL PRIVILEGES ON DATABASE DW TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DW TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE DW TO ROLE DATA_LOADER;

GRANT ALL PRIVILEGES ON SCHEMA DW.BASE TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON future TABLES in schema DW.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL TABLES in schema DW.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON future SEQUENCES in schema DW.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES in schema DW.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA DW.BASE TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA DW.BASE TO ROLE DATA_LOADER;

GRANT ALL PRIVILEGES ON SCHEMA DW.CONTROL TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON future VIEWS in schema DW.CONTROL to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL VIEWS in schema DW.CONTROL to role DATA_LOADER;
GRANT ALL PRIVILEGES ON future TABLES in schema DW.CONTROL to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL TABLES in schema DW.CONTROL to role DATA_LOADER;
GRANT ALL PRIVILEGES ON future SEQUENCES in schema DW.CONTROL to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES in schema DW.CONTROL to role DATA_LOADER;

GRANT ALL PRIVILEGES ON SCHEMA DW.KEY TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON future VIEWS in schema DW.KEY to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL VIEWS in schema DW.KEY to role DATA_LOADER;
GRANT ALL PRIVILEGES ON future TABLES in schema DW.KEY to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL TABLES in schema DW.KEY to role DATA_LOADER;
GRANT ALL PRIVILEGES ON future SEQUENCES in schema DW.KEY to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES in schema DW.KEY to role DATA_LOADER;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA DW.FUNCTION TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA DW.FUNCTION TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA DW.FUNCTION TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA DW.FUNCTION TO ROLE DATA_LOADER;

--------

GRANT ALL PRIVILEGES ON DATABASE STG_REFERENCE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE STG_REFERENCE TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE STG_REFERENCE TO ROLE DATA_LOADER;

GRANT ALL PRIVILEGES ON SCHEMA STG_REFERENCE.BASE TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON future TABLES in schema STG_REFERENCE.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL TABLES in schema STG_REFERENCE.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON future SEQUENCES in schema STG_REFERENCE.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES in schema STG_REFERENCE.BASE to role DATA_LOADER;

-------
GRANT ALL PRIVILEGES ON DATABASE ODS_REFERENCE TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ODS_REFERENCE TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE ODS_REFERENCE TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON SCHEMA ODS_REFERENCE.BASE TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON future SEQUENCES in schema ODS_REFERENCE.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES in schema ODS_REFERENCE.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON future TABLES in schema ODS_REFERENCE.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL TABLES in schema ODS_REFERENCE.BASE to role DATA_LOADER;

GRANT ALL PRIVILEGES ON DATABASE AUDIT TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE AUDIT TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE AUDIT TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON SCHEMA AUDIT.BASE TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON future SEQUENCES in schema AUDIT.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES in schema AUDIT.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON future TABLES in schema AUDIT.BASE to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL TABLES in schema AUDIT.BASE to role DATA_LOADER;


GRANT ALL PRIVILEGES ON DATABASE ODS_GRS_NO TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ODS_GRS_NO TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE ODS_GRS_NO TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON SCHEMA ODS_GRS_NO.DBO TO ROLE DATA_LOADER;
GRANT USAGE ON SCHEMA ODS_GRS_NO.DBO TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON future SEQUENCES in schema ODS_GRS_NO.DBO to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES in schema ODS_GRS_NO.DBO to role DATA_LOADER;
GRANT ALL PRIVILEGES ON future TABLES in schema ODS_GRS_NO.DBO to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL TABLES in schema ODS_GRS_NO.DBO to role DATA_LOADER;

GRANT ALL PRIVILEGES ON DATABASE STG_GRS_NO TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE STG_GRS_NO TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE STG_GRS_NO TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON SCHEMA STG_GRS_NO.DBO TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON future SEQUENCES in schema STG_GRS_NO.DBO to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES in schema STG_GRS_NO.DBO to role DATA_LOADER;
GRANT ALL PRIVILEGES ON future TABLES in schema STG_GRS_NO.DBO to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL TABLES in schema STG_GRS_NO.DBO to role DATA_LOADER;

-----Views should be seen by dataloader ----

GRANT ALL PRIVILEGES ON DATABASE DW TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE DW TO ROLE SYSADMIN;
GRANT USAGE ON DATABASE DW TO ROLE DATA_LOADER;

GRANT ALL PRIVILEGES ON SCHEMA DATAMART.RISKPREDICTION TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN SCHEMA DATAMART.RISKPREDICTION TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN SCHEMA DATAMART.RISKPREDICTION TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON SCHEMA DATAMART.MYSECURITAS TO ROLE DATA_LOADER;
GRANT ALL PRIVILEGES ON future VIEWS in schema DATAMART.MYSECURITAS to role DATA_LOADER;
GRANT ALL PRIVILEGES ON ALL VIEWS in schema DATAMART.MYSECURITAS to role DATA_LOADER;
---- To be deleted ------
