

CREATE TABLE ALARM_CODES(
    ALARM_CODE_ID               INTEGER           NOT NULL,
    SHORT_DESCRIPTION           VARCHAR(4000),
    DESCRIPTION                 VARCHAR(4000),
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_ALARM_CODES PRIMARY KEY (ALARM_CODE_ID)
)
; 


CREATE TABLE ALARM_GROUP(
    ALARM_GROUP_ID              INTEGER           NOT NULL,
    DESCRIPTION                 VARCHAR(4000),
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_ALARM_GROUP PRIMARY KEY (ALARM_GROUP_ID)
)
;

CREATE or replace TABLE ASSIGNMENT_TYPE(
    ASSIGNMENT_TYPE_ID          INTEGER           NOT NULL,
    DESCRIPTION                 VARCHAR(4000),
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_ASSIGNMENT_TYPE PRIMARY KEY (ASSIGNMENT_TYPE_ID)
)
;


CREATE TABLE COMMITMENT(
    COMMITMENT_ID               INTEGER    NOT NULL,
    DESCRIPTION                 VARCHAR(4000),
    INSTRUCTION                 VARCHAR(4000),
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
      CONSTRAINT PK_COMMITMENT PRIMARY KEY (COMMITMENT_ID)
)
;

CREATE TABLE CONTR_PART_VER(
    CONTRACT_ID                 INTEGER           NOT NULL,
    CONTRACT_PART_ID            INTEGER           NOT NULL,
    VERSION_FROM                DATE              NOT NULL,
    PROFITCENTER_ID             INTEGER,
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_CONTR_PART_VER PRIMARY KEY (CONTRACT_ID, CONTRACT_PART_ID, VERSION_FROM)
)
;

CREATE TABLE CONTRACT(
    CONTRACT_ID                 INTEGER           NOT NULL,
    CONTRACT_NO                 VARCHAR(4000),
    CUSTOMER_ID                 INTEGER,
    MONTHLY_INC_ALL             DECIMAL(19, 4),
    CONTACT                     VARCHAR(4000),
    INVOICE_LATEST              DATE,
    INVOICED_TO                 DATE,
    VALIDTO                     DATE,
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_CONTRACT PRIMARY KEY (CONTRACT_ID)
)
;

CREATE TABLE CONTRACT_PART(
    CONTRACT_PART_ID            INTEGER           NOT NULL,
    CONTRACT_PART_NO            VARCHAR(4000),
    CUST_OBJ_ID                 INTEGER,
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
   CONSTRAINT PK_CONTRACT_PART PRIMARY KEY (CONTRACT_PART_ID)
)
;


CREATE TABLE CONTRACT_TYPE(
    CONTRACT_TYPE_ID            INTEGER           NOT NULL,
    DESCRIPTION                 VARCHAR(4000),
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_CONTRACT_TYPE PRIMARY KEY (CONTRACT_TYPE_ID)
)
;

CREATE TABLE CUST_CUST_OBJECT(
    CUST_OBJ_ID                 INTEGER           NOT NULL,
    CUSTOMER_ID                 INTEGER           NOT NULL,
    DATEFROM                    DATE              NOT NULL,
    DATETO                      DATE,
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_CUST_CUST_OBJECT PRIMARY KEY (CUST_OBJ_ID, CUSTOMER_ID, DATEFROM)
)
;

CREATE TABLE CUSTOMER(
    CUSTOMER_ID                 INTEGER           NOT NULL,
    NAME_SEARCH                 VARCHAR(4000),
    CUSTOMER_TYPE_ID            INTEGER,
    CUSTOMER_NO                 VARCHAR(4000),
    NAME_1                      VARCHAR(4000),
    ADDRESS                     VARCHAR(4000),
    POSTCODE                    VARCHAR(4000),
    POSTADDRESS                 VARCHAR(4000),
    VALIDTO                     DATE,
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE CUSTOMER_OBJECT(
    CUST_OBJ_NO                 VARCHAR(4000),
    CUST_OBJ_ID                 INTEGER           NOT NULL,
    PROFITCENTER_ID             VARCHAR(4000),
    NAME                        VARCHAR(4000),
    ADDRESS                     VARCHAR(4000),
    POSTDELIVERY_ADDRESS        VARCHAR(4000),
    POSTCODE                    VARCHAR(4000),
    ADDRESS_2                   VARCHAR(4000),
    POSTADDRESS                 VARCHAR(4000),
    CHANGE_DATE                 TIMESTAMP,
    INSERT_DATE                 TIMESTAMP,
    TERMINATE_DATE              DATE,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_CUSTOMER_OBJECT PRIMARY KEY (CUST_OBJ_ID)
)
;

CREATE TABLE GD(
    GD_ID                       INTEGER           NOT NULL,
    GD_NO                       VARCHAR(4000),
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_GD PRIMARY KEY (GD_ID)
)
;



CREATE TABLE LOCATION_MARK(
    LOCATION_MARK_ID            INTEGER           NOT NULL,
    BARCODE                     VARCHAR(4000),
    POSITION                    VARCHAR(4000),
    POSITION_GUARD_INFO         VARCHAR(4000),
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_LOCATION_MARK PRIMARY KEY (LOCATION_MARK_ID)
)
;


CREATE TABLE LOCATION_OBJECT(
    PROD_OBJ_ID                 INTEGER           NOT NULL,
    LOC_OBJ_ID                  INTEGER           NOT NULL,
    DESCRIPTION                 VARCHAR(4000),
    CHANGE_DATE                 TIMESTAMP,
    INSERT_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_LOCATION_OBJECT PRIMARY KEY (PROD_OBJ_ID, LOC_OBJ_ID)
)
;



CREATE TABLE PROCESSED_TRANSACTIONS(
    LOGG_ID                     INTEGER           NOT NULL,
    TRANS_ID                    INTEGER           NOT NULL,
    SUB_ID                      INTEGER           NOT NULL,
    GD_ID                       INTEGER,
    PROD_OBJ_ID                 INTEGER,
    LOC_OBJ_ID                  INTEGER,
    MULTIPLICATION_FACTOR       INTEGER,
    REPORT_NOTES                VARCHAR(4000),
    COMMITMENT_ID               INTEGER,
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    POSITION                    VARCHAR(4000),
    BARCODE_TIME                TIMESTAMP,
    BARCODE_DATE                TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_PROCESSED_TRANSACTIONS PRIMARY KEY (LOGG_ID, TRANS_ID, SUB_ID)
)
;

CREATE TABLE PRODUCTION_OBJECT(
    PROD_OBJ_ID                 INTEGER           NOT NULL,
    PROD_OBJ_NO                 VARCHAR(4000),
    DESCRIPTION                 VARCHAR(4000),
    ADDRESS                     VARCHAR(4000),
    CHANGE_DATE                 TIMESTAMP,
    INSERT_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_PRODUCTION_OBJECT PRIMARY KEY (PROD_OBJ_ID)
)
;


CREATE TABLE PROFITCENTER(
    PROFITCENTER_ID             INTEGER           NOT NULL,
    PROFITCENTER_NO             VARCHAR(4000),
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_PROFITCENTER PRIMARY KEY (PROFITCENTER_ID)
)
;

CREATE TABLE REPORT_MARK(
    REPORT_MARK_ID              INTEGER           NOT NULL,
    REPORT_LABEL                VARCHAR(4000),
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_REPORT_MARK PRIMARY KEY (REPORT_MARK_ID)
)
;

CREATE TABLE TEMP_TRANSACTIONS(
    LOGG_ID                     INTEGER           NOT NULL,
    TRANS_ID                    INTEGER           NOT NULL,
    BARCODE_TIME                TIMESTAMP,
    BARCODE_NO                  VARCHAR(4000),
    INSERT_DATE                 TIMESTAMP,
    CHANGE_DATE                 TIMESTAMP,
    LATITUDE                    DECIMAL(18, 0),
    LONGITUDE                   DECIMAL(18, 0),
    GPSTIMESTAMP                TIMESTAMP,
    ODS_SRC_SYSTEM_ID           DECIMAL(38, 0),
    ODS_CREATEDBY               VARCHAR(255),
    ODS_MODIFIEDBY              VARCHAR(255),
    ODS_MODIFIEDBY_TIMESTAMP    TIMESTAMP,
    ODS_CREATEDBY_TIMESTAMP     TIMESTAMP,
    CONSTRAINT PK_TEMP_TRANSACTIONS PRIMARY KEY (LOGG_ID, TRANS_ID)
)
;

 